### PR TITLE
Layout: Implement `GaugeAir`

### PR DESCRIPTION
**Pull request by GRAnimated**
Used by Mario when he's running out of oxygen.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)* status: all files reviewed, 2 unresolved discussions (waiting on @GRAnimated)

___
*[`src/Layout/GaugeAir.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119#-O09PkbtB1BobghF_kp_:-O09PkbtB1BobghF_kpa:b-56kgiw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b3b7c699b844dbe0db0130e1b1a3351d30ff4a0e/src/Layout/GaugeAir.h#L27)):*
> ```objc
> private:
>     bool mIsActive = false;
>     bool mIsNotFull;
> ```

Doesn't seem to exist - never listed in the `cpp`, not set in the constructor, so it's only padding here?
___
*[`src/Layout/GaugeAir.cpp` line 54 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119#-O09QefUE8BFZke_-XU5:-O09QefUE8BFZke_-XU6:bj0sx02) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b3b7c699b844dbe0db0130e1b1a3351d30ff4a0e/src/Layout/GaugeAir.cpp#L54)):*
> ```cpp
> 
> void GaugeAir::endMax() {
>     if (!isAlive() || !al::isNerve(this, &NrvGaugeAir.Wait))
> ```

if (!isWait())



_Code quote:_
```cpp
if (!isAlive() || !al::isNerve(this, &NrvGaugeAir.Wait))
```

**Review by GRAnimated — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/GaugeAir.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119#-O09PkbtB1BobghF_kp_:-O0AK2kq4Eela6DXfTsh:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b3b7c699b844dbe0db0130e1b1a3351d30ff4a0e/src/Layout/GaugeAir.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Doesn't seem to exist - never listed in the `cpp`, not set in the constructor, so it's only padding here?
</blockquote></details>

Done.
___
*[`src/Layout/GaugeAir.cpp` line 54 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119#-O09QefUE8BFZke_-XU5:-O0AK30xE-V910EglAn3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b3b7c699b844dbe0db0130e1b1a3351d30ff4a0e/src/Layout/GaugeAir.cpp#L54)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

if (!isWait())
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Comment by MonsterDruide1** [comment]
Requires rebase

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/119)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
