### PR TITLE
`MapObj`: Finish `AnagramAlphabetCharacter`

### PR DESCRIPTION
**Pull request by GRAnimated**
In June of 2023, this actor was the most challenging thing I had worked on at that point. I made many mismatches then and this PR should rectify that.

I'm not sure when, but I guess I also fixed a mismatch in `MofumofuWarpHole` on this branch, so enjoy that as well.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: all files reviewed, 8 unresolved discussions (waiting on @GRAnimated)

___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 117 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3puzuuA2w_LDNNy_hv:-O3puzuuA2w_LDNNy_hw:bagn8e8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L117)):*
> ```cpp
>             al::validateClipping(this);
>             al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
>             capTargetParts->startNormal();
> ```

Ah, this is the inlined block thing you had problems with earlier?



_Code quote:_
```cpp
            CapTargetParts* capTargetParts = mCapTargetParts;
            rs::endHack(&mHackerParent);
            al::validateClipping(this);
            al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
            capTargetParts->startNormal();
```
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 129 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pv60_7wf9btbZ95XU:-O3pv60_7wf9btbZ95XV:breoa48) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L129)):*
> ```cpp
>         al::validateClipping(this);
>         al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
>         capTargetParts->startNormal();
> ```

Same block



_Code quote:_
```cpp
        CapTargetParts* capTargetParts = mCapTargetParts;
        rs::endHack(&mHackerParent);
        al::validateClipping(this);
        al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
        capTargetParts->startNormal();
```
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 143 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pv47r4nRUS4rXN2Wa:-O3pv47r4nRUS4rXN2Wb:breoa48) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L143)):*
> ```cpp
>             al::validateClipping(this);
>             al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
>             capTargetParts->startNormal();
> ```

Same block



_Code quote:_
```cpp
            CapTargetParts* capTargetParts = mCapTargetParts;
            rs::endHackDir(&mHackerParent, dir);
            al::validateClipping(this);
            al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
            capTargetParts->startNormal();
```
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 262 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pwGmRBaUF8M4k6bML:-O3pwGmS3ygtVj9D0phC:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L262)):*
> ```cpp
>     }
> 
>     if (rs::isTriggerHackSwing(mHackerParent) & 1)
> ```





_Suggestion:_
```cpp
if (rs::isTriggerHackSwing(mHackerParent))
```
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 298 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2Lmc6SkbBue9pMfU:-O3q2Lmc6SkbBue9pMfV:b-uupxtv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L298)):*
> ```cpp
> 
> void AnagramAlphabetCharacter::exeHackFall() {
>     al::isFirstStep(this);  // unused call
> ```

I'd make this an `if(al::isFirstStep(this)) {}` to show how this likely happened
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 333 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2a1b72C_lKWK9QjK:-O3q2a1b72C_lKWK9QjL:bldbv8r) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L333)):*
> ```cpp
>     }
> 
>     sead::Vector3f rot = {mPoseMatrix->m[0][2], mPoseMatrix->m[1][2], mPoseMatrix->m[2][2]};
> ```

As said in Discord, this should be labeled `front`
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 341 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2iKe0UphL8qA1kEx:-O3q2iKe0UphL8qA1kEy:b-kygvgq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L341)):*
> ```cpp
>     al::lerpVec(al::getTransPtr(this), al::getTrans(this), pos, 0.5f);
> 
>     if (al::isGreaterEqualStep(this, 0)) {
> ```

Huh, what? When is this *not* run?
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 348 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2qCI9CpqJ4D7Tsla:-O3q2qCI9CpqJ4D7Tslb:b-s2x5mu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L348)):*
> ```cpp
>         al::validateClipping(this);
>         al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
>         capTargetParts->startNormal();
> ```

Same block as earlier



_Code quote:_
```cpp
        CapTargetParts* capTargetParts = mCapTargetParts;
        rs::endHackDir(&mHackerParent, rot);
        al::validateClipping(this);
        al::setNerve(this, &NrvAnagramAlphabetCharacter.HackEnd);
        capTargetParts->startNormal();
```

**Comment by LynxDev2** [comment]
I did some testing and an inline function mismatches for `exeHackGoal` ( https://decomp.me/scratch/VGju5 ), does work for the first two parts of `receiveMsg`, but not for the last one ( https://decomp.me/scratch/VrRJ3 ). Both have a similar one instruction mismatch related to the stack pointer

**Comment by MonsterDruide1** [comment]
The inline function you created here does not call `endHackDir`, but `endHack` instead, thus not taking a `const sead::Vector3f&` as second parameter. Does that fix anything here?

**Comment by LynxDev2** [comment]
Looks like two of them use `endHack` and the other two use `endHackDir`. Passing in the param for `endHackDir` might cause a mismatch and I think I need to make two inline functions?

**Comment by MonsterDruide1** [comment]
Huh, didn't notice them using two different functions so far. As they are not inlined here, you definitely need to call each individual "correct" one, so ... two inline functions, I guess?

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: 7 of 9 files reviewed, 8 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 117 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3puzuuA2w_LDNNy_hv:-O9VDk3q9P2JLRr4-dGk:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L117)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ah, this is the inlined block thing you had problems with earlier?
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 129 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pv60_7wf9btbZ95XU:-O9VDjtt2Ya7JPSMvOxK:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L129)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same block
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 143 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pv47r4nRUS4rXN2Wa:-O9VDjVg2W_zZReLdIX7:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L143)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same block
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 262 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3pwGmRBaUF8M4k6bML:-O9VDi9ZDKgOhF15Z2re:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L262)):*
> ```cpp
>     }
> 
>     if (rs::isTriggerHackSwing(mHackerParent) & 1)
> ```

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 298 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2Lmc6SkbBue9pMfU:-O9VDhEk4wYk0OjG9vVC:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L298)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'd make this an `if(al::isFirstStep(this)) {}` to show how this likely happened
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 333 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2a1b72C_lKWK9QjK:-O9VDfmM-X-d4o7gZzp-:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L333)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

As said in Discord, this should be labeled `front`
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 341 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2iKe0UphL8qA1kEx:-O9VDeuU3TmghuefCI19:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L341)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Huh, what? When is this *not* run?
</blockquote></details>

Done.
___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 348 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2qCI9CpqJ4D7Tsla:-O9VDeQl85LgHy2evBIL:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L348)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same block as earlier
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: all files reviewed, 2 unresolved discussions (waiting on @GRAnimated)

___
*[`src/MapObj/AnagramAlphabetCharacter.h` line 37 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O9VTgZYCQXzPR0rd_r1:-O9VTgZYCQXzPR0rd_r2:b7bsbx5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9580b04145309420ae9a6616b48583214659da14/src/MapObj/AnagramAlphabetCharacter.h#L37)):*
> ```objc
>     inline bool isHack();
>     inline void endHack();
>     inline void endHackDir(const sead::Vector3f& dir);
> ```

Does this cause the functions to end up showing up (with symbol) in the binary?



_Code quote:_
```objc
    inline bool isHack();
    inline void endHack();
    inline void endHackDir(const sead::Vector3f& dir);
```

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: all files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`src/MapObj/AnagramAlphabetCharacter.cpp` line 341 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O3q2iKe0UphL8qA1kEx:-O9VZr3U8aYbH3D6vMjc:b-szjzu0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/dda380f9f6669b504cef86822b11120b720adbd7/src/MapObj/AnagramAlphabetCharacter.cpp#L341)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@LynxDev2 gave two ideas here:
1. `setNerve` initializes the `step` to `-1`, so it might be `-1` in the first iteration - unlikely, as `al::isFirstStep` also compares with `0`.
2. It was a higher number initially (enforce some delay), but got changed to `0` later in development.

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/MapObj/AnagramAlphabetCharacter.h` line 37 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O9VTgZYCQXzPR0rd_r1:-O9VaL_g0wazpmWpJ01n:b-vxfzpc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9580b04145309420ae9a6616b48583214659da14/src/MapObj/AnagramAlphabetCharacter.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Does this cause the functions to end up showing up (with symbol) in the binary?
</blockquote></details>

Although `strings` shows both mangled and demangled names for those, `tools/listsym` and `objdump` don't find them, so I don't think they appear in the executable

**Review by MonsterDruide1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

___
*[`src/MapObj/AnagramAlphabetCharacter.h` line 37 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/143#-O9VTgZYCQXzPR0rd_r1:-O9VlUP_-It8KFt0rY2J:b-2g97u6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9580b04145309420ae9a6616b48583214659da14/src/MapObj/AnagramAlphabetCharacter.h#L37)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

Although `strings` shows both mangled and demangled names for those, `tools/listsym` and `objdump` don't find them, so I don't think they appear in the executable
</blockquote></details>

Hmm, might just be our debug settings not being absolutely right. I guess we're fine then.

**Pull request merged**
