### PR TITLE
Library/MapObj: Implement `BreakMapPartsBase`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `BreakMapPartsBase` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29tG5f8Rn4K36IFDGm:-O29tG5f8Rn4K36IFDGn:b-q3e8bw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L23)):*
> ```objc
>     void startBreakByProgram();
>     bool receiveMsg(const SensorMsg* message, HitSensor* source, HitSensor* target) override;
>     virtual JudgeFunc getJudgeFunction(const char* name) const;
> ```

Are you sure that this is `JudgeFunc` and not `JudgeFunc*` or `const JudgeFunc&`?
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29rzvd6LAzFZTDtJ76:-O29rzvd6LAzFZTDtJ77:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L28)):*
> ```objc
>     JudgeFunc mJudgeFunction = nullptr;
>     MtxConnector* mMtxConnector = nullptr;
>     sead::Vector3f mItemOffset = {0, 0, 0};
> ```





_Suggestion:_
```objc
{0.0f, 0.0f, 0.0f};
```
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29ssRw2oTm1zVTyw1B:-O29ssRw2oTm1zVTyw1C:b-cs2x8z) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L135)):*
> ```cpp
>         }
> 
>         return;
> ```

Merges the `kill()` in here with the one at the end of the function



_Suggestion:_
```cpp
        if (isExistAction(this, "Break")) {
            startAction(this, "Break");
            hideModelIfShow(this);
            return;
        }
```
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 154 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29t2wT-cO6tDpmLQmA:-O29t2wT-cO6tDpmLQmB:b4cphe3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L154)):*
> ```cpp
>     startBreakByProgram();
> 
>     return true;
> ```

Flip this logic, `if(...) return true;` and at the end of the function `return false;` for the standard path



_Code quote:_
```cpp
    if (!isNerve(this, &NrvBreakMapPartsBase.Wait) || !mJudgeFunction(message, source, target))
        return false;

    startBreakByProgram();

    return true;
```
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 158 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29s8651TfNGDpf_esw:-O29s866CzPGswLwOpgK:b-lyer3y) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L158)):*
> ```cpp
> 
> JudgeFunc BreakMapPartsBase::getJudgeFunction(const char* name) const {
>     return nullptr;
> ```

Wow, misleading. Huh.

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: 9 of 11 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29tG5f8Rn4K36IFDGm:-O29w94A9I-_cZJay7cv:b-kw74n5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Are you sure that this is `JudgeFunc` and not `JudgeFunc*` or `const JudgeFunc&`?
</blockquote></details>

`JudgeFunc` is a pointer to a function which have the same signature as `receiveMsg` I just typedefed it to avoid writing `bool (\*)(const SensorMsg\* message, HitSensor\* source, HitSensor\* target)` everywhere.
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29rzvd6LAzFZTDtJ76:-O29x90G0Ail_UY7nMTr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L28)):*
> ```objc
>     JudgeFunc mJudgeFunction = nullptr;
>     MtxConnector* mMtxConnector = nullptr;
>     sead::Vector3f mItemOffset = {0, 0, 0};
> ```

Done.
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29ssRw2oTm1zVTyw1B:-O2A0YWS4HhbjG6hjnKl:bakb65l) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L135)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Merges the `kill()` in here with the one at the end of the function
</blockquote></details>

It didn't match with this code.
https://decomp.me/scratch/AVDqh
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 154 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29t2wT-cO6tDpmLQmA:-O29zXFr96XLuHwuRHuP:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L154)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Flip this logic, `if(...) return true;` and at the end of the function `return false;` for the standard path
</blockquote></details>

Done.
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 158 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29s8651TfNGDpf_esw:-O2A1G_v7Y955rZxtvOZ:baa3kcj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L158)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Wow, misleading. Huh.
</blockquote></details>

What do you mean by misleading?

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29tG5f8Rn4K36IFDGm:-O2A3xXL9dlFZ9uj-9pI:b-jxypr2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L23)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

`JudgeFunc` is a pointer to a function which have the same signature as `receiveMsg` I just typedefed it to avoid writing `bool (\*)(const SensorMsg\* message, HitSensor\* source, HitSensor\* target)` everywhere.
</blockquote></details>

Yeah, it was just because that looked like a `return-by-value`, which is rather unusual. But looking at `rs::getBreakJudgeFunction`, I can confirm that this is a single-pointer.
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 135 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29ssRw2oTm1zVTyw1B:-O2A3haI7wnvDPgAGTIw:b-gnhvzi) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L135)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It didn't match with this code.
https://decomp.me/scratch/AVDqh
</blockquote></details>

Weird that they duplicated that call then... but I can't get a better match either. Ignore my comment then.
___
*[`lib/al/Library/MapObj/BreakMapPartsBase.cpp` line 158 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29s8651TfNGDpf_esw:-O2A3O3e04eL6gFCT8sh:bh3lcpq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.cpp#L158)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

What do you mean by misleading?
</blockquote></details>

`get` usually returns a static member variable, and `mJudgeFunction` is a variable here. This thing still returns `nullptr` though, as it's used the other way around - providing a function pointer to store into the variable. That's unusual.
___
*[`lib/al/Library/Stage/StageSwitchUtil.h` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O2A5w4y6ywCwwLlGbdy:-O2A5w4y6ywCwwLlGbdz:bddmnhc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/046966ef9e6f611eadb62753e60ad46512aa74b0/lib/al/Library/Stage/StageSwitchUtil.h#L32)):*
> ```objc
> bool isOnSwitchStart(const IUseStageSwitch* user);
> 
> inline void initStageSwitchListener(LiveActor* actor) {
> ```

Not entirely sure about this one yet, let's discuss it on Discord. The name is not nice though, as there are other ways to initialize the listener.

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/BreakMapPartsBase.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O29tG5f8Rn4K36IFDGm:-O2Ft9HPDJOn869twuSa:b-qh5qws) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e74dbde7a5fbd5367c81bc33fd4aa8f6c4d2337e/lib/al/Library/MapObj/BreakMapPartsBase.h#L23)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Yeah, it was just because that looked like a `return-by-value`, which is rather unusual. But looking at `rs::getBreakJudgeFunction`, I can confirm that this is a single-pointer.
</blockquote></details>

I renamed the type to `JudgeFuncPtr` to avoid any misinterpretation.
___
*[`lib/al/Library/Stage/StageSwitchUtil.h` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O2A5w4y6ywCwwLlGbdy:-O2Fu-lw45YXg95Ye6xB:bmn0qcj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/046966ef9e6f611eadb62753e60ad46512aa74b0/lib/al/Library/Stage/StageSwitchUtil.h#L32)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Not entirely sure about this one yet, let's discuss it on Discord. The name is not nice though, as there are other ways to initialize the listener.
</blockquote></details>

As discussed on discord I made the function only defined in the `cpp` file and `static` to avoid external linkage.
Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/LiveActor/ActorInitFunction.cpp` line 8 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O2Gh0UZA66cs3ct31uz:-O2Gh0UZA66cs3ct31v-:b-ssei7w) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0720ce9b81ce8dedbef116231a59b13900c0ffcf/lib/al/Library/LiveActor/ActorInitFunction.cpp#L8)):*
> ```cpp
> 
> namespace al {
> bool trySyncStageSwitchKill(LiveActor* actor) {
> ```

Why is this one mismatching? Can we get it matching before, or at least mark it as `NON_MATCHING`?

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/LiveActor/ActorInitFunction.cpp` line 8 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-O2Gh0UZA66cs3ct31uz:-O2Gj-4SEcXWOJt0an9d:budo7se) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0720ce9b81ce8dedbef116231a59b13900c0ffcf/lib/al/Library/LiveActor/ActorInitFunction.cpp#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Why is this one mismatching? Can we get it matching before, or at least mark it as `NON_MATCHING`?
</blockquote></details>

Oops I replaced `actor->makeActorAlive()` with `actor->appear()` by accident.
Done

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Review by MonsterDruide1 — APPROVED** [review]
Requires a rebase

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-:-O2P4huN2DD7HGi5-Sx4:b-vr14xc)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Review by Fuzzy2319 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134#-:-O2Q40aB-uPObi_-008W:b-896fix)* status: 10 of 13 files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/134)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
