### PR TITLE
Player: Implement PlayerCounterGetCoin

### PR DESCRIPTION
**Pull request by GRAnimated**
Very small unused class.
I had to add `al::converge` functions here, and I've placed them in `MathUtil.h` as that seems to be full of the unorganized stuff. That being said, I'm pretty sure we agreed on un-splitting `MathUtil.h` in Discord, so that should happen at some point.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58)* status: all files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`src/Player/PlayerCounterGetCoin.cpp` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58#-NzNPTBABOjcCGjMUex2:-NzNPTBABOjcCGjMUex3:bmw3qcc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/153922cb94af2dafbc0fb203007cf6778fb4d363/src/Player/PlayerCounterGetCoin.cpp#L15)):*
> ```cpp
>     if (newTime > 720)
>         newTime = 720;
>     mTimer = newTime;
> ```

`sead::Mathi::clampMax(mTimer+90, 720)`



_Code quote:_
```cpp
    s32 newTime = mTimer + 90;
    if (newTime > 720)
        newTime = 720;
    mTimer = newTime;
```

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerCounterGetCoin.cpp` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58#-NzNPTBABOjcCGjMUex2:-NzOvK7h-RADsvbttAV3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/153922cb94af2dafbc0fb203007cf6778fb4d363/src/Player/PlayerCounterGetCoin.cpp#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`sead::Mathi::clampMax(mTimer+90, 720)`
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Comment by MonsterDruide1** [comment]
Needs a rebase ^

**Comment by GRAnimated** [comment]
Rebased

**Review by MonsterDruide1 — APPROVED** [review]
Thanks!

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/58#-:-NzY8nIY7H_a_DbaDZEB:b-ucfknh)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
