### PR TITLE
`al`: add ActorPoseKeeper header and some utility functions

### PR DESCRIPTION
**Pull request by fruityloops1**
This change is [Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Wow, the `ActorPoseKeepers` are quite something worth. Thanks for adding all of that!

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-:-Mu0N5BoBTOjmv-pNUiu:bc1m12f)* status: all files reviewed, 9 unresolved discussions (waiting on @fruityloops1)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MvTlCWUkAb_pTTvA):*
If possible, please change the commit messages to the common format of `location: change`.
___
*[lib/al/LiveActor/ActorPoseKeeper.h, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0KpBW3V2vlAjz6aOg:-Mu0KpBW3V2vlAjz6aOh:b-kcus5d) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/LiveActor/ActorPoseKeeper.h#L3)):*
> ```objc
> #pragma once
> 
> #include "math/seadMatrix.h"
> ```

These should go into less-than/more-than bracket signs (`#include <math/seadMatrix.h>`)
___
*[lib/al/LiveActor/ActorPoseKeeper.h, line 123 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0LTsA5ZzcWlrDpFik:-Mu0LTsA5ZzcWlrDpFil:b-ezrenq) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/LiveActor/ActorPoseKeeper.h#L123)):*
> ```objc
> };
> 
> class ActorPoseKeeperTQGMSV : public ActorPoseKeeperTQGSV {
> ```

This does still directly inherit from `ActorPoseKeeperBase`, not `TQGSV`.
___
*[lib/al/LiveActor/ActorPoseKeeper.h, line 163 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0Le7Z0yhbFM72LyUI:-Mu0Le7Z0yhbFM72LyUJ:b1tu95s) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/LiveActor/ActorPoseKeeper.h#L163)):*
> ```objc
> };
> 
> class ActorPoseKeeperTRMSV : public ActorPoseKeeperTRSV {
> ```

This does still directly inherit from `ActorPoseKeeperBase`, not `TRSV`.
___
*[lib/al/LiveActor/LiveActor.h, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0LmjL0NtlQfGZXvEV:-Mu0LmjL0NtlQfGZXvEW:b3kuoox) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/LiveActor/LiveActor.h#L12)):*
> ```objc
> #include "al/iuse/IUseEffectKeeper.h"
> #include "al/nerve/Nerve.h"
> #include "al/LiveActor/ActorPoseKeeper.h"
> ```

This is not a wanted change. Including all subclasses as header slows down compile time as they need to be loaded and included manually, while a simple stub is faster to parse and compile. Only include the headers when actually using their contents later.
___
*[lib/al/util/MathUtil.h, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MAkJ8gRbBa3cJ9iv:-Mu0MAkJ8gRbBa3cJ9iw:b-ugcr7i) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/util/MathUtil.h#L3)):*
> ```objc
> #pragma once
> 
> #include "math/seadVector.h"
> ```

This should go into less-than/more-than bracket signs (`#include <math/seadVector.h>`)
___
*[src/al/util/LiveActorUtil.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MEc96VfQ7y1d01DG:-Mu0MEc96VfQ7y1d01DH:bmnw23w) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/src/al/util/LiveActorUtil.cpp#L3)):*
> ```cpp
> #include "al/util/LiveActorUtil.h"
> #include "al/util/MathUtil.h"
> #include "math/seadVector.h"
> ```

This should go into less-than/more-than bracket signs (`#include <math/seadVector.h>`), and at the very top of the include list (for style, as they are "library headers")
___
*[src/al/util/LiveActorUtil.cpp, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MQ1l2XfPCqyiRz4N:-Mu0MQ1l2XfPCqyiRz4O:bf0x5a4) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/src/al/util/LiveActorUtil.cpp#L12)):*
> ```cpp
>     const sead::Vector3f* l2Trans = al::getTrans(l2);
>     const sead::Vector3f* l1Trans = al::getTrans(l1);
>     float x = l2Trans->x - l1Trans->x;
> ```

Did you try to use vector subtraction? Does that generate better code, or does that have the same issue? Maybe also `length()`on the vector itself might be worth a try.
___
*[src/al/util/LiveActorUtil.cpp, line 22 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0Mmcd1S5J5lC-zp8R:-Mu0Mmce0pvG1xMySDza:b-lrmc6z) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/src/al/util/LiveActorUtil.cpp#L22)):*
> ```cpp
> float calcSpeed(const al::LiveActor* actor) {
>     const sead::Vector3f* velocity = actor->mPoseKeeper->getVelocity();
>     return sqrtf(velocity->x * velocity->x + velocity->y * velocity->y + velocity->z * velocity->z);
> ```

Same here (and all below), what about `velocity.length()`?

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12)* status: all files reviewed, 6 unresolved discussions (waiting on @fruityloops1 and @MonsterDruide1)

___
*[lib/al/LiveActor/ActorPoseKeeper.h, line 31 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu1RiWa5Dwh3pd00FrO:-Mu1RiWa5Dwh3pd00FrP:b-ensje7) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/fa9e00dd643877ed1fdf27ebfe85e177ca57f12f/lib/al/LiveActor/ActorPoseKeeper.h#L31)):*
> ```objc
>     virtual void updatePoseQuat(const sead::Quatf&);
>     virtual void updatePoseMtx(const sead::Matrix34f&);
>     virtual void copyPose(const ActorPoseKeeperBase&);
> ```

Telling from the function symbol, this is a pointer and not a reference.
___
*[src/al/util/LiveActorUtil.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MEc96VfQ7y1d01DG:-Mu1S0FjEb4N-Vf5-WUe:b-q2hk5j) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/src/al/util/LiveActorUtil.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This should go into less-than/more-than bracket signs (`#include <math/seadVector.h>`), and at the very top of the include list (for style, as they are "library headers")
</blockquote></details>

Please move this to the top of the `#include` list, as it is a library file.
___
*[src/al/util/LiveActorUtil.cpp, line 30 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu1SXnm-PswGB0J84Y5:-Mu1SXnm-PswGB0J84Y6:b-bu2s20) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/fa9e00dd643877ed1fdf27ebfe85e177ca57f12f/src/al/util/LiveActorUtil.cpp#L30)):*
> ```cpp
>     const sead::Vector3f& gravity = al::getGravity(actor);
> 
>     return -(velocity.x * gravity.x + velocity.y * gravity.y + velocity.z * gravity.z);
> ```

This does not pull the `sqrt`, so it is probably `velocity.dot(gravity)`.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12)* status: all files reviewed, 6 unresolved discussions (waiting on @fruityloops1)

___
*[src/al/util/LiveActorUtil.cpp, line 12 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MQ1l2XfPCqyiRz4N:-Mu1Xfeo-AoTxuihRy_z:b-jx6307) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/src/al/util/LiveActorUtil.cpp#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Did you try to use vector subtraction? Does that generate better code, or does that have the same issue? Maybe also `length()`on the vector itself might be worth a try.
</blockquote></details>

You have to also implement `_ZN2al12calcDistanceEPKNS_9LiveActorERKN4sead7Vector3IfEE` and call that function, to get it inlined for a better match.

**Comment by fruityloops1** [comment]
___
*[lib/al/LiveActor/ActorPoseKeeper.h, line 31 at r2](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu1RiWa5Dwh3pd00FrO:-Mu1XFu3-m2SvW57GEuD:b-alhni9) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/fa9e00dd643877ed1fdf27ebfe85e177ca57f12f/lib/al/LiveActor/ActorPoseKeeper.h#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Telling from the function symbol, this is a pointer and not a reference.
</blockquote></details>

I accidentally changed that while changing all the getter functions to return references, undoing

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12)* status: all files reviewed, 3 unresolved discussions (waiting on @fruityloops1)

___
*[-- commits, line 21 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu1exWp2ihz9_o9YURO):*
When you're done adding fixing commits, please either recreate the commits (`git reset master` to remove commits while keeping files, then re-commit), or squash them into single commits matching the files/"topics" of work.
___
*[lib/al/util/MathUtil.h, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-Mu0MAkJ8gRbBa3cJ9iv:-Mu1ehCnB-lt81dAO2hv:bos8qix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/a20c751939be3142b500389a4fc767d171cd5a2b/lib/al/util/MathUtil.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This should go into less-than/more-than bracket signs (`#include <math/seadVector.h>`)
</blockquote></details>

This is still remaining.

**Review by MonsterDruide1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/12#-:-Mu1ic6z0zLrIgOykjuo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @fruityloops1)

**Pull request merged**
