### PR TITLE
Library/MapObj: Implement `ClockMapParts`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `ClockMapParts` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)

### CODE REVIEW

**Review by LynxDev2 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-OCrPZE57AiFoMnhsWAa:-OCrPZE57AiFoMnhsWAb:bru833v) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/66d9cf2f374fe33e0b14e98eba6bd371a6948050/lib/al/Library/MapObj/ClockMapParts.cpp#L50)):*
> ```cpp
>     registSupportFreezeSyncGroup(this, info);
> 
>     *(sead::BaseQuat<f32>*)&mQuat = getQuat(this);
> ```

`mQuat = getQuat(this);`



_Code quote:_
```cpp
*(sead::BaseQuat<f32>*)&mQuat = getQuat(this);
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-OCrPZE57AiFoMnhsWAa:-OCrRBXEAbz0Ron2fAkC:bnogl7b) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/66d9cf2f374fe33e0b14e98eba6bd371a6948050/lib/al/Library/MapObj/ClockMapParts.cpp#L50)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

`mQuat = getQuat(this);`
</blockquote></details>

No it doesn't match this way.
I initially wrote it this way
https://decomp.me/scratch/PjTuh
and then after a discuting with @MonsterDruide1 on discord, it found that assigning to `BaseQuat` match also
https://decomp.me/scratch/DMDBE
but creating a `Quat::set(const Quat&)` function might be better than what I did here.

**Comment by MonsterDruide1** [comment]
Blocked by https://github.com/open-ead/sead/pull/148

**Comment by MonsterDruide1** [comment]
Unblocked - please rebase and update accordingly.

**Review by Fuzzy2319 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-:-ODVyO2yDFtDa3e6yFLK:bb6un1j)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @LynxDev2 and @MonsterDruide1)

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 9 unresolved discussions (waiting on @Fuzzy2319 and @LynxDev2)

___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 200 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQZc83IJemhgZLx4-:-ODXQZc83IJemhgZLx40:batiqca) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L200)):*
> ```cpp
>         startNerveAction(this, "RotateSign");
>     else
>         startNerveAction(this, "Rotate");
> ```

Does this match?



_Suggestion:_
```cpp
    else
        setRotateStartNerve();
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 221 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQRIS4WhIu_ADf9ez:-ODXQRIS4WhIu_ADf9f-:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L221)):*
> ```cpp
>     }
> 
>     startNerveAction(this, "RotateSign");
> ```





_Suggestion:_
```cpp
    if (mTimer >= mRotateTimer)
        startNerveAction(this, "AssistStopEndWait");
    else if (mTimer >= mRotateSignTime)
        startNerveAction(this, "Rotate");
    else
        startNerveAction(this, "RotateSign");
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 238 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQfcUChCInHWtQrzh:-ODXQfcUChCInHWtQrzi:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L238)):*
> ```cpp
>     }
> 
>     startNerveAction(this, "Rotate");
> ```





_Suggestion:_
```cpp
    if (mRotateSignTime > 0) {
        startNerveAction(this, "RotateSign");
    else
        startNerveAction(this, "Rotate");
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 252 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPMwU2qlp5YP9mSBN:-ODXPMwU2qlp5YP9mSBO:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L252)):*
> ```cpp
>         tryStartAction(this, "MiddleSign");
> 
>     f32 tmp = modf((f32)(mCurrentStep * mClockAngleDegree) + 360.0f, 360.0f) + 0.0f;
> ```





_Suggestion:_
```cpp
f32 angle = modf((f32)(mCurrentStep * mClockAngleDegree) + 360.0f, 360.0f) + 0.0f;
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 261 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPQG3DIOU1hoVVJG8:-ODXPQG3DIOU1hoVVJG9:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L261)):*
> ```cpp
>         return;
> 
>     startNerveAction(this, "Rotate");
> ```





_Suggestion:_
```cpp
    if (mTimer >= mRotateSignTime)
        startNerveAction(this, "Rotate");
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 269 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPp3yESb2o_Bqnv3c:-ODXPp3yESb2o_Bqnv3d:b8rhkk4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L269)):*
> ```cpp
>                              (f32)mClockAngleDegree +
>                          360.0f,
>                      360.0f);
> ```

Please splilt that into more temporary variables, to make it actually readable. `(x + mCurrentStep) * mClockAngleDegree + 360.0f` should be good. Also, to make it similar to the `exeRotateSign`, move `+0.0f` into this `modf` statement as well.



_Code quote:_
```cpp
    f32 angle = modf((((f32)(mTimer - mRotateSignTime) / (f32)(mRotateTimer + ~mRotateSignTime)) +
                      (f32)mCurrentStep) *
                             (f32)mClockAngleDegree +
                         360.0f,
                     360.0f);
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 278 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPhd-8NIHkcVJWT2d:-ODXPhd-8NIHkcVJWT2e:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L278)):*
> ```cpp
>     mCurrentStep = modi(mCurrentStep + mTurnStepCount + 1, mTurnStepCount);
>     startNerveAction(this, "Wait");
>     tryStartSe(this, "RotateEnd");
> ```





_Suggestion:_
```cpp
    if (mTimer >= mRotateTimer) {
        mCurrentStep = modi(mCurrentStep + mTurnStepCount + 1, mTurnStepCount);
        startNerveAction(this, "Wait");
        tryStartSe(this, "RotateEnd");
    }
```
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 283 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXRPB0-t-b7R9A9AtB:-ODXRPB0-t-b7R9A9AtC:b-myey0b) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L283)):*
> ```cpp
> void ClockMapParts::exeWait() {
>     mTimer++;
>     if (mActiveTimer <= mTimer) {
> ```

Should make the intention clearer (variable is at the front)



_Suggestion:_
```cpp
if (mTimer >= ActiveTimer) {
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 9 unresolved discussions (waiting on @LynxDev2 and @MonsterDruide1)

___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 200 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQZc83IJemhgZLx4-:-ODXTjQuDuGgs4ON3Hou:bogylse) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L200)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Does this match?
</blockquote></details>

Yes.
Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 269 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPp3yESb2o_Bqnv3c:-ODXVuC7BuvIArfIF5Uk:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L269)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please splilt that into more temporary variables, to make it actually readable. `(x + mCurrentStep) * mClockAngleDegree + 360.0f` should be good. Also, to make it similar to the `exeRotateSign`, move `+0.0f` into this `modf` statement as well.
</blockquote></details>

Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 283 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXRPB0-t-b7R9A9AtB:-ODXWI3DBkJnSOMQYDDd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L283)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should make the intention clearer (variable is at the front)
</blockquote></details>

Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 221 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQRIS4WhIu_ADf9ez:-ODXU8IM9vST9aF4grsl:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L221)):*
> ```cpp
>     }
> 
>     startNerveAction(this, "RotateSign");
> ```

Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 238 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXQfcUChCInHWtQrzh:-ODXUO4BDdkwy2u8vsbA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L238)):*
> ```cpp
>     }
> 
>     startNerveAction(this, "Rotate");
> ```

Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 252 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPMwU2qlp5YP9mSBN:-ODXUXhAEYkTthxsTILF:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L252)):*
> ```cpp
>         tryStartAction(this, "MiddleSign");
> 
>     f32 tmp = modf((f32)(mCurrentStep * mClockAngleDegree) + 360.0f, 360.0f) + 0.0f;
> ```

Done.
___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 278 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-ODXPhd-8NIHkcVJWT2d:-ODXW0Fe4lfmL9wIGJXg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9470e361ab2b516ab5861018e7154738218dcd9b/lib/al/Library/MapObj/ClockMapParts.cpp#L278)):*
> ```cpp
>     mCurrentStep = modi(mCurrentStep + mTurnStepCount + 1, mTurnStepCount);
>     startNerveAction(this, "Wait");
>     tryStartSe(this, "RotateEnd");
> ```

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319 and @LynxDev2)

___
*[`lib/al/Library/MapObj/ClockMapParts.cpp` line 119 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204#-OEBQzCQCDD3fCgsMtF9:-OEBQzCQCDD3fCgsMtFA:b-um0uaw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/77f20dcad339aa147940eb10bf3e3d71e9da9bcb/lib/al/Library/MapObj/ClockMapParts.cpp#L119)):*
> ```cpp
>     }
> 
>     startNerveAction(this, "Rotate");
> ```

Also, in any case connect with `else` to above to avoid early-return



_Suggestion:_
```cpp
    setRotateStartNerve();
```

**Review by LynxDev2 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/204)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
