### PR TITLE
Layout: Implement `FilterFly` and `FilterScope`

### PR DESCRIPTION
**Pull request by GRAnimated**
I'm not sure how I forgot about this one. I had this fully decompiled 3 weeks ago and must have lost it in my pile of branches (that I'm going to clean up). These are used by the binoculars capture.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: all files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`src/Layout/FilterFly.h` line 22 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O09Oqu4CY9Lro9sJBs2:-O09Oqu4CY9Lro9sJBs3:bk8xvn4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9b51a0dc3ddc61a8dfa77415a28d31d937b69798/src/Layout/FilterFly.h#L22)):*
> ```objc
> private:
>     sead::Vector2f mTargetPos = sead::Vector2f::zero;
>     sead::Vector2f mTargetPos2 = sead::Vector2f::zero;
> ```

This name doesn't really fit, it's something else... almost like a velocity to make the position overshoot `mTargetPos` if pointed in the same direction for enough time. Did you try to take a look at some values during runtime to make more sense of the calculations?

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Layout/FilterFly.h` line 22 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O09Oqu4CY9Lro9sJBs2:-O0AKO_FDsnMGfhDWJPf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9b51a0dc3ddc61a8dfa77415a28d31d937b69798/src/Layout/FilterFly.h#L22)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This name doesn't really fit, it's something else... almost like a velocity to make the position overshoot `mTargetPos` if pointed in the same direction for enough time. Did you try to take a look at some values during runtime to make more sense of the calculations?
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

___
*[`src/Layout/FilterFly.h` line 22 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O09Oqu4CY9Lro9sJBs2:-O1sVLGIBqDIt3A2gadr:be2i66h) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9b51a0dc3ddc61a8dfa77415a28d31d937b69798/src/Layout/FilterFly.h#L22)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Testing those variables at runtime, it seems to reflect values that match their descriptions now.

**Review by MonsterDruide1 — APPROVED** [review]
Needs a rebase.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-:-O1sVerA5lK6s-vDUqeh:b-dw4aal)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r4, 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @GRAnimated)

___
*[`src/Layout/FilterFly.h` line 13 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQsAh2r-mj6RK2YlI:-O1wQsAh2r-mj6RK2YlJ:b-ngtg7w) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterFly.h#L13)):*
> ```objc
> class FilterFly : public al::LayoutActor {
> public:
>     FilterFly(const char*, const al::LayoutInitInfo&, const char*);
> ```

Missing parameter names, did exist before (`name, info, suffix`)
___
*[`src/Layout/FilterFly.h` line 17 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQuuQ9ppXRMyuWO3k:-O1wQuuQ9ppXRMyuWO3l:b7jn15g) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterFly.h#L17)):*
> ```objc
>     void exeWaitEnd();
>     void exeMove();
>     void move(const sead::Vector2f&);
> ```

`target`
___
*[`src/Layout/FilterScope.h` line 11 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQd2u5v1O9Nn2pjJJ:-O1wQd2u5v1O9Nn2pjJK:bwdch37) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterScope.h#L11)):*
> ```objc
> class FilterScope : public al::LayoutActor {
> public:
>     FilterScope(const char*, const al::LayoutInitInfo&, const char*);
> ```

Missing parameter names. That's a rebasing regression, those did exist before (`name, info, suffix`).

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/FilterFly.h` line 13 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQsAh2r-mj6RK2YlI:-O1wUp9B7gOagX96wmSG:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterFly.h#L13)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing parameter names, did exist before (`name, info, suffix`)
</blockquote></details>

Done.
___
*[`src/Layout/FilterFly.h` line 17 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQuuQ9ppXRMyuWO3k:-O1wUpVc5PxBwrqvi7TD:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterFly.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`target`
</blockquote></details>

Done.
___
*[`src/Layout/FilterScope.h` line 11 at r5](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117#-O1wQd2u5v1O9Nn2pjJJ:-O1wV07S4i-cNpnxB8DJ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3d594f240de154e404f7282e2a937745b87d04ff/src/Layout/FilterScope.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing parameter names. That's a rebasing regression, those did exist before (`name, info, suffix`).
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 6 files at r4, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/117)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
