### PR TITLE
Layout: Implement `MapTerrainLayout`

### PR DESCRIPTION
**Pull request by GRAnimated**
This small class contains a single pane of world's map texture. Used in `MapLayout`.

Requires `System/MapDataHolder.h`, along with a `MapData` struct for the loaded data.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)* status: all files reviewed, 8 unresolved discussions (waiting on @GRAnimated)

___
*[`src/Layout/MapTerrainLayout.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHmBY-0RGxYFdRLF5:-O-zHmBY-0RGxYFdRLF6:b-q19qv7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L5)):*
> ```objc
> #include "Library/Layout/LayoutActor.h"
> 
> #include "System/MapDataHolder.h"
> ```

forward-declare
___
*[`src/Layout/MapTerrainLayout.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHsUK1GzSknuE_a51:-O-zHsUK1GzSknuE_a52:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L9)):*
> ```objc
> class MapTerrainLayout : public al::LayoutActor {
> public:
>     MapTerrainLayout(const char*);
> ```





_Suggestion:_
```objc
    MapTerrainLayout(const char* name);
```
___
*[`src/Layout/MapTerrainLayout.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHtyG8FF06Lh0XkjB:-O-zHtyG8FF06Lh0XkjC:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L11)):*
> ```objc
>     MapTerrainLayout(const char*);
> 
>     bool tryChangePrintWorld(s32);
> ```





_Suggestion:_
```objc
    bool tryChangePrintWorld(s32 worldId);
```
___
*[`src/System/MapDataHolder.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJgMUB-0d0fBupoh9:-O-zJgMUB-0d0fBupohA:b-q7iglj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L25)):*
> ```objc
>     void* field_B8;
>     s32 mPartsNum;
>     void** mParts;
> ```

At least add a short comment behind it like `// TODO unknown type` to show that this is not really a `void*` array
___
*[`src/System/MapDataHolder.h` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJLSyCQ0NmZoBYewv:-O-zJLSyCQ0NmZoBYeww:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L33)):*
> ```objc
> public:
>     MapDataHolder(const GameDataHolder*);
>     void loadMapData(al::Resource*, const char*, s32);
> ```





_Suggestion:_
```objc
    MapData* loadMapData(al::Resource*, const char*, s32);
```
___
*[`src/System/MapDataHolder.h` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJQPC8dHhoJZTiyrR:-O-zJQPC8dHhoJZTiyrS:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L34)):*
> ```objc
>     MapDataHolder(const GameDataHolder*);
>     void loadMapData(al::Resource*, const char*, s32);
>     bool tryLoadMapData(al::Resource*, const char*, s32);
> ```





_Suggestion:_
```objc
    MapData* tryLoadMapData(al::Resource*, const char*, s32);
```
___
*[`src/System/MapDataHolder.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ-xe5AXw5Um7b_JC:-O-zJ-xf9cSvq_8IHn8d:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L35)):*
> ```objc
>     void loadMapData(al::Resource*, const char*, s32);
>     bool tryLoadMapData(al::Resource*, const char*, s32);
>     void findViewMtx(s32);
> ```





_Suggestion:_
```objc
    const sead::Matrix34f& findViewMtx(s32) const;
```
___
*[`src/System/MapDataHolder.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ8Yt8LqfolLiCq9_:-O-zJ8Yt8LqfolLiCq9a:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L36)):*
> ```objc
>     bool tryLoadMapData(al::Resource*, const char*, s32);
>     void findViewMtx(s32);
>     void findMapData(s32);
> ```





_Suggestion:_
```objc
    const MapData& findMapData(s32) const;
```

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)* status: all files reviewed, 8 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/MapTerrainLayout.h` line 5 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHmBY-0RGxYFdRLF5:-O0098CxEbvF2rTyV9KA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L5)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

forward-declare
</blockquote></details>

Done.
___
*[`src/Layout/MapTerrainLayout.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHsUK1GzSknuE_a51:-O009Bl_2fXvcFNkgKKw:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L9)):*
> ```objc
> class MapTerrainLayout : public al::LayoutActor {
> public:
>     MapTerrainLayout(const char*);
> ```

Done.
___
*[`src/Layout/MapTerrainLayout.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zHtyG8FF06Lh0XkjB:-O009C5eBKPzXsThSvzl:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/Layout/MapTerrainLayout.h#L11)):*
> ```objc
>     MapTerrainLayout(const char*);
> 
>     bool tryChangePrintWorld(s32);
> ```

Done.
___
*[`src/System/MapDataHolder.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJgMUB-0d0fBupoh9:-O009IyE6Bs4EQGZekkR:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

At least add a short comment behind it like `// TODO unknown type` to show that this is not really a `void*` array
</blockquote></details>

Done.
___
*[`src/System/MapDataHolder.h` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJLSyCQ0NmZoBYewv:-O009VHA7jBZi1K93hAq:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L33)):*
> ```objc
> public:
>     MapDataHolder(const GameDataHolder*);
>     void loadMapData(al::Resource*, const char*, s32);
> ```

Done.
___
*[`src/System/MapDataHolder.h` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJQPC8dHhoJZTiyrR:-O009Okl-D-HQxZShsaR:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L34)):*
> ```objc
>     MapDataHolder(const GameDataHolder*);
>     void loadMapData(al::Resource*, const char*, s32);
>     bool tryLoadMapData(al::Resource*, const char*, s32);
> ```

Done.
___
*[`src/System/MapDataHolder.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ-xe5AXw5Um7b_JC:-O009Vuw8nw4NIT2kzBO:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L35)):*
> ```objc
>     void loadMapData(al::Resource*, const char*, s32);
>     bool tryLoadMapData(al::Resource*, const char*, s32);
>     void findViewMtx(s32);
> ```

Done.
___
*[`src/System/MapDataHolder.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ8Yt8LqfolLiCq9_:-O009WB37DIArOLboBk1:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L36)):*
> ```objc
>     bool tryLoadMapData(al::Resource*, const char*, s32);
>     void findViewMtx(s32);
>     void findMapData(s32);
> ```

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)* status: all files reviewed, 2 unresolved discussions (waiting on @GRAnimated)

___
*[`src/System/MapDataHolder.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ-xe5AXw5Um7b_JC:-O00GeiwCh4qRAYA9rme:b-bkjbuq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L35)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing `const`
___
*[`src/System/MapDataHolder.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ8Yt8LqfolLiCq9_:-O00GgJN5jF_DqOjs2Ti:b-bkjbuq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L36)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing `const`

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/System/MapDataHolder.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ-xe5AXw5Um7b_JC:-O00H3t11jsSQ6w8YEUd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing `const`
</blockquote></details>

Done.
___
*[`src/System/MapDataHolder.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112#-O-zJ8Yt8LqfolLiCq9_:-O00H44s-WSTg3ELcPra:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/cf4847d8566b2fca9f168f8ac6c1a61d7a4355dc/src/System/MapDataHolder.h#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing `const`
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/112)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
