### PR TITLE
More mod headers

### PR DESCRIPTION
**Pull request by LynxDev2**
This PR changes some headers and adds some new ones. All the new headers are modified versions of galaxy mod headers with extra info and parameter names.

I also moved `al::Sequenece::isDisposable` into a cpp file since it shouldn't be in a header.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: all files reviewed, 17 unresolved discussions (waiting on @LynxDev2)

___
*[`lib/al/Library/Area/AreaObj.h` line 20 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gamf38sBrC0FiwgAS:-O9Gamf38sBrC0FiwgAT:b34pyqm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Area/AreaObj.h#L20)):*
> ```objc
>     AreaObj(const char* name);
> 
>     virtual const char* getName() const override;
> ```

Remove `virtual` on functions marked with `override`
___
*[`lib/al/Library/Area/AreaObj.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GaVDo-tZG5Gijs5E0:-O9GaVDo-tZG5Gijs5E1:bajvpxt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Area/AreaObj.h#L27)):*
> ```objc
>     virtual bool isInVolumeOffset(const sead::Vector3f& pos, f32 offset) const;
>     virtual SceneObjHolder* getSceneObjHolder() const override;
> ```

missing `private:`. Why does the linter not pick that up?
___
*[`lib/al/Library/File/FileLoader.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GblswBuN2OJQp1S2o:-O9GblswBuN2OJQp1S2p:b45h) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L27)):*
> ```objc
>                             const char* compareToInCallback);
>     void listFiles(sead::FixedSafeString<256>* out, s32 unk, const char* compareToInCallback,
>                    const char* unused);
> ```





_Suggestion:_
```objc
    s32 listSubdirectories(sead::FixedSafeString<256>* out, s32 unk,
                            const char* compareToInCallback);
    s32 listFiles(sead::FixedSafeString<256>* out, s32 unk, const char* compareToInCallback,
                   const char* unused);
```
___
*[`lib/al/Library/File/FileLoader.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gbso8DBH-woUmKLPD:-O9Gbso8DBH-woUmKLPE:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L28)):*
> ```objc
>     void listFiles(sead::FixedSafeString<256>* out, s32 unk, const char* compareToInCallback,
>                    const char* unused);
>     void isExistFile(const sead::SafeString& path, sead::FileDevice* device) const;
> ```





_Suggestion:_
```objc
bool isExistFile(const sead::SafeString& path, sead::FileDevice* device) const;
```
___
*[`lib/al/Library/File/FileLoader.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GbzEK1UoBKXxI--tm:-O9GbzEK1UoBKXxI--tn:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L32)):*
> ```objc
>                                     sead::FileDevice* maybeNullDevice) const;
>     void isExistArchive(const sead::SafeString& path, sead::FileDevice* device) const;
>     void isExistDirectory(const sead::SafeString& path, sead::FileDevice* device) const;
> ```





_Suggestion:_
```objc
    bool isExistArchive(const sead::SafeString& path, sead::FileDevice* device) const;
    bool isExistDirectory(const sead::SafeString& path, sead::FileDevice* device) const;
```
___
*[`lib/al/Library/File/FileLoader.h` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GcZk-9csGCH--s9Vs:-O9GcZk-9csGCH--s9Vt:b-93x346) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L34)):*
> ```objc
>     void isExistDirectory(const sead::SafeString& path, sead::FileDevice* device) const;
>     u32 getFileSize(const sead::SafeString& path, sead::FileDevice* device) const;
>     void loadfile(const sead::SafeString&, s32, sead::FileDevice*);
> ```

name parameters



_Suggestion:_
```objc
u8* loadFile(const sead::SafeString&, s32, sead::FileDevice*);
```
___
*[`lib/al/Library/File/FileLoader.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GcC1f8bb_80cjrcRf:-O9GcC1f8bb_80cjrcRg:b-93x346) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L35)):*
> ```objc
>     u32 getFileSize(const sead::SafeString& path, sead::FileDevice* device) const;
>     void loadfile(const sead::SafeString&, s32, sead::FileDevice*);
>     void tryLoadFileToBuffer(const sead::SafeString&, u8*, u32, s32, sead::FileDevice*);
> ```

name parameters



_Suggestion:_
```objc
bool tryLoadFileToBuffer(const sead::SafeString&, u8*, u32, s32, sead::FileDevice*);
```
___
*[`lib/al/Library/File/FileLoader.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GdpvkC8fv3E7F1TVX:-O9GdpvkC8fv3E7F1TVY:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L40)):*
> ```objc
>                           sead::FileDevice* device);
>     void loadArchiveWithExt(const sead::SafeString& path, const char* suffix,
>                             sead::FileDevice* device);
> ```





_Suggestion:_
```objc
    sead::Resource* loadArchive(const sead::SafeString& path, sead::FileDevice* device);
    sead::Resource* loadArchiveLocal(const sead::SafeString& path, const char* suffix,
                          sead::FileDevice* device);
    sead::Resource* loadArchiveWithExt(const sead::SafeString& path, const char* suffix,
                            sead::FileDevice* device);
```
___
*[`lib/al/Library/File/FileLoader.h` line 44 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gdzx2AaxZPprPgIRM:-O9Gdzx2AaxZPprPgIRN:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L44)):*
> ```objc
>                                sead::FileDevice* device);
>     void requestLoadArchive(const sead::SafeString& path, sead::Heap* heap,
>                             sead::FileDevice* device);
> ```





_Suggestion:_
```objc
    FileEntryBase* requestLoadArchive(const sead::SafeString& path, sead::Heap* heap,
                            sead::FileDevice* device);
```
___
*[`lib/al/Library/File/FileLoader.h` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Ge92r9MgOejahSe7a:-O9Ge92r9MgOejahSe7b:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L45)):*
> ```objc
>     void requestLoadArchive(const sead::SafeString& path, sead::Heap* heap,
>                             sead::FileDevice* device);
>     void loadSoundItem(u32 soundEntryId, u32 unused, IAudioResourceLoader* loader);
> ```





_Suggestion:_
```objc
bool loadSoundItem(u32 soundEntryId, u32 unused, IAudioResourceLoader* loader);
```
___
*[`lib/al/Library/File/FileLoader.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Ge62EDegqOCJT4EAi:-O9Ge62EDegqOCJT4EAj:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L46)):*
> ```objc
>                             sead::FileDevice* device);
>     void loadSoundItem(u32 soundEntryId, u32 unused, IAudioResourceLoader* loader);
>     void requestLoadSoundItem(u32 unused, u32 unused2, IAudioResourceLoader* unused3);
> ```





_Suggestion:_
```objc
FileEntryBase* requestLoadSoundItem(u32 unused, u32 unused2, IAudioResourceLoader* unused3);
```
___
*[`lib/al/Library/Wipe/WipeHolder.h` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GfBKA6jot37cpW_HS:-O9GfBKA6jot37cpW_HT:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Wipe/WipeHolder.h#L17)):*
> ```objc
>     s32 findInfo(const char* infoName) const;
>     bool tryStartClose(const char* name, s32 unk);
>     bool tryStartCloseByInfo(const char* infoName);
> ```





_Suggestion:_
```objc
    void tryStartClose(const char* name, s32 unk);
    void tryStartCloseByInfo(const char* infoName);
```
___
*[`src/Sequence/ChangeStageInfo.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gfyw73uhZvBUVZskG:-O9Gfyw73uhZvBUVZskH:b-jyno28) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/ChangeStageInfo.h#L7)):*
> ```objc
> #include "Library/Placement/PlacementInfo.h"
> 
> #include "System/GameDataHolder.h"
> ```

Useless includes



_Code quote:_
```objc
#include "Library/Placement/PlacementInfo.h"

#include "System/GameDataHolder.h"
```
___
*[`src/Sequence/ChangeStageInfo.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gg4YQBJvCPD1D3VBI:-O9Gg4YQBJvCPD1D3VBJ:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/ChangeStageInfo.h#L29)):*
> ```objc
>                     s32 scenario, SubScenarioType subScenarioType);
>     void copy(const ChangeStageInfo& other);
>     void findScenarioNoByList(const GameDataHolder*);  // Doesn't return anything
> ```





_Suggestion:_
```objc
void findScenarioNoByList(const GameDataHolder*);
```
___
*[`src/Sequence/HakoniwaSequence.h` line 47 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gh1Hf2HJ750hJRShF:-O9Gh1Hf2HJ750hJRShG:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L47)):*
> ```objc
>     void destroySceneHeap(bool destroyResource);
>     void initSystem();
>     void isEnableSave() const;
> ```





_Suggestion:_
```objc
bool isEnableSave() const;
```
___
*[`src/Sequence/HakoniwaSequence.h` line 75 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GhKfi3T29cVUItJdA:-O9GhKfi3T29cVUItJdB:b-d189cq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L75)):*
> ```objc
>     al::Scene* mCurrentScene;
>     GameDataHolderAccessor mGameDataHolderAccessor;
>     al::GamePadSystem* mGamePadSystem;
> ```

`ControllerAppletFunction*`, see `updatePadSystem()`
___
*[`src/Sequence/HakoniwaSequence.h` line 85 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GhWej1-7g5GLNh1Wl:-O9GhWej1-7g5GLNh1Wm:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L85)):*
> ```objc
>     bool _100;
>     sead::FixedSafeString<128> mStageName;
>     s32 mScenarioNum;
> ```





_Suggestion:_
```objc
s32 mNextScenarioNum;
```

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: all files reviewed, 17 unresolved discussions (waiting on @LynxDev2)

___
*[`lib/al/Library/Area/AreaObj.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GaVDo-tZG5Gijs5E0:-O9H06gxBE6ZCJKNVyJK:b4svybz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Area/AreaObj.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

missing `private:`. Why does the linter not pick that up?
</blockquote></details>

The linter doesn't check this so far. Huh. Still wrong on this though.

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: 9 of 14 files reviewed, 17 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Area/AreaObj.h` line 20 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gamf38sBrC0FiwgAS:-O9OCKTICr5vJQcng_pj:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Area/AreaObj.h#L20)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Remove `virtual` on functions marked with `override`
</blockquote></details>

Done.
___
*[`lib/al/Library/Area/AreaObj.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GaVDo-tZG5Gijs5E0:-O9OCLNG2VjR5SFJh_Mk:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Area/AreaObj.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

The linter doesn't check this so far. Huh. Still wrong on this though.
</blockquote></details>

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GblswBuN2OJQp1S2o:-O9OCNFbBeXBcn_PBhLv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L27)):*
> ```objc
>                             const char* compareToInCallback);
>     void listFiles(sead::FixedSafeString<256>* out, s32 unk, const char* compareToInCallback,
>                    const char* unused);
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gbso8DBH-woUmKLPD:-O9OCO2D-ly75HLIbhWg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L28)):*
> ```objc
>     void listFiles(sead::FixedSafeString<256>* out, s32 unk, const char* compareToInCallback,
>                    const char* unused);
>     void isExistFile(const sead::SafeString& path, sead::FileDevice* device) const;
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GbzEK1UoBKXxI--tm:-O9OCOgz5D00Nk_5bQwd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L32)):*
> ```objc
>                                     sead::FileDevice* maybeNullDevice) const;
>     void isExistArchive(const sead::SafeString& path, sead::FileDevice* device) const;
>     void isExistDirectory(const sead::SafeString& path, sead::FileDevice* device) const;
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GcZk-9csGCH--s9Vs:-O9OCPCB-GW64dzfT6qr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L34)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

name parameters
</blockquote></details>

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GcC1f8bb_80cjrcRf:-O9OCPhl1-KQuB7xQuNf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

name parameters
</blockquote></details>

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GdpvkC8fv3E7F1TVX:-O9OCQEj5CaloqHUchp-:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L40)):*
> ```objc
>                           sead::FileDevice* device);
>     void loadArchiveWithExt(const sead::SafeString& path, const char* suffix,
>                             sead::FileDevice* device);
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 44 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gdzx2AaxZPprPgIRM:-O9OCQfi5dkTtRLNzCeQ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L44)):*
> ```objc
>                                sead::FileDevice* device);
>     void requestLoadArchive(const sead::SafeString& path, sead::Heap* heap,
>                             sead::FileDevice* device);
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Ge92r9MgOejahSe7a:-O9OCR388PZ-vfv6CW3z:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L45)):*
> ```objc
>     void requestLoadArchive(const sead::SafeString& path, sead::Heap* heap,
>                             sead::FileDevice* device);
>     void loadSoundItem(u32 soundEntryId, u32 unused, IAudioResourceLoader* loader);
> ```

Done.
___
*[`lib/al/Library/File/FileLoader.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Ge62EDegqOCJT4EAi:-O9OCRpt69ZbjPWhK7Ua:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L46)):*
> ```objc
>                             sead::FileDevice* device);
>     void loadSoundItem(u32 soundEntryId, u32 unused, IAudioResourceLoader* loader);
>     void requestLoadSoundItem(u32 unused, u32 unused2, IAudioResourceLoader* unused3);
> ```

Done.
___
*[`lib/al/Library/Wipe/WipeHolder.h` line 17 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GfBKA6jot37cpW_HS:-O9OCShABNjgW23J7HtB:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/Wipe/WipeHolder.h#L17)):*
> ```objc
>     s32 findInfo(const char* infoName) const;
>     bool tryStartClose(const char* name, s32 unk);
>     bool tryStartCloseByInfo(const char* infoName);
> ```

Done.
___
*[`src/Sequence/ChangeStageInfo.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gfyw73uhZvBUVZskG:-O9OD08sBEBsoShuglaD:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/ChangeStageInfo.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless includes
</blockquote></details>

Done.
___
*[`src/Sequence/ChangeStageInfo.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gg4YQBJvCPD1D3VBI:-O9OD4QL1xk_UtmobwzU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/ChangeStageInfo.h#L29)):*
> ```objc
>                     s32 scenario, SubScenarioType subScenarioType);
>     void copy(const ChangeStageInfo& other);
>     void findScenarioNoByList(const GameDataHolder*);  // Doesn't return anything
> ```

Done.
___
*[`src/Sequence/HakoniwaSequence.h` line 47 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9Gh1Hf2HJ750hJRShF:-O9ODCUfAF9XpW8upACd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L47)):*
> ```objc
>     void destroySceneHeap(bool destroyResource);
>     void initSystem();
>     void isEnableSave() const;
> ```

Done.
___
*[`src/Sequence/HakoniwaSequence.h` line 75 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GhKfi3T29cVUItJdA:-O9OEAts2k9D441pQtDP:b-v9fxq4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L75)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`ControllerAppletFunction*`, see `updatePadSystem()`
</blockquote></details>

No, I think the current type is correct. `updatePadSystem` calls `ControllerAppletFunction::connectControllerSinglePlay` which calls `al::tryCallControllerApplet` that takes a `const al::GamePadSystem*` and passes the first arg as that `GamePadSystem*`. It also wouldn't make sense to have a pointer to a function class
___
*[`src/Sequence/HakoniwaSequence.h` line 85 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GhWej1-7g5GLNh1Wl:-O9OFWYIDjHO7xY3mEYA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/src/Sequence/HakoniwaSequence.h#L85)):*
> ```objc
>     bool _100;
>     sead::FixedSafeString<128> mStageName;
>     s32 mScenarioNum;
> ```

Done.

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/File/FileLoader.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174#-O9GdpvkC8fv3E7F1TVX:-O9R2eNI8sRWJ-ZC532V:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/568ef30a3f0a52dd3f23c53c91ba520ae2e42431/lib/al/Library/File/FileLoader.h#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Last one is missing a `*` (`sead::Resource*`)
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/174)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

**Pull request merged**
