### PR TITLE
Player: PlayerJudgeTalkGround (retry)

### PR DESCRIPTION
**Pull request by LynxDev2**
Had to do a duplicate PR since I'm bad at git: Implemented all functions for **PlayerJudgeTalkGround.** Any suggestions on what header should I put the rs declarations in?

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)

### CODE REVIEW

**Comment by MonsterDruide1** [comment]
Supersedes #82

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 8 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @LynxDev2)

___
*[`src/Player/PlayerHackKeeper.h` line 4 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTHAm2Um3nsGlurHT:-NzwTHAm2Um3nsGlurHU:bmdct9i) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerHackKeeper.h#L4)):*
> ```objc
> 
> #include "Library/LiveActor/LiveActor.h"
> #include "Project/HitSensor/HitSensor.h"
> ```

Do not include, but forward-declare instead
___
*[`src/Player/PlayerHackKeeper.h` line 21 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwT8R90xboOznnERmg:-NzwT8R90xboOznnERmh:bq88dvl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerHackKeeper.h#L21)):*
> ```objc
> 
>     inline al::LiveActor* getCurrentHackActor() const { return mCurrentHackActor; }
>     inline al::HitSensor* getUnkHitSensor() const { return mUnkHitSensor; }
> ```

Do not mark them as `inline` here, they will automatically be inlined (as they're written in a header)



_Code quote:_
```objc
    inline al::LiveActor* getCurrentHackActor() const { return mCurrentHackActor; }
    inline al::HitSensor* getUnkHitSensor() const { return mUnkHitSensor; }
```
___
*[`src/Player/PlayerJudgeTalkGround.h` line 17 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTS7wDWRO4DVfEfNR:-NzwTS7wDWRO4DVfEfNS:b2kj4y7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.h#L17)):*
> ```objc
> class PlayerStateWait;
> 
> class PlayerJudgeTalkGround : public IJudge {
> ```

The type info shows that it has two superclasses:



_Suggestion:_
```objc
class PlayerJudgeTalkGround : public IJudge, public al::HioNode {
```
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 3 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTbRiEXx9CZfPpdrM:-NzwTbRiEXx9CZfPpdrN:b9v2x0m) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L3)):*
> ```cpp
> #include "Player/PlayerJudgeTalkGround.h"
> 
> #include <math/seadVectorFwd.h>
> ```

Do not use that header, but `math/seadVector.h` instead
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 16 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTina4m5HQ90Og4bN:-NzwTina4m5HQ90Og4bO:bevvogz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L16)):*
> ```cpp
> #include "Player/PlayerStateWait.h"
> 
> // TODO: Put these in the correct headers
> ```

... yeah, please do
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwU1oE5pWzBwfkjzA4:-NzwU1oE5pWzBwfkjzA5:b29c2ek) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L38)):*
> ```cpp
> void PlayerJudgeTalkGround::update() {}
> 
> bool PlayerJudgeTalkGround::judge() const {
> ```

Try re-ordering this entire function to be a bunch of early-return-false's, followed by the "proper path(s)".

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)* status: 7 of 8 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerHackKeeper.h` line 4 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTHAm2Um3nsGlurHT:-NzxFHkt3ik8AQ8sXwk3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerHackKeeper.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Do not include, but forward-declare instead
</blockquote></details>

Done.
___
*[`src/Player/PlayerHackKeeper.h` line 21 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwT8R90xboOznnERmg:-NzxFaqTAeRBEUi3NJTO:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerHackKeeper.h#L21)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Do not mark them as `inline` here, they will automatically be inlined (as they're written in a header)
</blockquote></details>

Done.
___
*[`src/Player/PlayerJudgeTalkGround.h` line 17 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTS7wDWRO4DVfEfNR:-NzxH0oCARwb_xcVc2mO:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.h#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

The type info shows that it has two superclasses:
</blockquote></details>

Done.
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 3 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTbRiEXx9CZfPpdrM:-NzxD-vAAsYn9yXJ1vlY:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Do not use that header, but `math/seadVector.h` instead
</blockquote></details>

Done.
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 16 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwTina4m5HQ90Og4bN:-NzxD1-q4FJhy6b4LKUD:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L16)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

... yeah, please do
</blockquote></details>

Done.
___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwU1oE5pWzBwfkjzA4:-NzxHcrXBN8GArqto2wI:beph9b2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Try re-ordering this entire function to be a bunch of early-return-false's, followed by the "proper path(s)".
</blockquote></details>

Should I reverse the order of the blocks by putting a `!` at the start of the first condition?

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @LynxDev2)

___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwU1oE5pWzBwfkjzA4:-Nzxfo6v6gIVtNKWpM5W:b-iie2h8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L38)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

Should I reverse the order of the blocks by putting a `!` at the start of the first condition?
</blockquote></details>

https://decomp.me/scratch/5Ciz5

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerJudgeTalkGround.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83#-NzwU1oE5pWzBwfkjzA4:-NzxIf-N1iC_-28QmTcL:bb6un1j) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/9d26563656c7dbc5db48c5681ac20c3cb32a0b44/src/Player/PlayerJudgeTalkGround.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

https://decomp.me/scratch/5Ciz5
</blockquote></details>

Done

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/83)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

**Pull request merged**
