### PR TITLE
Add hash code functions

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds hash code functions. I also changed the name of the `getBaseName` variables to better ones.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-NwooXmn2aGHSdnx9QR0:b-vim2hi) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):*
> ```objc
> #include <cstdarg>
> #include <cstdio>
> #include <cstring>
> ```

Are all of these required?



_Code quote:_
```objc
#include <cctype>
#include <cstdarg>
#include <cstdio>
#include <cstring>
```
___
*[`lib/al/src/Library/Base/Base.cpp` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-Nwon_DT3DnqTT5_drXy:-Nwon_DT3DnqTT5_drXz:b-reua0l) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/src/Library/Base/Base.cpp#L7)):*
> ```cpp
>     if (hash[0] == '\0') {
>         return 0;
>     }
> ```

I think this should already be covered by the `for` loop, so no additional check needed here?



_Code quote:_
```cpp
    if (hash[0] == '\0') {
        return 0;
    }
```
___
*[`lib/al/src/Library/Base/Base.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooQ_k2eIi1i3aXJIE:-NwooQ_k2eIi1i3aXJIF:b-1obmrp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/src/Library/Base/Base.cpp#L37)):*
> ```cpp
> 
>     // I'm not sure if this is the right macro to use here
>     // I've never used this before
> ```

Yes, seems about right, compare with this:
https://github.com/open-ead/sead/blob/b936df1db43fcf34efb739356b464aaf72ec611c/modules/src/prim/seadStringBuilder.cpp#L315-L323

Should be fine, please remove this comment then.



_Code quote:_
```cpp
    // I'm not sure if this is the right macro to use here
    // I've never used this before
```

**Comment by Fuzzy2319** [comment]
> _[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-NwooXmn2aGHSdnx9QR0:b-vim2hi) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):_
> 
> > ```objc
> > #include <cstdarg>
> > #include <cstdio>
> > #include <cstring>
> > ```
> 
> Are all of these required?
> 
> _Code quote:_
> 
> ```objc
> #include <cctype>
> #include <cstdarg>
> #include <cstdio>
> #include <cstring>
> ```

yes `<cctype>` is for `tolower`, `<cstdargs>` is for `std::va_list`, `<cstdio>` is for `vsprintf` and `<cstring>` is for `strrchr`
 
> _[`lib/al/src/Library/Base/Base.cpp` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-Nwon_DT3DnqTT5_drXy:-Nwon_DT3DnqTT5_drXz:b-reua0l) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/src/Library/Base/Base.cpp#L7)):_
> 
> > ```c++
> >     if (hash[0] == '\0') {
> >         return 0;
> >     }
> > ```
> 
> I think this should already be covered by the `for` loop, so no additional check needed here?
> 
> _Code quote:_
> 
> ```c++
>     if (hash[0] == '\0') {
>         return 0;
>     }
> ```
> 
> _[`lib/al/src/Library/Base/Base.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooQ_k2eIi1i3aXJIE:-NwooQ_k2eIi1i3aXJIF:b-1obmrp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/src/Library/Base/Base.cpp#L37)):_

the function does not match without
image

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-NwotoyO6OY2KjBwPqp3:b-wq2t97) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

yes `<cctype>` is for `tolower`, `<cstdargs>` is for `std::va_list`, `<cstdio>` is for `vsprintf` and `<cstring>` is for `strrchr`
 

</blockquote></details>

Alright, thanks for the explanation!
___
*[`lib/al/src/Library/Base/Base.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooQ_k2eIi1i3aXJIE:-NwotzXm4xE9AeFb1mYp:b-jv6eqp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/src/Library/Base/Base.cpp#L37)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

the function does not match without
image

</blockquote></details>

Huh, that's a meme-like diff... the compiler decides to insert a jump to a single return statement instead of returning immediately. That's weird, and kind of funny. Either way, I guess it's fine then.

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-NwovWxb6K5r3LNwQNGy:b7c27vs) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Alright, thanks for the explanation!
</blockquote></details>

shouldn't they go in the source file rather than the header?

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319 and @tetraxile)

___
*[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-Nwovjc01OeKMphPUjZz:barsyb6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

shouldn't they go in the source file rather than the header?
</blockquote></details>

Oh. Huh, yeah, good catch - at least `cctype`, `cstdio` and `cstring` should go there, `cstdargs` is probably required here as well.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Base/Base.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooXmn2aGHSdnx9QR-:-NxOIKMNBUzy3xFw_UMH:bgo7bt9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/7325f50e48614ed9b5bf735324a9831aabb1b9c8/lib/al/include/Library/Base/Base.h#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Oh. Huh, yeah, good catch - at least `cctype`, `cstdio` and `cstring` should go there, `cstdargs` is probably required here as well.
</blockquote></details>

Ah, you changed it without commenting - sorry, this has gone unnoticed on my end.

**Pull request merged**
