### PR TITLE
`game/player`: Implement `PlayerEquipmentUser`

### PR DESCRIPTION
**Pull request by OatmealDome**
The ordering of the ``equipmentSensor`` and the ``sourceSensor`` got a bit confusing - I hope I got it right.

---
This change is [Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)* status: all files reviewed, 9 unresolved discussions (waiting on @OatmealDome)

___
*[lib/al/sensor/SensorMsg.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-L1S8Tzw0L9Pewyo:-Ms_-L1TCpcZjGJObjEH:bo304qw) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/50bf777e5776e75a39d73623b0052789b0bdb31a/lib/al/sensor/SensorMsg.h#L8)):*
> ```objc
> class SensorMsg;
> 
> void sendMsgPlayerReleaseEquipment(al::HitSensor*, al::HitSensor*);
> ```

No qualifying with `al` necessary here, just `HitSensor*` is enough.
___
*[lib/al/sensor/SensorMsg.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-ZIy7EZT7hgd1aWt:-Ms_-ZIy7EZT7hgd1aWu:b-qirw8z) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/50bf777e5776e75a39d73623b0052789b0bdb31a/lib/al/sensor/SensorMsg.h#L8)):*
> ```objc
> class SensorMsg;
> 
> void sendMsgPlayerReleaseEquipment(al::HitSensor*, al::HitSensor*);
> ```

Please name the parameters if possible.
___
*[lib/game/player/PlayerEquipmentUser.h, line 14 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-xFhBs0SD1euH5sh:-Ms_-xFhBs0SD1euH5si:b-560u4s) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L14)):*
> ```objc
> class PlayerEquipmentUser {
> public:
>     PlayerEquipmentUser(PlayerInput const* input, PlayerModelHolder const* modelHolder,
> ```

`const` should go to the front of the type. Example: `const PlayerInput* input` instead of `PlayerInput const*`. Same for everything below.
___
*[lib/game/player/PlayerEquipmentUser.h, line 14 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_02LlD2o54i7l5RnI:-Ms_02LlD2o54i7l5RnJ:bnq9mal) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L14)):*
> ```objc
> class PlayerEquipmentUser {
> public:
>     PlayerEquipmentUser(PlayerInput const* input, PlayerModelHolder const* modelHolder,
> ```

Parameter names follow snake case, so `model_holder` would be better here. Same below for `model_changer`.
___
*[lib/game/player/PlayerEquipmentUser.h, line 22 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0iQi7JKwiiz3D3s_:-Ms_0iQj9g7mG-RabJNr:b-cs95hq) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L22)):*
> ```objc
>     void noticeDamage();
> 
>     al::HitSensor* mSourceSensor = nullptr;
> ```

These should all be `private:`.
___
*[lib/game/player/PlayerEquipmentUser.h, line 28 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0P-S0iCD4plcWXZf:-Ms_0P-S0iCD4plcWXZg:b-uvdq2d) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L28)):*
> ```objc
>     PlayerModelHolder const* mPlayerModelHolder;
>     IPlayerModelChanger const* mPlayerModelChanger;
>     void* mUnk = nullptr;
> ```

Are you sure this exists? There is no reference to it in the `cpp`...
___
*[lib/game/player/PlayerEquipmentUser.h, line 29 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0Y3w6eK263dWnrBK:-Ms_0Y3w6eK263dWnrBL:b-l40zuv) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L29)):*
> ```objc
>     IPlayerModelChanger const* mPlayerModelChanger;
>     void* mUnk = nullptr;
> };
> ```

If you know the size of this struct (`operator new(0x...)`), assert it here using `static_assert(sizeof(PlayerEquipmentUser) == 0x...);`.
___
*[src/game/player/PlayerEquipmentUser.cpp, line 4 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0qu-254GSmoMxnT8:-Ms_0qu-254GSmoMxnT9:b-m9c420) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/src/game/player/PlayerEquipmentUser.cpp#L4)):*
> ```cpp
> 
> #include "al/sensor/SensorMsg.h"
> ```

No need for this empty line. It makes sense to separate the header of this `cpp`, but everything else can be grouped together.
___
*[src/game/player/PlayerEquipmentUser.cpp, line 7 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_12n56mELgBiNVakQ:-Ms_12n56mELgBiNVakR:bhprf2u) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/src/game/player/PlayerEquipmentUser.cpp#L7)):*
> ```cpp
> #include "rs/Sensor.h"
> 
> PlayerEquipmentUser::PlayerEquipmentUser(PlayerInput const* input,
> ```

Same remarks about `const` and snake case as in the header.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)* status: 1 of 6 files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/al/sensor/SensorMsg.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-L1S8Tzw0L9Pewyo:-MsrI7Sb799-8otJBkH2:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/50bf777e5776e75a39d73623b0052789b0bdb31a/lib/al/sensor/SensorMsg.h#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No qualifying with `al` necessary here, just `HitSensor*` is enough.
</blockquote></details>

Done.
___
*[lib/al/sensor/SensorMsg.h, line 8 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-ZIy7EZT7hgd1aWt:-MsrI9I06iUdfGOSFMFs:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/50bf777e5776e75a39d73623b0052789b0bdb31a/lib/al/sensor/SensorMsg.h#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please name the parameters if possible.
</blockquote></details>

Done.
___
*[lib/game/player/PlayerEquipmentUser.h, line 14 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_-xFhBs0SD1euH5sh:-MsrIA2i8ZXgGjxuoYEY:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`const` should go to the front of the type. Example: `const PlayerInput* input` instead of `PlayerInput const*`. Same for everything below.
</blockquote></details>

Done.
___
*[lib/game/player/PlayerEquipmentUser.h, line 14 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_02LlD2o54i7l5RnI:-MsrIADuBOE1s1KWKiQe:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Parameter names follow snake case, so `model_holder` would be better here. Same below for `model_changer`.
</blockquote></details>

Done.
___
*[lib/game/player/PlayerEquipmentUser.h, line 22 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0iQi7JKwiiz3D3s_:-MsrIBZd3jTxpwaP_6QI:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L22)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

These should all be `private:`.
</blockquote></details>

Done.
___
*[lib/game/player/PlayerEquipmentUser.h, line 28 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0P-S0iCD4plcWXZf:-MsrIFEr0NJQuGjaaRpf:b-e0e7gl) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Are you sure this exists? There is no reference to it in the `cpp`...
</blockquote></details>

The constructor appears to set a 7th pointer at the end of the class to nullptr, but I haven't been able to figure out what it is, since none of the class functions access or set it. Not sure if it really does exist or if it's just some sort of padding.
___
*[lib/game/player/PlayerEquipmentUser.h, line 29 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0Y3w6eK263dWnrBK:-MsrIuRP8p476HBafE1k:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If you know the size of this struct (`operator new(0x...)`), assert it here using `static_assert(sizeof(PlayerEquipmentUser) == 0x...);`.
</blockquote></details>

Done.
___
*[src/game/player/PlayerEquipmentUser.cpp, line 4 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0qu-254GSmoMxnT8:-MsrIEacB0E1YXfITVT5:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/src/game/player/PlayerEquipmentUser.cpp#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No need for this empty line. It makes sense to separate the header of this `cpp`, but everything else can be grouped together.
</blockquote></details>

Done.
___
*[src/game/player/PlayerEquipmentUser.cpp, line 7 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_12n56mELgBiNVakQ:-MsrIvVMAt3JzHpM7uG9:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/src/game/player/PlayerEquipmentUser.cpp#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same remarks about `const` and snake case as in the header.
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)* status: all files reviewed, 1 unresolved discussion (waiting on @OatmealDome)

___
*[lib/game/player/PlayerEquipmentUser.h, line 28 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0P-S0iCD4plcWXZf:-MsvfCeoE9GKHWA_IdGi:b-wnxpst) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L28)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

The constructor appears to set a 7th pointer at the end of the class to nullptr, but I haven't been able to figure out what it is, since none of the class functions access or set it. Not sure if it really does exist or if it's just some sort of padding.
</blockquote></details>

In `PlayerActorHakoniwa::initPlayer`, I can find this line:
```
this->mPlayerEquipmentUser->mUnk = this->mPlayerStateRolling;
```

This indicates the field in question to be of type `PlayerStateRolling*`, with an inlined setter in the header to avoid setting the field to `public`.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[lib/game/player/PlayerEquipmentUser.h, line 28 at r3](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-Ms_0P-S0iCD4plcWXZf:-MsxtDOWA8o89E-L4WUi:bka1je8) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/6d747eec68ddec127f279f44ca5d9bedfd7ef465/lib/game/player/PlayerEquipmentUser.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

In `PlayerActorHakoniwa::initPlayer`, I can find this line:
```
this->mPlayerEquipmentUser->mUnk = this->mPlayerStateRolling;
```

This indicates the field in question to be of type `PlayerStateRolling*`, with an inlined setter in the header to avoid setting the field to `public`.
</blockquote></details>

Thanks for tracking it down! Fixed.

**Review by MonsterDruide1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/6#-:-Mt52vDLEYj-5ir_R6cz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OatmealDome)

**Pull request merged**
