### PR TITLE
Amiibo: Implement HelpAmiiboExecutor & ItemAmiiboKoopa

### PR DESCRIPTION
**Pull request by GRAnimated**
Small classes that initiate work on `src/Amiibo`.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @GRAnimated)

___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGCw4m5o-wJ-hxXfQV:-NzGCw4m5o-wJ-hxXfQW:b-khpb54) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L4)):*
> ```objc
> 
> #include "Library/HostIO/HioNode.h"
> #include "Library/LiveActor/ActorInitInfo.h"
> ```

Declare instead of include
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGD45x1Rd75kGOzWNW:-NzGD45x1Rd75kGOzWNX:b-rbegpw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L15)):*
> ```objc
> public:
>     HelpAmiiboExecutor(HelpAmiiboDirector*, al::LiveActor*, const char*);
>     virtual void initAfterPlacement(const al::ActorInitInfo&);
> ```

Please group them together in groups of `ctor/dtor - empty line - virtual functions - empty line - other functions`, to make sure that virtual functions are obvious and listed at the top
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDSfFEzMAvlBgLdwe:-NzGDSfGD2fSVNjGJS8I:b-rsyu67) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L27)):*
> ```objc
> private:
>     HelpAmiiboDirector* mHelpAmiiboDirector = nullptr;
>     char mIsActivated = false;
> ```

Should probably be `bool`?
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDW1o9DWt7bfqE_Rr:-NzGDW1o9DWt7bfqE_Rs:b13jrb8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L28)):*
> ```objc
>     HelpAmiiboDirector* mHelpAmiiboDirector = nullptr;
>     char mIsActivated = false;
>     char mIsTouched = false;
> ```

`bool`?
___
*[`src/Amiibo/HelpAmiiboExecutor.cpp` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDmkj1MUFwyLGTsnP:-NzGDmkj1MUFwyLGTsnQ:bxlabea) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.cpp#L4)):*
> ```cpp
> 
> HelpAmiiboExecutor::HelpAmiiboExecutor(HelpAmiiboDirector* director, al::LiveActor* amiiboActor,
>                                        const char* amiiboName)
> ```

Heh, unused argument in a function that could've just not used the argument. That's rare.
___
*[`src/Amiibo/HelpAmiiboExecutor.cpp` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDyLt7Cha1tqJCF_J:-NzGDyLt7Cha1tqJCF_K:b45h) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.cpp#L10)):*
> ```cpp
> 
> bool HelpAmiiboExecutor::tryTouch(const al::NfpInfo& nfpInfo) {
>     if (mIsActivated || isTriggerTouch(nfpInfo) == false)
> ```





_Suggestion:_
```cpp
    if (mIsActivated || !isTriggerTouch(nfpInfo))
```
___
*[`src/Amiibo/HelpAmiiboExecutor.cpp` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGEPVo83SxA7gNea0G:-NzGEPVo83SxA7gNea0H:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.cpp#L24)):*
> ```cpp
>     mIsTouched = false;
>     if (execute())
>         return deactivate();
> ```





_Suggestion:_
```cpp
        deactivate();
```
___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 41 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGFhpu0sLjYWPRzeY1:-NzGFhpu0sLjYWPRzeY2:b-4kqkmp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L41)):*
> ```cpp
> void ItemAmiiboKoopa::exeExpand() {
>     al::setSensorRadius(this, al::getNerveStep(this) / 30.0f * 1000.0f);
>     al::setTrans(this, *rs::getPlayerPos(this));
> ```

(same as below)
___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 48 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGFYjo5NPdeBfOGck9:-NzGFYjo5NPdeBfOGckA:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L48)):*
> ```cpp
> void ItemAmiiboKoopa::exeWait() {
>     if (al::isGreaterEqualStep(this, 300))
>         return kill();
> ```





_Suggestion:_
```cpp
    if (al::isGreaterEqualStep(this, 300)) {
        kill();
        return;
    }
```
___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGF66dCimbGLI2mKZO:-NzGF66dCimbGLI2mKZP:bw2spp5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L50)):*
> ```cpp
>         return kill();
> 
>     al::setTrans(this, *rs::getPlayerPos(this));
> ```

Re-reading the `rs::getPlayerPos()` function, I think it should have the return type `const sead::Vector3f&` instead. Can you adjust it accordingly (and remove the `*` here)?

**Review by GRAnimated — COMMENTED** [review]
Cleaned up

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-:-NzGHXjj6-2HLoeYq05y:b-4iduyw)* status: 4 of 6 files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGCw4m5o-wJ-hxXfQV:-NzGGQ9c8RbHcSMtS4us:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Declare instead of include
</blockquote></details>

Done.
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 15 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGD45x1Rd75kGOzWNW:-NzGGjLUEYUKQBmvoBgw:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L15)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Please group them together in groups of `ctor/dtor - empty line - virtual functions - empty line - other functions`, to make sure that virtual functions are obvious and listed at the top
</blockquote></details>

Done.
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDSfFEzMAvlBgLdwe:-NzGGlZG5yHwrXD6HcRf:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should probably be `bool`?
</blockquote></details>

Done.
___
*[`src/Amiibo/HelpAmiiboExecutor.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDW1o9DWt7bfqE_Rr:-NzGGll8Bc7nAkx-ov2v:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`bool`?
</blockquote></details>

Done.
___
*[`src/Amiibo/HelpAmiiboExecutor.cpp` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGDyLt7Cha1tqJCF_J:-NzGGtTeDoArH_KB67XP:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.cpp#L10)):*
> ```cpp
> 
> bool HelpAmiiboExecutor::tryTouch(const al::NfpInfo& nfpInfo) {
>     if (mIsActivated || isTriggerTouch(nfpInfo) == false)
> ```

Done.
___
*[`src/Amiibo/HelpAmiiboExecutor.cpp` line 24 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGEPVo83SxA7gNea0G:-NzGGvU-AWjYrMf4fVBm:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/HelpAmiiboExecutor.cpp#L24)):*
> ```cpp
>     mIsTouched = false;
>     if (execute())
>         return deactivate();
> ```

Done.
___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 48 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGFYjo5NPdeBfOGck9:-NzGH-vf7A57JzsyDTLE:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L48)):*
> ```cpp
> void ItemAmiiboKoopa::exeWait() {
>     if (al::isGreaterEqualStep(this, 300))
>         return kill();
> ```

Done.
___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 50 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGF66dCimbGLI2mKZO:-NzGHCu88QVd5D-UOaCe:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L50)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Re-reading the `rs::getPlayerPos()` function, I think it should have the return type `const sead::Vector3f&` instead. Can you adjust it accordingly (and remove the `*` here)?
</blockquote></details>

Done.

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)* status: 3 of 8 files reviewed, 9 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Amiibo/ItemAmiiboKoopa.cpp` line 41 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50#-NzGFhpu0sLjYWPRzeY1:-NzGHkRw5OwRBx6_tg73:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a868e63616a6c3bc4b6dd9e1d9ae2606e6baa0a5/src/Amiibo/ItemAmiiboKoopa.cpp#L41)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(same as below)
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/50)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
