### PR TITLE
Scene: Add SceneObjFactory

### PR DESCRIPTION
**Pull request by MonsterDruide1**
This PR mostly adds the `SceneObjID` enum. This list was compiled by @tetraxile, the suggestion to create an enum was done by @fruityloops1.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26)

### CODE REVIEW

**Comment by fruityloops1** [comment]
*[`src/Scene/SceneObjFactory.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26#-NuvjxOhDsCx8MJ8YEq8:-NuvjxOhDsCx8MJ8YEq9:bmeniph) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f51026483a53b120a3a1978e6341a25dc950e7b3/src/Scene/SceneObjFactory.h#L9)):*
> ```objc
> }
> 
> enum class SceneObjID : s32 {
> ```

it shouldn't be an enum class, because this enum is used as an index for the pointer array which you can't do with an enum class, unless you want to force use of wrappers for getSceneObj that convert the enum to the int argument, but you could just use a normal enum which does implicitly get converted to int, prefix all of the enum members with SceneObjID_ to avoid namespace bloating

**Review by fruityloops1 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @fruityloops1)

___
*[`src/Scene/SceneObjFactory.h` line 9 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26#-NuvjxOhDsCx8MJ8YEq8:-NuzUBb083creH2_poJC:b-om0a94) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f51026483a53b120a3a1978e6341a25dc950e7b3/src/Scene/SceneObjFactory.h#L9)):*
<details><summary><i>Previously, fruityloops1 (Fruityloops) wrote…</i></summary><blockquote>

it shouldn't be an enum class, because this enum is used as an index for the pointer array which you can't do with an enum class, unless you want to force use of wrappers for getSceneObj that convert the enum to the int argument, but you could just use a normal enum which does implicitly get converted to int, prefix all of the enum members with SceneObjID_ to avoid namespace bloating
</blockquote></details>

Alright, that's true. I missed that `enum` (without `class`) supports implicit conversion, which would make its usages a lot cleaner - I would've gone with manual casting `(s32)SceneObjID::whatever` each time, but I guess with just `enum` and the prefix it's better.

**Review by fruityloops1 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/26#-:-NvTr_au-ogSXFKikNDk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

**Pull request merged**
