### PR TITLE
Scene: Add decompiled actors to actor factory

### PR DESCRIPTION
**Pull request by GRAnimated**
Adds `createActorFunction`s to decompiled actors inside of `ProjectActorFactory`.
I've also removed `Coin.h` as its currently unused and isn't filled out to the correct size of the class, and added the fields for `AnagramAlphabet.h` to make it match.

I currently have it where actors are included in `ProjectActors.h` to keep `ProjectActorFactory.cpp` clean, but clangd gives a warning that the headers aren't used directly. Maybe the entire table should be moved to a `ProjectActorEntries.h` and the headers can be included there?

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57)

### CODE REVIEW

**Review by MonsterDruide1 — COMMENTED** [review]
I don't really know the different access patterns between static/const/member constants/constexpr "tables"/values, I'm not sure if we can tell a "correct way" or if it's just preference/styling.

Why/What would you want to keep out of `ProjectActorFactory.cpp` that you would prefer creating another header with just includes?

> Reviewed 6 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57#-:-NzNOAcT-gkM-aR4FbBA:b-hgbs53)* status: 6 of 7 files reviewed, all discussions resolved

**Review by GRAnimated — COMMENTED** [review]
Later on, when there's 200+ actors included for the actor factory, it's a little ugly to include them all at the beginning of the file, obscuring everything else. `ProjectActors.h` just keeps those includes out. I could also move the table into that file as well to keep that contained in a single place.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57#-:-NzOYWna5YICDofueHHy:b-ses438)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by MonsterDruide1 — COMMENTED** [review]
This class only consists of the table and a very short constructor though, why would you want to externalize those things to a separate file again, where all of them are listed just like before?

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57#-:-NzPJoD3DHeM2WYZ37xi:byosytc)* status: 6 of 7 files reviewed, all discussions resolved

**Review by GRAnimated — COMMENTED** [review]
That's a fair counter-argument. And mods using OdysseyHeaders will be defining their own custom table anyway with a custom ProjectActorFactory implementation, so we don't need to externalize the table to make way for modifications. I've moved the includes into the .cpp.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57#-:-NzPZKx49BwmEWw2sXrV:b-ajco6j)* status: 5 of 7 files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/57)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
