### PR TITLE
Library/Movement: Implement `RailMoveMovement`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `RailMoveMovement` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/Movement/RailMoveMovement.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-O9Z45hT2JcA64dCcJbY:-O9Z45hT2JcA64dCcJbZ:ba5jsvt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b54c8339676a06788c03c9fee53dd23719923b5d/lib/al/Library/Movement/RailMoveMovement.h#L3)):*
> ```objc
> #pragma once
> 
> #include "Library/LiveActor/LiveActor.h"
> ```

Is this include necessary?



_Code quote:_
```objc
#include "Library/LiveActor/LiveActor.h"
```
___
*[`lib/al/Library/Movement/RailMoveMovement.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-O9Z3Teg2U4GLz4HT055:-O9Z3Teg2U4GLz4HT056:b-235wsm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b54c8339676a06788c03c9fee53dd23719923b5d/lib/al/Library/Movement/RailMoveMovement.h#L6)):*
> ```objc
> #include "Library/Nerve/NerveStateBase.h"
> 
> enum class RailMoveMovementMoveType : u32 { Loop, Turn, Ahead };
> ```

Move to within `RailMoveMovement` and just call it `MoveType`?

(type change based on `tryGetArg(int*, ...)`)



_Suggestion:_
```objc
enum class RailMoveMovementMoveType : s32 { Loop, Turn, Ahead };
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Movement/RailMoveMovement.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-O9Z45hT2JcA64dCcJbY:-O9Z6v-x3bg3tKQ4S4uV:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b54c8339676a06788c03c9fee53dd23719923b5d/lib/al/Library/Movement/RailMoveMovement.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Is this include necessary?
</blockquote></details>

Done.
___
*[`lib/al/Library/Movement/RailMoveMovement.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-O9Z3Teg2U4GLz4HT055:-O9Z6wEsBz-NF-87AIeF:b-xv6rc2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b54c8339676a06788c03c9fee53dd23719923b5d/lib/al/Library/Movement/RailMoveMovement.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Move to within `RailMoveMovement` and just call it `MoveType`?

(type change based on `tryGetArg(int*, ...)`)
</blockquote></details>

The ctor use `b.lo` instruction which is the unsigned version of `b.lt` according to the documentation.

https://developer.arm.com/documentation/dui0473/m/condition-codes/condition-code-suffixes-and-related-flags

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/Library/Movement/RailMoveMovement.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-O9Z3Teg2U4GLz4HT055:-O9ZA_TsD2KwwyDL3QvN:baa2aun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b54c8339676a06788c03c9fee53dd23719923b5d/lib/al/Library/Movement/RailMoveMovement.h#L6)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

The ctor use `b.lo` instruction which is the unsigned version of `b.lt` according to the documentation.

https://developer.arm.com/documentation/dui0473/m/condition-codes/condition-code-suffixes-and-related-flags


</blockquote></details>

Alright, nevermind then.

**Review by Fuzzy2319 — COMMENTED** [review]
Regarding of the failed check I updated `check-format.py` to allow enum inside classes.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180#-:-OBypvMt2i9RgJjIgWCA:b-knnjjn)* status: 4 of 7 files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/180)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
