### PR TITLE
Library/MapObj: Implement `GateMapParts`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `GateMapParts` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/GateMapParts.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O8nQwHi6O08gYKBgV2D:-O8nQwHi6O08gYKBgV2E:bn0tlx7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.h#L26)):*
> ```objc
>     sead::Quatf mMoveNextQuat = sead::Quatf::unit;
>     sead::Vector3f mMoveNextTrans = sead::Vector3f::zero;
>     s32 _140 = 10;
> ```

These should still be named somehow
___
*[`lib/al/Library/MapObj/GateMapParts.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O8nQsKZ2x6OhJkIV3Py:-O8nQsKZ2x6OhJkIV3Pz:b-5kb41w) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.h#L28)):*
> ```objc
>     s32 _140 = 10;
>     s32 mOpenTime = 120;
>     f32 mBoundRate = .1f;
> ```

same below



_Suggestion:_
```objc
f32 mBoundRate = 0.1f;
```
___
*[`lib/al/Library/MapObj/GateMapParts.cpp` line 35 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O8nREAM61ZVt4CYs-Us:-O8nREAN5uTOBsO05ST2:b6zbhvc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.cpp#L35)):*
> ```cpp
> }
> 
> // can be something like
> ```

Sounds like a change to `sead` is necessary for a proper implementation here. The `Quat` stuff is still missing some parts, so I think it is not a bad idea to provide two different methods of assigning `Quat`s, just like for `Vector`s (`operator=` vs `set`).

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/GateMapParts.cpp` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O99PUzY8XGTW-wKeQNh:-O99PUzY8XGTW-wKeQNi:b-scubsq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.cpp#L33)):*
> ```cpp
>     out->z = other.z;
>     out->w = other.w;
> }
> ```

https://github.com/open-ead/sead/pull/144
=> use simple assignment (`=`) once this PR is merged.



_Code quote:_
```cpp
void setQuat(sead::Quatf* out, const sead::Quatf& other) {
    out->x = other.x;
    out->y = other.y;
    out->z = other.z;
    out->w = other.w;
}
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/GateMapParts.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O8nQwHi6O08gYKBgV2D:-O9IvhT-3iwuMou1tCRj:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.h#L26)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

These should still be named somehow
</blockquote></details>

Done.
___
*[`lib/al/Library/MapObj/GateMapParts.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O8nQsKZ2x6OhJkIV3Py:-O9Ivhx-ApJPc7MAHBaR:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

same below
</blockquote></details>

Done.
___
*[`lib/al/Library/MapObj/GateMapParts.cpp` line 33 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O99PUzY8XGTW-wKeQNh:-O9IvjWV4XFFkBjIEaNy:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/411780e74a2acf037a9185c4b8112865ab2f67a2/lib/al/Library/MapObj/GateMapParts.cpp#L33)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

https://github.com/open-ead/sead/pull/144
=> use simple assignment (`=`) once this PR is merged.
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/GateMapParts.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O9Jx5VX-hl3cjVzAhWA:-O9Jx5VX-hl3cjVzAhWB:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0757b4e14bbfbb11d443f373a34a5b4735ea19e4/lib/al/Library/MapObj/GateMapParts.h#L29)):*
> ```objc
>     s32 mOpenTime = 120;
>     f32 mBoundRate = 0.1f;
>     s32 mStepRemaining = 120;
> ```





_Suggestion:_
```objc
s32 mCurrentBoundSteps = 120;
```
___
*[`lib/al/Library/MapObj/GateMapParts.h` line 31 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O9Jx1ZkAtge5uDGontY:-O9Jx1ZkAtge5uDGontZ:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0757b4e14bbfbb11d443f373a34a5b4735ea19e4/lib/al/Library/MapObj/GateMapParts.h#L31)):*
> ```objc
>     s32 mStepRemaining = 120;
>     s32 mHitReactionCurrent = 0;
>     f32 mBoundRateFactor = 0.1f;
> ```





_Suggestion:_
```objc
f32 mCurrentBoundRate = 0.1f;
```
___
*[`lib/al/Library/MapObj/GateMapParts.cpp` line 116 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O9JxV0k23FSVDS0ATlK:-O9JxV0k23FSVDS0ATlL:b3t10lf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0757b4e14bbfbb11d443f373a34a5b4735ea19e4/lib/al/Library/MapObj/GateMapParts.cpp#L116)):*
> ```cpp
>     f32 rate = calcNerveRate(this, mStepRemaining - 1);
>     rate = sead::Mathf::pow(mBoundRateFactor * (rate * 2 - 1.0f), 2);
>     rate += (1.0f - sead::Mathf::pow(mBoundRateFactor, 2));
> ```

Full formula:
`rate = (mCurrentBoundRate * (2*nerveRate - 1))^2 + (1 - mCurrentBoundRate^2)`

... which traces a symmetric parabola (in range [0,1]) with the opening at the top, meaning it starts at the end of the animation, "rebounds" a bit backwards (upwards) before falling down again.



_Code quote:_
```cpp
    rate = sead::Mathf::pow(mBoundRateFactor * (rate * 2 - 1.0f), 2);
    rate += (1.0f - sead::Mathf::pow(mBoundRateFactor, 2));
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/GateMapParts.h` line 29 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O9Jx5VX-hl3cjVzAhWA:-O9KB429CdONsQU03Rtj:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0757b4e14bbfbb11d443f373a34a5b4735ea19e4/lib/al/Library/MapObj/GateMapParts.h#L29)):*
> ```objc
>     s32 mOpenTime = 120;
>     f32 mBoundRate = 0.1f;
>     s32 mStepRemaining = 120;
> ```

Done.
___
*[`lib/al/Library/MapObj/GateMapParts.h` line 31 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173#-O9Jx1ZkAtge5uDGontY:-O9KB4Z194jt3ZaeZgzU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/0757b4e14bbfbb11d443f373a34a5b4735ea19e4/lib/al/Library/MapObj/GateMapParts.h#L31)):*
> ```objc
>     s32 mStepRemaining = 120;
>     s32 mHitReactionCurrent = 0;
>     f32 mBoundRateFactor = 0.1f;
> ```

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/173)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
