### PR TITLE
Library/MapObj: Implement `KeyMoveMapPartsGenerator`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `KeyMoveMapPartsGenerator` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/KeyMoveMapPartsGenerator.cpp` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXpckuEigCEYkW_gC9:-OCXpckuEigCEYkW_gCA:b-a5yjns) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/MapObj/KeyMoveMapPartsGenerator.cpp#L27)):*
> ```cpp
>     initActorSceneInfo(this, info);
>     initExecutorMapObjMovement(this, info);
>     initActorPoseTQSV(this);
> ```

Interesting, it initializes the pose keeper manually instead of calling the "initialize everything from PlacementInfo"-functions.
___
*[`lib/al/Library/LiveActor/LiveActorGroup.h` line 43 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXpUn840A3U4XHZBt7:-OCXpUn840A3U4XHZBt8:b-b4h2z5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/LiveActor/LiveActorGroup.h#L43)):*
> ```objc
> class DeriveActorGroup : public LiveActorGroup {
> public:
>     DeriveActorGroup(const char* groupName, s32 groupCount)
> ```

Yeah, no idea why this was so wrong before - that definitely didn't compile, but nobody noticed because it wasn't used anywhere. Fun.
___
*[`lib/al/Library/MapObj/KeyMoveMapPartsGenerator.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXp4KR26AV25z-EzY9:-OCXp4KS5PtPhQ4z-iCr:b-p7dnxo) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/MapObj/KeyMoveMapPartsGenerator.h#L4)):*
> ```objc
> 
> #include "Library/LiveActor/LiveActor.h"
> #include "Library/LiveActor/LiveActorGroup.h"
> ```

Should be forward-declared instead:
```cpp
template <class T>
class DeriveActorGroup;
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/KeyMoveMapPartsGenerator.h` line 4 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXp4KR26AV25z-EzY9:-OCXsZiT6isfPinbYwWd:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/MapObj/KeyMoveMapPartsGenerator.h#L4)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should be forward-declared instead:
```cpp
template <class T>
class DeriveActorGroup;
```
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/LiveActor/LiveActorGroup.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXsTV8EX71I-y8dUEd:-OCXsTV8EX71I-y8dUEe:b5di0f2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/LiveActor/LiveActorGroup.h#L46)):*
> ```objc
>         : LiveActorGroup(groupName, groupCount) {}
> 
>     T* getActor(s32 idx) const { return (T*)LiveActorGroup::getActor(idx); }
> ```

My IDE warns me about hidden functions, but the code matches, should I keep it that way? I did it this way to avoid casting.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/LiveActor/LiveActorGroup.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXsTV8EX71I-y8dUEd:-OCXv0vvADMXT3JqsOyi:b13z799) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/LiveActor/LiveActorGroup.h#L46)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

My IDE warns me about hidden functions, but the code matches, should I keep it that way? I did it this way to avoid casting.

</blockquote></details>

Hmm, good point - what about renaming the functions to `getTActor` and `tryFindDeadTActor`, or `getDeriveActor` and `tryFindDeadDeriveActor` respectively?

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/LiveActor/LiveActorGroup.h` line 46 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201#-OCXsTV8EX71I-y8dUEd:-OCXw5xUAoR9Y1GBgXc3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/662d6a76a1162a68e5ca523582b5af2cc2a290d9/lib/al/Library/LiveActor/LiveActorGroup.h#L46)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Hmm, good point - what about renaming the functions to `getTActor` and `tryFindDeadTActor`, or `getDeriveActor` and `tryFindDeadDeriveActor` respectively?
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/201)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
