### PR TITLE
AccountHolder functions

### PR DESCRIPTION
**Pull request by Fuzzy2319**
this pr adds `AccountHolder` definition and it's implementation

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Yes, great work! Not much to comment on here, the functions are looking correct and you mostly followed the styling guide (see failed run for details). Only one question remaining below.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-:-NvcS_cuAPXV9WAg0iZT:b-iqwn3g)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Network/AccountHolder.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-NvcSLYv9AlaIUgAVuLG:-NvcSLYv9AlaIUgAVuLH:b-9a1dl4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8981fc06af79e8a5f4ef70d9f7062eb73efa304b/lib/al/src/Library/Network/AccountHolder.cpp#L6)):*
> ```cpp
> AccountHolder::AccountHolder() {
>     nn::account::Initialize();
>     mUserHandle = new nn::account::UserHandle;
> ```

Does it mismatch when using `new nn::account::UserHandle();` here?

**Comment by Fuzzy2319** [comment]
> Yes, great work! Not much to comment on here, the functions are looking correct and you mostly followed the styling guide (see failed run for details). Only one question remaining below.
> 
> > Reviewed 3 of 3 files at r1, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-:-NvcS_cuAPXV9WAg0iZT:b-iqwn3g)_ status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)
> 
> _[`lib/al/src/Library/Network/AccountHolder.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-NvcSLYv9AlaIUgAVuLG:-NvcSLYv9AlaIUgAVuLH:b-9a1dl4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8981fc06af79e8a5f4ef70d9f7062eb73efa304b/lib/al/src/Library/Network/AccountHolder.cpp#L6)):_
> 
> > ```c++
> > AccountHolder::AccountHolder() {
> >     nn::account::Initialize();
> >     mUserHandle = new nn::account::UserHandle;
> > ```
> 
> Does it mismatch when using `new nn::account::UserHandle();` here?

Yes it missmatch with `new nn::account::UserHandle();`

Here is the diff:
image

**Review by MonsterDruide1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-:-Nvekg3RDMy7tQFDItPX:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Network/AccountHolder.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32#-NvcSLYv9AlaIUgAVuLG:-Nvekl1O0xiHHamLg6dR:b-3xtgrh) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/8981fc06af79e8a5f4ef70d9f7062eb73efa304b/lib/al/src/Library/Network/AccountHolder.cpp#L6)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

Yes it missmatch with `new nn::account::UserHandle();`

Here is the diff:
image

</blockquote></details>

Alright - thanks for showing!

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
