### PR TITLE
Misc mod headers

### PR DESCRIPTION
**Pull request by LynxDev2**
Small changes to headers mainly from galaxy mod and one new header

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169)* status: all files reviewed, 16 unresolved discussions (waiting on @LynxDev2)

___
*[`lib/al/Library/Collision/PartsConnector.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Wl9u2EeceJvka7Q3:-O81Wl9u2EeceJvka7Q4:b-22a4i2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/lib/al/Library/Collision/PartsConnector.h#L14)):*
> ```objc
> void attachMtxConnectorToCollision(MtxConnector* mtxConnector, const LiveActor* actor, bool);
> void connectPoseQT(LiveActor* actor, const MtxConnector* mtxConnector, const sead::Quatf& quat,
>                    const sead::Vector3f& vec);
> ```

Given that hte name is `PoseQT`, the variables should be called `quat` and `trans` or `translation`.
___
*[`lib/al/Library/Collision/PartsConnector.h` line 20 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81WyIm1A0b-t40oQF-:-O81WyIm1A0b-t40oQF0:b-78ymr8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/lib/al/Library/Collision/PartsConnector.h#L20)):*
> ```objc
>                                const sead::Vector3f&);
> void disconnectMtxConnector(MtxConnector*);
> bool isMtxConnectorConnecting(const MtxConnector*);
> ```

Parameter names



_Code quote:_
```objc
void attachMtxConnectorToJoint(MtxConnector*, const LiveActor*, const char*);
void attachMtxConnectorToJoint(MtxConnector*, const LiveActor*, const char*, const sead::Vector3f&,
                               const sead::Vector3f&);
void disconnectMtxConnector(MtxConnector*);
bool isMtxConnectorConnecting(const MtxConnector*);
```
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Y0QV5rhG1hfPhWcA:-O81Y0QV5rhG1hfPhWcB:b-2zllp8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L28)):*
> ```objc
>     void updateSearchAmiiboName();
>     bool requestAppearAmiiboLayout();
>     bool requestDecideAmiiboLayout();
> ```

This one seems to be `void`? Why are they so inconsistent...
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Y5La6SxGoj1Eb3JG:-O81Y5La6SxGoj1Eb3JH:boraxfz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L29)):*
> ```objc
>     bool requestAppearAmiiboLayout();
>     bool requestDecideAmiiboLayout();
>     bool requestEndAmiiboLayout();
> ```

Same here, `void` return type
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YMSS5G8uAGFrM2yd:-O81YMSS5G8uAGFrM2ye:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L31)):*
> ```objc
>     bool requestEndAmiiboLayout();
>     bool isEndAmiiboLayout();
>     u32 registerSearchAmiibo(s32, s32, ulong);
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YNO2E4mGNWurPCFr:-O81YNO2E4mGNWurPCFs:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L32)):*
> ```objc
>     bool isEndAmiiboLayout();
>     u32 registerSearchAmiibo(s32, s32, ulong);
>     bool deleteSearchEndAmiibo();
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Xnro4uH0TrZblBMo:-O81Xnro4uH0TrZblBMp:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L36)):*
> ```objc
>     u32 getSearchAmiiboNum();
>     u32 getSearchEndAmiiboNum();
>     u32 getSearchEndAmiiboNumRealTime();
> ```





_Suggestion:_
```objc
    u32 getSearchAmiiboNum() const;
    u32 getSearchEndAmiiboNum() const;
    u32 getSearchEndAmiiboNumRealTime() const;
```
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YTA8D8ZBZhtCKGPb:-O81YTA8D8ZBZhtCKGPc:b-tr282t) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L37)):*
> ```objc
>     u32 getSearchEndAmiiboNum();
>     u32 getSearchEndAmiiboNumRealTime();
>     u32 isEnableSearchAmiibo();
> ```

`bool`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 52 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_P7P53LE9miA8xAt:-O81_P7P53LE9miA8xAu:b-3ciwn2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L52)):*
> ```objc
> // Can't be split since these functions are in the middle of AmiiboNpcDirector in the executable
> 
> class AmiiboFunction {
> ```

As far as I can tell, these functions do not use internals of `AmiiboNpcDirector` (apart from inlined functions), so a friend class is not needed here. Turn this into a `namespace` instead, using non-static functions.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 60 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_jOz18r2TEmVlGlu:-O81_jOz18r2TEmVlGlv:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L60)):*
> ```objc
>     static bool isNfpErrorHandled(const al::IUseSceneObjHolder*);
>     static bool requestAppearAmiiboLayout(const al::IUseSceneObjHolder*);
>     static bool requestDecideAmiiboLayout(const al::IUseSceneObjHolder*);
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 61 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_lVF8gdLa7r1_Ykg:-O81_lVF8gdLa7r1_Ykh:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L61)):*
> ```objc
>     static bool requestAppearAmiiboLayout(const al::IUseSceneObjHolder*);
>     static bool requestDecideAmiiboLayout(const al::IUseSceneObjHolder*);
>     static bool requestEndAmiiboLayout(const al::IUseSceneObjHolder*);
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aPDrD7eiN3166pWn:-O81aPDrD7eiN3166pWo:b-1fwu0p) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L63)):*
> ```objc
>     static bool requestEndAmiiboLayout(const al::IUseSceneObjHolder*);
>     static bool isEndAmiiboLayout(const al::IUseSceneObjHolder*);
>     static AmiiboNpcLayout* getAmiiboTouchLayout(const al::IUseSceneObjHolder*);
> ```

Where did you get this type from?
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 68 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aUiM-fyWg2OgJ3BS:-O81aUiM-fyWg2OgJ3BT:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L68)):*
> ```objc
>     static u32 getSearchEndAmiiboNum(const al::IUseSceneObjHolder*);
>     static u32 getSearchEndAmiiboNumRealTime(const al::IUseSceneObjHolder*);
>     static u32 registerSearchAmiibo(const al::IUseSceneObjHolder*, const al::NfpInfo&);
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 71 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aZO63H6u1BnJGEp3:-O81aZO63H6u1BnJGEp4:b-tg2gun) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L71)):*
> ```objc
> 
>     static bool isSearchAmiibo(const al::IUseSceneObjHolder*, const al::NfpInfo&);
>     static bool deleteSearchEndAmiibo(const al::IUseSceneObjHolder*);
> ```

`void`
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 73 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81ayU-7jqRTmLPkH8s:-O81ayU-7jqRTmLPkH8t:b-3xufsy) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L73)):*
> ```objc
>     static bool deleteSearchEndAmiibo(const al::IUseSceneObjHolder*);
>     static void setTalkStartTime(const al::IUseSceneObjHolder*);
>     static const char* getMessageTagDataHolder(const al::IUseSceneObjHolder*);
> ```

Same here, where is the type from? Quick research shows me `sead::DelegateThread`, but ... I kind of doubt that one.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 76 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81ajVT4j7KgXm0Zp3Y:-O81ajVT4j7KgXm0Zp3Z:b-2oli5k) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L76)):*
> ```objc
>     static void setTouchAmiiboName(const al::IUseSceneObjHolder*, s32, s32);
>     static void trySetAmiiboCostumeName(const al::IUseSceneObjHolder*, s32);
> };
> ```

Missing `tryCreateHelpAmiiboDirector` and four `isTriggerTouchAmiiboX` functions

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169)* status: 5 of 7 files reviewed, 16 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Collision/PartsConnector.h` line 14 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Wl9u2EeceJvka7Q3:-O8Y6uPQBliT107QiO_E:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/lib/al/Library/Collision/PartsConnector.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Given that hte name is `PoseQT`, the variables should be called `quat` and `trans` or `translation`.
</blockquote></details>

Done.
___
*[`lib/al/Library/Collision/PartsConnector.h` line 20 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81WyIm1A0b-t40oQF-:-O8Y6v9aEsWj6Mbkz4jZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/lib/al/Library/Collision/PartsConnector.h#L20)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Parameter names
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 28 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Y0QV5rhG1hfPhWcA:-O8Y6wDREfWHODv0JDG9:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L28)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This one seems to be `void`? Why are they so inconsistent...
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 29 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Y5La6SxGoj1Eb3JG:-O8Y6wvL71iQVOBulUWu:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L29)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same here, `void` return type
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 31 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YMSS5G8uAGFrM2yd:-O8Y6xr73Dpz4uPiRYl6:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L31)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 32 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YNO2E4mGNWurPCFr:-O8Y6xe39tbtmYbxdCZi:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L32)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81Xnro4uH0TrZblBMo:-O8Y6yoYE_mBoolayGIU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L36)):*
> ```objc
>     u32 getSearchAmiiboNum();
>     u32 getSearchEndAmiiboNum();
>     u32 getSearchEndAmiiboNumRealTime();
> ```

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81YTA8D8ZBZhtCKGPb:-O8Y7-5v8CivSntaAsxI:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`bool`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 52 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_P7P53LE9miA8xAt:-O8Y7-r6Ct9FpDFhCYS_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L52)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

As far as I can tell, these functions do not use internals of `AmiiboNpcDirector` (apart from inlined functions), so a friend class is not needed here. Turn this into a `namespace` instead, using non-static functions.
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 60 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_jOz18r2TEmVlGlu:-O8Y70c1-FToI1vB4tgA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L60)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 61 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81_lVF8gdLa7r1_Ykg:-O8Y70rp9P-i2k0JIfv_:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L61)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aPDrD7eiN3166pWn:-O8Y72VW0H1u2p9IPXTV:bkdywv0) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L63)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Where did you get this type from?
</blockquote></details>

From the functions usage
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 68 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aUiM-fyWg2OgJ3BS:-O8Y77NF56b2M2h61Tqu:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L68)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 71 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aZO63H6u1BnJGEp3:-O8Y77wh5iSMBrZGAx6f:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L71)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`void`
</blockquote></details>

Done.
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 73 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81ayU-7jqRTmLPkH8s:-O8Y7t1cEiZRg2ob5zhR:b-usxixl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L73)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Same here, where is the type from? Quick research shows me `sead::DelegateThread`, but ... I kind of doubt that one.
</blockquote></details>

Based on the usage it's actually just simply it's own type `MessageTagDataHolder`. I'll update that
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 76 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81ajVT4j7KgXm0Zp3Y:-O8Y80Om3T4z6SkkN8Zr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L76)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Missing `tryCreateHelpAmiiboDirector` and four `isTriggerTouchAmiiboX` functions
</blockquote></details>

Done.

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169)* status: 5 of 8 files reviewed, 16 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Amiibo/AmiiboNpcDirector.h` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aPDrD7eiN3166pWn:-O8YA8Ic6Juoecpqw6QN:bhsd5n7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L63)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

From the functions usage
</blockquote></details>

Done. (Reviewable wants me to add this)
___
*[`src/Amiibo/AmiiboNpcDirector.h` line 73 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81ayU-7jqRTmLPkH8s:-O8Y9ZU_7kf9ugcqPUCK:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L73)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

Based on the usage it's actually just simply it's own type `MessageTagDataHolder`. I'll update that
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

___
*[`src/Amiibo/AmiiboNpcDirector.h` line 63 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/169#-O81aPDrD7eiN3166pWn:-O8YU4Qf2NFqi7iaFHAj:b-r20ywu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/2bdf33a13ca67257a484b4245a4193e4086bef76/src/Amiibo/AmiiboNpcDirector.h#L63)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

Done. (Reviewable wants me to add this)
</blockquote></details>

You can also click the status icon to change it to `Resolved` manually instead of using the "Done" text.

**Pull request merged**
