### PR TITLE
SceneEventFlowMsg functions

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `SceneEventFlowMsg` definition and it's implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Event/SceneEventFlowMsg.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45#-Nynw8X3AHXN0PEIScYE:-Nynw8X3AHXN0PEIScYF:bs8731a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c511f4ef8efdff74f185b9c7806193192932ed94/lib/al/src/Library/Event/SceneEventFlowMsg.cpp#L6)):*
> ```cpp
> 
> namespace al {
> SceneEventFlowMsg::SceneEventFlowMsg() : mCmd("") {}
> ```

Define in header instead: `sead::FixedSafeString<64> mCmd = "";`, then have just `() {}` here.

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Event/SceneEventFlowMsg.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45#-Nynw8X3AHXN0PEIScYE:-NynxXhq-qYR53TBKQfN:b5ioydp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c511f4ef8efdff74f185b9c7806193192932ed94/lib/al/src/Library/Event/SceneEventFlowMsg.cpp#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Define in header instead: `sead::FixedSafeString<64> mCmd = "";`, then have just `() {}` here.
</blockquote></details>


it doesn't compile when I do this.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Event/SceneEventFlowMsg.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45#-Nynw8X3AHXN0PEIScYE:-NynyTDvDrkjeZRJyUZl:bjoy68j) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c511f4ef8efdff74f185b9c7806193192932ed94/lib/al/src/Library/Event/SceneEventFlowMsg.cpp#L6)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>


it doesn't compile when I do this.
</blockquote></details>

Hmm, maybe `mCmd = {""};`?

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Event/SceneEventFlowMsg.cpp` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45#-Nynw8X3AHXN0PEIScYE:-Nyo07ZM4uxyR2MU2Ftr:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c511f4ef8efdff74f185b9c7806193192932ed94/lib/al/src/Library/Event/SceneEventFlowMsg.cpp#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Hmm, maybe `mCmd = {""};`?
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
