### PR TITLE
CounterLife

### PR DESCRIPTION
**Pull request by Wexos**
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @Wexos)

___
*[`src/Layout/CounterLife.h` line 38 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q2QIB5IPOzF-vr5uU:-O4Q2QIB5IPOzF-vr5uV:b-kmrxpj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.h#L38)):*
> ```objc
> private:
>     f32 mCurFrame = 0.0f;
>     f32 mGoalFrame = 0.0f;
> ```

I'm not sure about naming these `...Frame`. What makes you believe it has something to do with frames?



_Code quote:_
```objc
    void startGauge(f32 goalFrame);

    void startGaugeWithFrame(f32 goalFrame, f32 frames);

    void setEmpty();

    void setGaugeAnim();

    void setCount(f32 frame);



    void start();

    void end();

    void wait();

    bool isWait() const;



    void exeNone();

    void exeAppear();

    void exeWait();

    void exeEnd();

    void exeGauge();

    void exeGaugeWait();



private:

    f32 mCurFrame = 0.0f;

    f32 mGoalFrame = 0.0f;
```
___
*[`src/Layout/CounterLife.cpp` line 78 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q2nIB2WKq110hqTSH:-O4Q2nIC7wDljEOZSLMU:b-vnppt3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L78)):*
> ```cpp
> }
> 
> void CounterLife::setCount(f32 frame) {
> ```

... especially this. `setCount`, passing a `frame`?

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @Wexos)

___
*[`src/Layout/CounterLife.h` line 38 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q2QIB5IPOzF-vr5uU:-O4Q8eCy1LtEPeI31BkF:bf9dhct) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.h#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'm not sure about naming these `...Frame`. What makes you believe it has something to do with frames?
</blockquote></details>

Nevermind. It interpolates the animation, which changes color depending on the number of lives.
___
*[`src/Layout/CounterLife.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9JzsEGuqY3UzZfsJ:-O4Q9JzsEGuqY3UzZfsK:bw25zi1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L37)):*
> ```cpp
>         al::startAction(this, "Loop", "Loop");
>     else
>         al::startFreezeAction(this, "Loop", 0.0f, "Loop");
> ```

(inlined function)



_Code quote:_
```cpp
    if (mIsCounterUp)

        return;



    if (GameDataFunction::getPlayerHitPoint(GameDataHolderAccessor(this)) == 1)

        al::startAction(this, "Loop", "Loop");

    else

        al::startFreezeAction(this, "Loop", 0.0f, "Loop");
```
___
*[`src/Layout/CounterLife.cpp` line 57 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9PFL0IFi8RLtJ91J:-O4Q9PFL0IFi8RLtJ91K:bjsocmi) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L57)):*
> ```cpp
> 
>     if (mCurFrame < mGoalFrame)
>         maxLifeFrames = al::getActionFrameMax(this, "Damage", "Life");
> ```

Not sure if this is equivalent, if not, then still make this an explicit `else` by doing `f32 maxLifeFrames;` above



_Suggestion:_
```cpp
    f32 maxLifeFrames = al::getActionFrameMax(this, mCurFrame < mGoalFrame ? "Add" : "Damage", "Life");
```
___
*[`src/Layout/CounterLife.cpp` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAuUWEtWG5bgBcGfj:-O4QAuUWEtWG5bgBcGfk:b-dfvxhj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L59)):*
> ```cpp
>         maxLifeFrames = al::getActionFrameMax(this, "Damage", "Life");
> 
>     mStep = (maxGaugeFrames / 3) / maxLifeFrames;
> ```

I wonder if this hardcoded `3` causes some problems with non-3-segmented gauges...
___
*[`src/Layout/CounterLife.cpp` line 71 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9mQH8W3gW9TpeqvL:-O4Q9mQH8W3gW9TpeqvM:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L71)):*
> ```cpp
> void CounterLife::setEmpty() {
>     f32 gaugeMax = al::getActionFrameMax(this, "Gauge", "Gauge");
>     setCount(gaugeMax);
> ```





_Suggestion:_
```cpp
    setCount(al::getActionFrameMax(this, "Gauge", "Gauge"));
```
___
*[`src/Layout/CounterLife.cpp` line 124 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9Flf8nPE-STP3JO-:-O4Q9Flf8nPE-STP3JO0:b-nkkdhs) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L124)):*
> ```cpp
>             else
>                 al::startFreezeAction(this, "Loop", 0.0f, "Loop");
>         }
> ```

Make this an inlined function reused in `init`



_Code quote:_
```cpp
        if (!mIsCounterUp) {

            if (GameDataFunction::getPlayerHitPoint(GameDataHolderAccessor(this)) == 1)

                al::startAction(this, "Loop", "Loop");

            else

                al::startFreezeAction(this, "Loop", 0.0f, "Loop");

        }
```
___
*[`src/Layout/CounterLife.cpp` line 140 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAU0G0KvqbzeDk3kQ:-O4QAU0G0KvqbzeDk3kR:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L140)):*
> ```cpp
>         mCurFrame = mGoalFrame;
> 
>         al::startFreezeAction(this, "Gauge", mGoalFrame, "Gauge");
> ```





_Suggestion:_
```cpp
setGaugeAnim();
```

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @Wexos)

___
*[`src/Layout/CounterLife.cpp` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAuUWEtWG5bgBcGfj:-O4QDVbFDIeaWT-qxhaK:b-w50k79) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L59)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I wonder if this hardcoded `3` causes some problems with non-3-segmented gauges...
</blockquote></details>

Well, not "problems", but ... I guess they at least didn't intend it. Measuring how long the gauge takes to deplete in normal mode and comparing it to assist mode, it only takes half the time in assist mode - `19` frames instead of `38`.

**Review by Wexos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/CounterLife.cpp` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9JzsEGuqY3UzZfsJ:-O4QVADo5Oouh7SsgEbn:b-3tyhtf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(inlined function)
</blockquote></details>

Constructor doesn't match, so keeping this like it is.
___
*[`src/Layout/CounterLife.cpp` line 57 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9PFL0IFi8RLtJ91J:-O4QH0g-5cJuHHfW9ogg:b-paiqzx) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L57)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Not sure if this is equivalent, if not, then still make this an explicit `else` by doing `f32 maxLifeFrames;` above
</blockquote></details>

Neither matches, which makes sense, because the compiler can't know what the function actually does. I don't remember what it's called, but it's a fundamental part of C++ where a compiler is only allowed to optimize away destructor calls as far as I remember.
___
*[`src/Layout/CounterLife.cpp` line 59 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAuUWEtWG5bgBcGfj:-O4QI-fK6RpF2g59W3iJ:bqcaj1t) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L59)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Well, not "problems", but ... I guess they at least didn't intend it. Measuring how long the gauge takes to deplete in normal mode and comparing it to assist mode, it only takes half the time in assist mode - `19` frames instead of `38`.
</blockquote></details>

Nice catch, I was confused what the `3` meant
___
*[`src/Layout/CounterLife.cpp` line 71 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9mQH8W3gW9TpeqvL:-O4QVTxaEfv0-3x9xjzW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L71)):*
> ```cpp
> void CounterLife::setEmpty() {
>     f32 gaugeMax = al::getActionFrameMax(this, "Gauge", "Gauge");
>     setCount(gaugeMax);
> ```

Done.
___
*[`src/Layout/CounterLife.cpp` line 124 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9Flf8nPE-STP3JO-:-O4QVY7mDEiUXAKtL4TL:b75xfrt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L124)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Make this an inlined function reused in `init`
</blockquote></details>

Keeping it since constructor doesn't match with inlined function.
___
*[`src/Layout/CounterLife.cpp` line 140 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAU0G0KvqbzeDk3kQ:-O4QVbsA6jwt03Lmtxes:b-el4zco) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L140)):*
> ```cpp
>         mCurFrame = mGoalFrame;
> 
>         al::startFreezeAction(this, "Gauge", mGoalFrame, "Gauge");
> ```

Can't, because it uses `mGoalFrame` and not `mCurFrame`

**Review by Wexos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/CounterLife.cpp` line 140 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAU0G0KvqbzeDk3kQ:-O4QbSBu2I5deaU3d7ck:b-y52cqh) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L140)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Can't, because it uses `mGoalFrame` and not `mCurFrame`
</blockquote></details>

Nevermind, fixed.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Wexos)

___
*[`src/Layout/CounterLife.cpp` line 57 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4Q9PFL0IFi8RLtJ91J:-O4QuHuK-Aehib8odhlP:boluj35) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L57)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Neither matches, which makes sense, because the compiler can't know what the function actually does. I don't remember what it's called, but it's a fundamental part of C++ where a compiler is only allowed to optimize away destructor calls as far as I remember.
</blockquote></details>

Oh wait, yeah, it has to do two function calls in some cases... I only thought about the case where the decompiler outputs the "else" case as always-initializing by that value above `if`, but that only works with constant values. Makes sense.
___
*[`src/Layout/CounterLife.cpp` line 140 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/144#-O4QAU0G0KvqbzeDk3kQ:-O4Qty886j_Vl0wODqs4:b-mz3345) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b2014fb68a1ef1c05c6bd23c68db0e7762fd5a6d/src/Layout/CounterLife.cpp#L140)):*
<details><summary><i>Previously, Wexos wrote…</i></summary><blockquote>

Nevermind, fixed.
</blockquote></details>

`mCurFrame` is set to `mGoalFrame`, and to avoid a useless data dependency (=> better pipelining), the compiler uses mGoalFrame (or rather register holding its value), as that one has the value while `mCurFrame` might still be writing.

**Pull request merged**
