### PR TITLE
Player: Implement PlayerCounterQuickTurnJump

### PR DESCRIPTION
**Pull request by MonsterDruide1**
Another simple class, responsible for detecting `QuickTurn`s and counting down from (default) `20`, allowing to initiate a `QuickTurnJump` in that window, and disallowing it again afterwards.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)

### CODE REVIEW

**Review by tetraxile — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerCounterQuickTurnJump.h` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZwi280gpMkdv_C6QO:-NzZwi280gpMkdv_C6QP:bytqixr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerCounterQuickTurnJump.h#L18)):*
> ```objc
>     const PlayerConst* mConst;
>     const PlayerTrigger* mTrigger;
>     s32 mFrame = 0;
> ```

how about `mCounter`? i think PlayerConst::getQuickTurnJumpFrame would only refer to the max frame number, so this name can be different because it counts down.
___
*[`src/Player/PlayerTrigger.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZx5Y78T11tymOnDMn:-NzZx5Y78T11tymOnDMo:bsxssvh) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerTrigger.h#L11)):*
> ```objc
>     enum EAttackSensorTrigger : u32 {};
>     enum EActionTrigger : u32 {
>         EActionTrigger_QuickTurn = 34,
> ```

`EActionTrigger_QuickTurnJump` may be better, it's referred to as "TurnJump" in the `isEnableTurnJump` method above so i think it should include the word "Jump"

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1 and @tetraxile)

___
*[`src/Player/PlayerCounterQuickTurnJump.h` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZwi280gpMkdv_C6QO:-NzZxuvD0Pr6A0AlGY7o:brz3vvl) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerCounterQuickTurnJump.h#L18)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

how about `mCounter`? i think PlayerConst::getQuickTurnJumpFrame would only refer to the max frame number, so this name can be different because it counts down.
</blockquote></details>

I was thinking that something else was using `mCounter` for something to count up, but ... looking at the code again, that was `PlayerCounterForceRun`, which also uses it to count down, so that's fine. Will adjust it in a second.
___
*[`src/Player/PlayerTrigger.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZx5Y78T11tymOnDMn:-NzZyDjiBbzVfGtesEfO:b-nd3ml3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerTrigger.h#L11)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

`EActionTrigger_QuickTurnJump` may be better, it's referred to as "TurnJump" in the `isEnableTurnJump` method above so i think it should include the word "Jump"
</blockquote></details>

Nope, that's what I thought first as well, but the counter is *started* on this action, allowing you to jump within the time frame - not forcing, so it doesn't actually trigger the jump. So, `ActionTrigger_34` is a *prerequisite* before being able to do the jump, which should be the turn itself. I can also look through some other classes for references though, if you want me to re-confirm this.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)* status: all files reviewed, 2 unresolved discussions (waiting on @tetraxile)

___
*[`src/Player/PlayerCounterQuickTurnJump.h` line 18 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZwi280gpMkdv_C6QO:-NzZzNYQ38qQJ6LDFBeW:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerCounterQuickTurnJump.h#L18)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I was thinking that something else was using `mCounter` for something to count up, but ... looking at the code again, that was `PlayerCounterForceRun`, which also uses it to count down, so that's fine. Will adjust it in a second.
</blockquote></details>

Done.

**Review by tetraxile — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerTrigger.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-NzZx5Y78T11tymOnDMn:-NzZyvkh5DRAxphz8JGw:baw0118) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/861187183e1456fc39f176108f7750fa05d7b767/src/Player/PlayerTrigger.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Nope, that's what I thought first as well, but the counter is *started* on this action, allowing you to jump within the time frame - not forcing, so it doesn't actually trigger the jump. So, `ActionTrigger_34` is a *prerequisite* before being able to do the jump, which should be the turn itself. I can also look through some other classes for references though, if you want me to re-confirm this.
</blockquote></details>

ah that's fair enough. i'm not too pushed about it so it can stay as is

**Review by tetraxile — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/62#-:-Nz_-k6H8ZJeCOj58zty:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

**Review by tetraxile — APPROVED** [review]

**Pull request merged**
