### PR TITLE
Player: Implement PlayerWallActionHistory

### PR DESCRIPTION
**Pull request by MonsterDruide1**
This class keeps track of the last `Jump` and `Leave` position and normal of a `WallAction` (=Slide, Jump).

As `update` is called on every frame, the information will be `reset` as soon as the Player touches the ground.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)

### CODE REVIEW

**Review by tetraxile — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerWallActionHistory.h` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzoODz632aMaf6GdICo:-NzoODz7CVEYVVPOmVov:b6jpnhf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/6a0f72e8cced51910c0a7c8437e560c52ccbc2d8/src/Player/PlayerWallActionHistory.h#L8)):*
> ```objc
> public:
>     PlayerWallActionHistory();
>     void update(const IUsePlayerCollision* collision);
> ```

unsure if i have mentioned this before but i kinda like calling these `collider` or similar, as it tends to be a `PlayerColliderHakoniwa` that gets passed in. `collision` sounds more like it's a collision triangle itself.

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/Player/PlayerWallActionHistory.h` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzoODz632aMaf6GdICo:-NzoXylv7HFxwdW8hiUk:b-gj8p9z) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/6a0f72e8cced51910c0a7c8437e560c52ccbc2d8/src/Player/PlayerWallActionHistory.h#L8)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

unsure if i have mentioned this before but i kinda like calling these `collider` or similar, as it tends to be a `PlayerColliderHakoniwa` that gets passed in. `collision` sounds more like it's a collision triangle itself.
</blockquote></details>

No, you haven't mentioned it, but I like this suggestion and naming scheme - having `Collision` is confusing, I agree, because we're working with an interface to a class that provides a method that can return a `PlayerCollider` - so it has nothing to do with a collision in the first place, and only "second-level" with a collider, but that's still closer than "nothing".

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerWallActionHistory.cpp` line 7 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzogN0w3RxegVgI1tdV:-NzogN0w3RxegVgI1tdW:b-e9haw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d6296de6408002186b3510be044515d32fd12d59/src/Player/PlayerWallActionHistory.cpp#L7)):*
> ```cpp
> PlayerWallActionHistory::PlayerWallActionHistory() {}
> void PlayerWallActionHistory::update(const IUsePlayerCollision* collider) {
>     if (rs::isCollidedGround(collider)) {
> ```

woops almost missed this, the `{}` braces around the body here seem inconsistent with other one-line `if` bodies

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/Player/PlayerWallActionHistory.cpp` line 7 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzogN0w3RxegVgI1tdV:-NztX6jP24jnxZoprQrV:bnqvigb) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d6296de6408002186b3510be044515d32fd12d59/src/Player/PlayerWallActionHistory.cpp#L7)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

woops almost missed this, the `{}` braces around the body here seem inconsistent with other one-line `if` bodies
</blockquote></details>

True, done. We don't currently have a rule for it though - should we enforce one-line-`if`s to not use braces?

**Review by tetraxile — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerWallActionHistory.cpp` line 7 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzogN0w3RxegVgI1tdV:-Nzta5VDCfvLQ3jvEUS2:b-gxxo11) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d6296de6408002186b3510be044515d32fd12d59/src/Player/PlayerWallActionHistory.cpp#L7)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

True, done. We don't currently have a rule for it though - should we enforce one-line-`if`s to not use braces?
</blockquote></details>

yeah i would say so

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @MonsterDruide1)

___
*[`src/Player/PlayerWallActionHistory.cpp` line 7 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/74#-NzogN0w3RxegVgI1tdV:-NztvkX745GOk154Y-tz:bl6myge) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d6296de6408002186b3510be044515d32fd12d59/src/Player/PlayerWallActionHistory.cpp#L7)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

yeah i would say so
</blockquote></details>

Started discussion on it: https://discord.com/channels/774687602996936747/1249124525681938472

Let's discuss/decide this as generic rule there.

**Pull request merged**
