### PR TITLE
Implement `CameraWatchPoint` and `CameraSubTargetTurnParam`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `CameraWatchPoint` functions and `CameraSubTargetTurnParam` functions

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)

### CODE REVIEW

**Review by GRAnimated — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Project/Camera/CameraSubTargetTurnParam.h` line 21 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0IT82W9ULkFxtYEIEJ:-O0IT82W9ULkFxtYEIEK:bx9gjsn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d3c2bacbda9d7af66e011f5b3f3e9cc02b265af5/lib/al/Project/Camera/CameraSubTargetTurnParam.h#L21)):*
> ```objc
>     f32 mTurnStopStartDistance = -1.0f;
>     f32 mTurnStopEndDistance = -1.0f;
>     s32 mUkn = 30;  // TODO: Find what is this and add a proper name.
> ```

Rename to `field_18` or `_18` to keep consistency with the rest of repo, and the TODO isn't needed

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`lib/al/Project/Camera/CameraSubTargetTurnParam.h` line 21 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0IT82W9ULkFxtYEIEJ:-O0IWI4dD2Ax1wkzq7do:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/d3c2bacbda9d7af66e011f5b3f3e9cc02b265af5/lib/al/Project/Camera/CameraSubTargetTurnParam.h#L21)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Rename to `field_18` or `_18` to keep consistency with the rest of repo, and the TODO isn't needed
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)* status: all files reviewed, 3 unresolved discussions (waiting on @Fuzzy2319 and @GRAnimated)

___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 11 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0K-Esm3758GU8wZoFG:-O0K-Esn8fv3BvTg4Dms:bsk6ujc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c9c39fca4d5d4f738f5bdf33552a9eddadd0965f/lib/al/Library/LiveActor/ActorInitFunction.h#L11)):*
> ```objc
> void initActorPoseTRSV(LiveActor* actor);
> void initActorSRT(LiveActor* actor, const ActorInitInfo& info);
> void trySyncStageSwitchAppearAndKill(LiveActor* actor);
> ```

returns `bool`
___
*[`lib/al/Project/Camera/CameraSubTargetTurnParam.h` line 10 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0JzFEs2lC8JYUDx1K8:-O0JzFEtClWZmzlEoBi5:bn0nf9w) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c9c39fca4d5d4f738f5bdf33552a9eddadd0965f/lib/al/Project/Camera/CameraSubTargetTurnParam.h#L10)):*
> ```objc
> class CameraSubTargetTurnParam {
> public:
>     CameraSubTargetTurnParam(){};
> ```

No semicolon at the end of the line

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)* status: all files reviewed, 3 unresolved discussions (waiting on @GRAnimated and @MonsterDruide1)

___
*[`lib/al/Library/LiveActor/ActorInitFunction.h` line 11 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0K-Esm3758GU8wZoFG:-O0KsSJ45uHuNOyNf8rZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c9c39fca4d5d4f738f5bdf33552a9eddadd0965f/lib/al/Library/LiveActor/ActorInitFunction.h#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

returns `bool`
</blockquote></details>

Done.
___
*[`lib/al/Project/Camera/CameraSubTargetTurnParam.h` line 10 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121#-O0JzFEs2lC8JYUDx1K8:-O0Kt8LI9Dp33eBwy4H5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/c9c39fca4d5d4f738f5bdf33552a9eddadd0965f/lib/al/Project/Camera/CameraSubTargetTurnParam.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No semicolon at the end of the line
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/121)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
