### PR TITLE
AllDeadWatcher functions

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `AllDeadWatcher` definition and it's implementation.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41)* status: all files reviewed, 5 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KLPy2n3i_QSh8C9O:-Ny5KLPy2n3i_QSh8C9P:bde6lul) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L3)):*
> ```objc
> #pragma once
> 
> #include "Library/LiveActor/LiveActor.h"
> ```

Forward-declare instead of including
___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KSA_4c4wxQKcQw7j:-Ny5KSA_4c4wxQKcQw7k:bcmwg22) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L6)):*
> ```objc
> 
> namespace al {
> // bool isAlive(LiveActor const* actor);
> ```

Why is this commented?
___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KNeN7D1l6Epa4JsH:-Ny5KNeN7D1l6Epa4JsI:b-ma3obk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L7)):*
> ```objc
> namespace al {
> // bool isAlive(LiveActor const* actor);
> void initActorSceneInfo(LiveActor* actor, ActorInitInfo const& info);
> ```

`const ActorInitInfo&`, same below
___
*[`lib/al/include/Library/LiveActor/ActorInitFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KZpmATqyT4y7j9Ty:-Ny5KZpmATqyT4y7j9Tz:bsi8rdp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorInitFunction.h#L3)):*
> ```objc
> #pragma once
> 
> #include "Library/LiveActor/LiveActor.h"
> ```

Forward-declare
___
*[`lib/al/src/Library/Obj/AllDeadWatcher.cpp` line 70 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5LoT_7QFpUngv91OE:-Ny5LoT_7QFpUngv91OF:bps2sjt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/src/Library/Obj/AllDeadWatcher.cpp#L70)):*
> ```cpp
> 
> void AllDeadWatcher::kill() {
>     LiveActor::kill();
> ```

... what was Nintendo thinking here? I mean, it's literally the entire function, but ... why???

**Comment by Fuzzy2319** [comment]
> _[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KLPy2n3i_QSh8C9O:-Ny5KLPy2n3i_QSh8C9P:bde6lul) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L3)):_
> 
> > ```objc
> > #pragma once
> > 
> > #include "Library/LiveActor/LiveActor.h"
> > ```
> 
> Forward-declare instead of including

It doesn't compile if I remove the include
image

> _[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KSA_4c4wxQKcQw7j:-Ny5KSA_4c4wxQKcQw7k:bcmwg22) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L6)):_
> 
> > ```objc
> > namespace al {
> > // bool isAlive(LiveActor const* actor);
> > ```
> 
> Why is this commented?

At some point I got a linking error (redefinition of already declared function) so I commented it, but now it would like to compile without errors (I don't know why) so I will uncomment it.

> 
> _[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KNeN7D1l6Epa4JsH:-Ny5KNeN7D1l6Epa4JsI:b-ma3obk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L7)):_
> 
> > ```objc
> > namespace al {
> > // bool isAlive(LiveActor const* actor);
> > void initActorSceneInfo(LiveActor* actor, ActorInitInfo const& info);
> > ```
> 
> `const ActorInitInfo&`, same below

What is the consensus here? In the function map it's written as `T const&`

> _[`lib/al/src/Library/Obj/AllDeadWatcher.cpp` line 70 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5LoT_7QFpUngv91OE:-Ny5LoT_7QFpUngv91OF:bps2sjt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/src/Library/Obj/AllDeadWatcher.cpp#L70)):_
> 
> > ```c++
> > void AllDeadWatcher::kill() {
> >     LiveActor::kill();
> > ```
> 
> ... what was Nintendo thinking here? I mean, it's literally the entire function, but ... why???

I don't know.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41)* status: all files reviewed, 4 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 3 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KLPy2n3i_QSh8C9O:-Ny9mC7cBFckK8MlQftm:b-antb6m) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L3)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

It doesn't compile if I remove the include
image

</blockquote></details>

Looks like you were looking at the wrong class? This annotation is on `ActorDrawFunction.h`, the error you show should only happen when removing the include from `AllDeadWatcher.h` - which should be kept, only remove it here.
___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 6 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KSA_4c4wxQKcQw7j:-Ny9mOF85ZWhHi1f0oLy:b1uuy20) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L6)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

At some point I got a linking error (redefinition of already declared function) so I commented it, but now it would like to compile without errors (I don't know why) so I will uncomment it.
</blockquote></details>

Maybe because you also defined it again in some `.cpp` class - it would definitely complain about that then, just declaring it (semicolon at the end instead of a function body) multiple times should be fine.
___
*[`lib/al/include/Library/LiveActor/ActorDrawFunction.h` line 7 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41#-Ny5KNeN7D1l6Epa4JsH:-Ny9mc79DNiShTSeCGIp:b5e1lyz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/794047d3aa1870046a209b5d1efb0a8a3890dde0/lib/al/include/Library/LiveActor/ActorDrawFunction.h#L7)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

What is the consensus here? In the function map it's written as `T const&`
</blockquote></details>

`const T&` is the standard way for this repo. The function map is different because that was dumped from IDA, which has a demangles the symbols with `T const&` instead - and nobody bothered to fix it in the function map.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
