### PR TITLE
Library/MapObj: Implement `FloaterMapParts`

### PR DESCRIPTION
**Pull request by Fuzzy2319**
This PR adds `FloaterMapParts` functions.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Please add it to the actor factory as well!

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-:-O5PIHQ12-lbJ2LiDf2g:bn6b7p1)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5PJXFA13u6gK161ETX:brvyfxu) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
> ```objc
>     f32 mSinkSpeed = 5.0f;
>     f32 mBackSpeed = 5.0f;
>     MoveType mMoveType = MoveType::Loop;
> ```

Where did you get this type from, why do you think it's the same here as in other classes? Especially because I only see the first two values occuring here.
___
*[`lib/al/Library/MapObj/FloaterMapParts.cpp` line 34 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PItxz3geYl47C5GUF:-O5PItxz3geYl47C5GUG:bxv8rnv) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.cpp#L34)):*
> ```cpp
>     initMapPartsActor(this, info, nullptr);
> 
>     tryGetQuatPtr(this);
> ```

Hmm. Interesting.
___
*[`lib/al/Library/MapObj/FloaterMapParts.cpp` line 126 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PKKyCE0mJoPV9nRDz:-O5PKKyCE0mJoPV9nRE-:bi3cd9u) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.cpp#L126)):*
> ```cpp
>         if (prevAccelCount > 0)
>             mAccelCount--;
>     } else {
> ```

I'd say switch these two branches, as that's also the order in which they would occur - first, do the sinking while changing coordinates, then (when reaching the bottom) start counting until moving back up.

**Review by Fuzzy2319 — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-:-O5UBa3C65uMt-38yLCp:b-896fix)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5UBlHxEMMKFXBGmrjG:bqgpgxw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Where did you get this type from, why do you think it's the same here as in other classes? Especially because I only see the first two values occuring here.
</blockquote></details>

I can't remember why I wrote this in first place a month ago.
___
*[`lib/al/Library/MapObj/FloaterMapParts.cpp` line 126 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PKKyCE0mJoPV9nRDz:-O5UDJE84zwXDjlHZ5KB:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.cpp#L126)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'd say switch these two branches, as that's also the order in which they would occur - first, do the sinking while changing coordinates, then (when reaching the bottom) start counting until moving back up.
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5UKmlw8jBGF3RYl503:b23lpwq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

I can't remember why I wrote this in first place a month ago.
</blockquote></details>

I don't think that it is the right type, its values/names don't even logically line up with what they are used for. If you don't find anything that clearly speaks against this, please change it to a new enum within this class.

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)* status: all files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5UVUsQ2SXQH5J5GumB:b2arju9) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I don't think that it is the right type, its values/names don't even logically line up with what they are used for. If you don't find anything that clearly speaks against this, please change it to a new enum within this class.
</blockquote></details>

Something like this?
```cpp
enum class FloaterMoveType : s32 { Wait, Back, Sink };
```

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5UkcLX3FFc0bGH_lMZ:bt1a8u1) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

Something like this?
```cpp
enum class FloaterMoveType : s32 { Wait, Back, Sink };
```
</blockquote></details>

Sounds about right? I'd need to verify in context, but this order seems correct.

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5gvm5vATf1_flqV8Uk:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Sounds about right? I'd need to verify in context, but this order seems correct.
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

___
*[`lib/al/Library/MapObj/FloaterMapParts.h` line 27 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/147#-O5PJXFA13u6gK161ETW:-O5ixECg7XpBlDCDvuit:b-1v456m) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/1c79691bb44c520e28b07940cce5a2b095635f26/lib/al/Library/MapObj/FloaterMapParts.h#L27)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, all of them look pretty sensible to me!

**Pull request merged**
