### PR TITLE
clean up various Execute headers

### PR DESCRIPTION
**Pull request by tetraxile**
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: all files reviewed, 3 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5SUPTGEp1lSuzb44T3:bxnys88) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
> ```objc
> private:
>     s32 mUpdateTableCount = 0;
>     s32 mUpdateTableMaxSize = 0;
> ```

Not sure, see comment below
___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUEx62PK4iiBz5fzK:-O5SUEx62PK4iiBz5fzL:bo8oll2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L40)):*
> ```objc
>     ExecuteTableHolderUpdate** mUpdateTables = nullptr;
>     s32 mDrawTableCount = 0;
>     s32 mDrawTableMaxSize = 0;
> ```

Seems to be unused - or am I missing something?
___
*[`lib/al/Library/Execute/ExecuteDirector.cpp` line 82 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SU-yW0vUYaAnQKTCu:-O5SU-yXCqURxhQUx7zD:b2xp0yp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.cpp#L82)):*
> ```cpp
> 
> void ExecuteDirector::registerUser(IUseExecutor* user, const char* listName) {
>     for (s32 i = 0; i < mUpdateTableMaxSize; i++)
> ```

I'm not convinced about this change yet. For `DrawTable`, it uses `Count`, but here `MaxSize`? That sounds wrong.

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: all files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5SWwqZ9L3_wdP2ySSS:b9k1f7f) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Not sure, see comment below
</blockquote></details>

swapping these around does make more sense as `MaxSize` would then be defined in the constructor, similarly to many other classes.
on another note, what do you think of the variable name itself: `mUpdateTableMaxSize`? it's not the maximum size of an update table, but rather the maximum number of update tables/the size of the buffer containing update tables. might a better name fit here? i know we previously discussed `Count`/`Num`/`No` variables in a discord thread and seemingly came up with "nintendo was inconsistent so we can be inconsistent too", but i'm not sure if we have an agreed upon convention for these maximum buffer size variables.
___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUEx62PK4iiBz5fzK:-O5SWS0V4zAR4IdhKt4j:b79ovpw) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L40)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Seems to be unused - or am I missing something?
</blockquote></details>

i put this here to match with the above `mUpdateTableMaxSize`, especially considering the class is almost entirely taken up by these two arrays so i'd expect them to be structured the same. that appears to be wrong though, based on the inconsistency of `Count` and `MaxSize` being used in the other functions.
___
*[`lib/al/Library/Execute/ExecuteDirector.cpp` line 82 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SU-yW0vUYaAnQKTCu:-O5SXRp17icyy0jNsZlO:bqh2k7x) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.cpp#L82)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'm not convinced about this change yet. For `DrawTable`, it uses `Count`, but here `MaxSize`? That sounds wrong.
</blockquote></details>

i think i agree. see above reply

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: all files reviewed, 2 unresolved discussions (waiting on @tetraxile)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5UJil94zP1X6LCyCVp:b58b2lj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

swapping these around does make more sense as `MaxSize` would then be defined in the constructor, similarly to many other classes.
on another note, what do you think of the variable name itself: `mUpdateTableMaxSize`? it's not the maximum size of an update table, but rather the maximum number of update tables/the size of the buffer containing update tables. might a better name fit here? i know we previously discussed `Count`/`Num`/`No` variables in a discord thread and seemingly came up with "nintendo was inconsistent so we can be inconsistent too", but i'm not sure if we have an agreed upon convention for these maximum buffer size variables.
</blockquote></details>

No, I don't think `MaxSize` and `Count` are even related to each other. `Count` is supposed to be something like `mMaxExecuteRequest`, while `MaxSize` is something with `mUpdateTable` - but still not really `MaxSize`, as the amount of `UpdateTable`s cannot be changed after the initial creation (or at all, really).

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: 15 of 17 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5V6WQ1EfohQqNf5cas:b-w8gvx5) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, I don't think `MaxSize` and `Count` are even related to each other. `Count` is supposed to be something like `mMaxExecuteRequest`, while `MaxSize` is something with `mUpdateTable` - but still not really `MaxSize`, as the amount of `UpdateTable`s cannot be changed after the initial creation (or at all, really).
</blockquote></details>

oh... right, that seems to make a lot more sense. fixed it.
___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUEx62PK4iiBz5fzK:-O5V6ZA4-dj9l6RE54HD:bt7vwcp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L40)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

i put this here to match with the above `mUpdateTableMaxSize`, especially considering the class is almost entirely taken up by these two arrays so i'd expect them to be structured the same. that appears to be wrong though, based on the inconsistency of `Count` and `MaxSize` being used in the other functions.
</blockquote></details>

done -- see above

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tetraxile)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5V9bRt600ZrkhKPQJm:bh8fjpt) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
<details><summary><i>Previously, tetraxile wrote…</i></summary><blockquote>

oh... right, that seems to make a lot more sense. fixed it.
</blockquote></details>

Lol, you changed everything back to what it was exactly before this PR. But yeah, seems like that is the most sensible naming.

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tetraxile)

___
*[`lib/al/Library/Execute/ExecuteDirector.h` line 37 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/150#-O5SUPTGEp1lSuzb44T2:-O5VA4wu-cj5ViqBrbz2:b-xgmcr4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e4cf41b71d863e407f6b5c226f91acc9c8e10d3c/lib/al/Library/Execute/ExecuteDirector.h#L37)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Lol, you changed everything back to what it was exactly before this PR. But yeah, seems like that is the most sensible naming.
</blockquote></details>

well hey at least we're sure of it now :p

**Pull request merged**
