### PR TITLE
`game/player`: Add `PlayerInfo`

### PR DESCRIPTION
**Pull request by OatmealDome**
I believe I got all of the fields right...

---
This change is [Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @OatmealDome)

___
*[lib/game/player/PlayerInfo.h, line 51 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55upE8ld6xV2FoPX5:-Mt55upE8ld6xV2FoPX6:b-6lhd2q) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L51)):*
> ```objc
> public:
>     PlayerInfo();
> ```

`private:`
___
*[lib/game/player/PlayerInfo.h, line 93 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55xHW0X6c4FjiL8S0:-Mt55xHW0X6c4FjiL8S1:b-7emet5) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L93)):*
> ```objc
>     PlayerJudgeEnableGuideArrow* mPlayerJudgeEnableGuideArrow = nullptr;
>     PlayerJudgeEnablePeachAmiibo* mPlayerJudgeEnablePeachAmiibo = nullptr;
>     bool mIsMoon;
> ```

This one does not have a default value?
___
*[src/game/player/PlayerInfo.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt56GO23jRxK32Amwcd:-Mt56GO23jRxK32Amwce:bak2ml9) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L3)):*
> ```cpp
> #include "game/player/PlayerInfo.h"
> 
> #include <string.h>
> ```

This include seems redundant.
___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-Mt565RJ935270cqLCLp:bc5unfn) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
> ```cpp
> 
> PlayerInfo::PlayerInfo() {
>     memset(this, 0, 0x149);
> ```

If the default values in the header are chosen correctly, clang should automatically generate a statement like this. Just use the `= default;` constructor and tweak the header until it matches.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @OatmealDome)

___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-MvLP9Zy859QELl2Bler:be1sa1s) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If the default values in the header are chosen correctly, clang should automatically generate a statement like this. Just use the `= default;` constructor and tweak the header until it matches.
</blockquote></details>

If I change the constructor declaration in the header to ``PlayerInfo() = default;`` and remove the implementation, it seems that the constructor ceases to exist in the compiled binary since I get the error "`unknown function: _ZN10PlayerInfoC2Ev`"  Not sure if I'm doing something wrong.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @OatmealDome)

___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-MvLPxN9At2wXTZSYtsH:bwcrcnz) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

If I change the constructor declaration in the header to ``PlayerInfo() = default;`` and remove the implementation, it seems that the constructor ceases to exist in the compiled binary since I get the error "`unknown function: _ZN10PlayerInfoC2Ev`"  Not sure if I'm doing something wrong.
</blockquote></details>

There's sometimes weirdness going on with the indexing of constructors/destructors, so maybe check for `_ZN10PlayerInfoC1Ev` as well.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1 and @OatmealDome)

___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-MvLbQIq2r6DvMVixcjz:blwydj0) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

There's sometimes weirdness going on with the indexing of constructors/destructors, so maybe check for `_ZN10PlayerInfoC1Ev` as well.
</blockquote></details>

I still get the same error ("unknown function") with ``C1``, unfortunately.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: all files reviewed, 4 unresolved discussions (waiting on @OatmealDome)

___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-MvLcisB3kubywEt1273:br4dyt4) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

I still get the same error ("unknown function") with ``C1``, unfortunately.
</blockquote></details>

Ahh, I see the issue now!
You still have to put the implementation with `= default;` into the `cpp`, otherwise it will not show up in the compiled binary, as it will be inlined for every usage instead.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 0 of 6 files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[lib/game/player/PlayerInfo.h, line 51 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55upE8ld6xV2FoPX5:-MvLkdmPCzsYPxmyR6VX:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L51)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`private:`
</blockquote></details>

Done.
___
*[lib/game/player/PlayerInfo.h, line 93 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55xHW0X6c4FjiL8S0:-MvLkdUICL2Wj75QkfPy:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L93)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This one does not have a default value?
</blockquote></details>

Done.
___
*[src/game/player/PlayerInfo.cpp, line 3 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt56GO23jRxK32Amwcd:-MvLkcxB-94tq91Kjq9a:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This include seems redundant.
</blockquote></details>

Done.
___
*[src/game/player/PlayerInfo.cpp, line 6 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt565RJ935270cqLCLo:-MvLkjr8Ed5a8xSdESVY:bcstya4) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/src/game/player/PlayerInfo.cpp#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ahh, I see the issue now!
You still have to put the implementation with `= default;` into the `cpp`, otherwise it will not show up in the compiled binary, as it will be inlined for every usage instead.
</blockquote></details>

Yep, that did it! Thanks.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: all files reviewed, 1 unresolved discussion (waiting on @OatmealDome)

___
*[lib/game/player/PlayerInfo.h, line 51 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55upE8ld6xV2FoPX5:-MvNXprQDVsycXCgDipy:bubarbi) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L51)):*
<details><summary><i>Previously, OatmealDome wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, the constructor should be `public:` and all member variables `private:`.

**Review by OatmealDome — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[lib/game/player/PlayerInfo.h, line 51 at r1](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-Mt55upE8ld6xV2FoPX5:-MvRdAS48HqtnTXeCrZl:b-896fix) ([raw file](https://github.com/monsterdruide1/odysseydecomp/blob/17eb670dadf0f170c4102ac1057eb91e9d7a0c86/lib/game/player/PlayerInfo.h#L51)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

No, the constructor should be `public:` and all member variables `private:`.
</blockquote></details>

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OatmealDome)

**Review by MonsterDruide1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/monsterdruide1/odysseydecomp/8#-:-MvTFmc82boBTrpmCxA5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @OatmealDome)

**Pull request merged**
