### PR TITLE
Actor: BarrierField

### PR DESCRIPTION
**Pull request by LynxDev2**
Implements all functions for the barrier actor used in boss battles with The Broodals

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: all files reviewed, 5 unresolved discussions (waiting on @LynxDev2)

___
*[`lib/al/Library/Nerve/NerveSetupUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8IkWDXnE8N3YL--7:-O-M8IkWDXnE8N3YL--8:b1bbnpa) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/lib/al/Library/Nerve/NerveSetupUtil.h#L36)):*
> ```objc
>         }                                                                                          \
>                                                                                                    \
>         const char* getActionName() const { return #Action; }                                      \
> ```

Might cause the four `getActionName` functions to match? (will be inlined otherwise)



_Suggestion:_
```objc
virtual const char* getActionName() const { return #Action; }
```
___
*[`src/MapObj/BarrierField.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8W9FBXcqtKaoBKhn:-O-M8W9FBXcqtKaoBKho:b-5djig6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.h#L25)):*
> ```objc
> private:
>     bool mIsDisappearByShineGet = false;
>     bool mIsOnTheMoon = false;
> ```

Shorter name to align with other, similar names throughout the game



_Suggestion:_
```objc
bool mIsMoon = false;
```
___
*[`src/MapObj/BarrierField.cpp` line 30 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M9HDyDMq0F4OPc9Qy:-O-M9HDyDMq0F4OPc9Qz:b3atrr2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.cpp#L30)):*
> ```cpp
>     NERVE_MAKE(BarrierField, Hide);
>     NERVE_MAKE(BarrierField, Disappear);
>     void* padding[4];
> ```

`sub_710000A098` explains this gap. The entire function seems like it could be another macro, not sure about it yet though. This function is referenced in the `.init_array` section, so it is some kind of initializer that is called before the program even starts.
___
*[`src/MapObj/BarrierField.cpp` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-MA-VX8qPPIwqCGgQG:-O-MA-VX8qPPIwqCGgQH:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.cpp#L45)):*
> ```cpp
>     if (al::isObjectName(initInfo, "WaterfallWorldHomeBarrier")) {
>         GameDataHolderAccessor dataAccessor(this);
>         if (GameDataFunction::isWorldMoon(dataAccessor))
> ```





_Suggestion:_
```cpp
        if (GameDataFunction::isWorldMoon(this))
```
___
*[`src/Util/StageSceneFunction.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M88tx4eYkPN62aUB0:-O-M88tx4eYkPN62aUB1:bwrsjic) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/Util/StageSceneFunction.h#L12)):*
> ```objc
> 
> class IJudge;
> class BarrierField;
> ```

Useless?

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: 2 of 7 files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Nerve/NerveSetupUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8IkWDXnE8N3YL--7:-O-MD5xmBOrtrlQCYWva:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/lib/al/Library/Nerve/NerveSetupUtil.h#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Might cause the four `getActionName` functions to match? (will be inlined otherwise)
</blockquote></details>

Done.
___
*[`src/MapObj/BarrierField.h` line 25 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8W9FBXcqtKaoBKhn:-O-MDBvM13BICg4CiqlH:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.h#L25)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Shorter name to align with other, similar names throughout the game
</blockquote></details>

Done.
___
*[`src/MapObj/BarrierField.cpp` line 30 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M9HDyDMq0F4OPc9Qy:-O-MDEaH8tQxjoVhZkDf:bcy29g3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.cpp#L30)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`sub_710000A098` explains this gap. The entire function seems like it could be another macro, not sure about it yet though. This function is referenced in the `.init_array` section, so it is some kind of initializer that is called before the program even starts.
</blockquote></details>

interesting
___
*[`src/MapObj/BarrierField.cpp` line 45 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-MA-VX8qPPIwqCGgQG:-O-MDjUkBcBJVjdu3yOC:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/MapObj/BarrierField.cpp#L45)):*
> ```cpp
>     if (al::isObjectName(initInfo, "WaterfallWorldHomeBarrier")) {
>         GameDataHolderAccessor dataAccessor(this);
>         if (GameDataFunction::isWorldMoon(dataAccessor))
> ```

Done.
___
*[`src/Util/StageSceneFunction.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M88tx4eYkPN62aUB0:-O-MDqEn7wZ91jJ3Q2l5:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/src/Util/StageSceneFunction.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless?
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @LynxDev2)

___
*[`lib/al/Library/Nerve/NerveSetupUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8IkWDXnE8N3YL--7:-O-QrCt4Ezc1ijJ1KlXq:bireh2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/lib/al/Library/Nerve/NerveSetupUtil.h#L36)):*
<details><summary><i>Previously, LynxDev2 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Actually, it's something entirely different. Blocked by #91, then this can be rebased and use the new macros.

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: 3 of 7 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Nerve/NerveSetupUtil.h` line 36 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-M8IkWDXnE8N3YL--7:-O-WF2wX-PJfPCYhZYh8:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/26ba1f9fc4d4c4a63eb81cca41cb87ca27a9c104/lib/al/Library/Nerve/NerveSetupUtil.h#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Actually, it's something entirely different. Blocked by #91, then this can be rebased and use the new macros.
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: all files reviewed, 2 unresolved discussions (waiting on @LynxDev2)

___
*[`data/odyssey_functions.csv` line 0 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHTrH-H-qK0QnF_wv:-O-WHTrH-H-qK0QnF_ww:b8ygs4f) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/data/odyssey_functions.csv#L0)):*
Assign a name to `710000a098` according to `tools/listsym` to get an additional match

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: all files reviewed, 4 unresolved discussions (waiting on @LynxDev2)

___
*[`src/MapObj/BarrierField.h` line 6 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHmJS5bONllNEuhca:-O-WHmJS5bONllNEuhcb:bj4xyla) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.h#L6)):*
> ```objc
> 
> namespace al {
> class LiveActor;
> ```

Useless forward-declare (already included + has to be included due to inheritance)
___
*[`src/MapObj/BarrierField.cpp` line 17 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHu_83tDluviKuynS:-O-WHu_83tDluviKuynT:b-42k4bn) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.cpp#L17)):*
> ```cpp
> namespace alNerveFunction {
> class NerveActionCollector;
> }
> ```

Useless forward-declare



_Code quote:_
```cpp
namespace alNerveFunction {
class NerveActionCollector;
}
```
___
*[`src/MapObj/BarrierField.cpp` line 38 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WI1OoDq3JPMZvhMXf:-O-WI1OoDq3JPMZvhMXg:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.cpp#L38)):*
> ```cpp
>         if (GameDataFunction::isWorldMoon(this))
>             mIsMoon = true;
>     }
> ```





_Suggestion:_
```cpp
    if (al::isObjectName(initInfo, "WaterfallWorldHomeBarrier") && GameDataFunction::isWorldMoon(this))
            mIsMoon = true;
```

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: all files reviewed, 4 unresolved discussions (waiting on @MonsterDruide1)

___
*[`data/odyssey_functions.csv` line  at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHTrH-H-qK0QnF_wv:-O-WQQXZEjlyqNvX1tyZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/data/odyssey_functions.csv#L)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Assign a name to `710000a098` according to `tools/listsym` to get an additional match
</blockquote></details>

Done.
___
*[`src/MapObj/BarrierField.h` line 6 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHmJS5bONllNEuhca:-O-WQYr9B82_Sb3i7x5G:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.h#L6)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless forward-declare (already included + has to be included due to inheritance)
</blockquote></details>

Done.
___
*[`src/MapObj/BarrierField.cpp` line 17 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WHu_83tDluviKuynS:-O-WQgru5qKpVboe-8JM:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.cpp#L17)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless forward-declare
</blockquote></details>

Done.
___
*[`src/MapObj/BarrierField.cpp` line 38 at r4](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90#-O-WI1OoDq3JPMZvhMXf:-O-WQi22CEH38UgoSRo2:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/b716588ef7c63e2e583c96227052072f71d73c24/src/MapObj/BarrierField.cpp#L38)):*
> ```cpp
>         if (GameDataFunction::isWorldMoon(this))
>             mIsMoon = true;
>     }
> ```

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/90)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

**Pull request merged**
