### PR TITLE
Base: Rename files to HashCodeUtil and StringUtil

### PR DESCRIPTION
**Pull request by GRAnimated**
These names better match the the rest of the function map.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)

### CODE REVIEW

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: all files reviewed, 1 unresolved discussion (waiting on @GRAnimated)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNKc1B5wzNkjkQWZ0S:-NzNKc1C8JPmLnDG8gb6:b-pz53a) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/68f549f2d9f2af0717be7613669ed7351c310143/lib/al/src/Library/Base/HashCodeUtil.cpp#L8)):*
> ```cpp
> 
> namespace al {
> s32 calcHashCode(char const* hash) {
> ```

We should change all these `char const*` to `const char*` in order to follow the code style of the repo.
This didn't come up in the first place when I wrote this and I forgot about it.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: all files reviewed, 2 unresolved discussions (waiting on @Fuzzy2319 and @GRAnimated)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNKc1B5wzNkjkQWZ0S:-NzNRmay2NDk2TnSekEF:b-6hdxtg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/68f549f2d9f2af0717be7613669ed7351c310143/lib/al/src/Library/Base/HashCodeUtil.cpp#L8)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

We should change all these `char const*` to `const char*` in order to follow the code style of the repo.
This didn't come up in the first place when I wrote this and I forgot about it.
</blockquote></details>

Ah, yes... agreed. We should also introduce a new linter check for this.
___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNRjrABahVDQ22L3Jr:-NzNRjrABahVDQ22L3Js:bmeuhvd) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/5e6180b48f83712fd52ebd363103065b77be77be/lib/al/src/Library/Base/HashCodeUtil.cpp#L11)):*
> ```cpp
>     if (str[0] == '\0') {
>         return 0;
>     }
> ```

Can be removed, as this should be handled by the loop below



_Code quote:_
```cpp
    if (str[0] == '\0') {
        return 0;
    }
```

**Review by Fuzzy2319 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: all files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNRjrABahVDQ22L3Jr:-NzNS_-K3oOoY_Yb-JlV:bt84ca4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/5e6180b48f83712fd52ebd363103065b77be77be/lib/al/src/Library/Base/HashCodeUtil.cpp#L11)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Can be removed, as this should be handled by the loop below
</blockquote></details>

The function doesn't match without we already talk about it here.
https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooQ_k2eIi1i3aXJIE

**Review by MonsterDruide1 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNRjrABahVDQ22L3Jr:-NzNTNRZDjBYrTEE-BTa:bw8m0aa) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/5e6180b48f83712fd52ebd363103065b77be77be/lib/al/src/Library/Base/HashCodeUtil.cpp#L11)):*
<details><summary><i>Previously, Fuzzy2319 wrote…</i></summary><blockquote>

The function doesn't match without we already talk about it here.
https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/35#-NwooQ_k2eIi1i3aXJIE
</blockquote></details>

Ah, true. Nevermind then, thanks.

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNKc1B5wzNkjkQWZ0S:-NzOvce-BrX6mq9YPIQt:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/68f549f2d9f2af0717be7613669ed7351c310143/lib/al/src/Library/Base/HashCodeUtil.cpp#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Ah, yes... agreed. We should also introduce a new linter check for this.
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: all files reviewed, 1 unresolved discussion (waiting on @Fuzzy2319)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNKc1B5wzNkjkQWZ0S:-NzPLgqeAetFaMiL_Rhm:b2gwfi4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/68f549f2d9f2af0717be7613669ed7351c310143/lib/al/src/Library/Base/HashCodeUtil.cpp#L8)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You did other ones, but apparently not the line we have annotated!

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`lib/al/src/Library/Base/HashCodeUtil.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55#-NzNKc1B5wzNkjkQWZ0S:-NzPM2YP8gIln4Gadals:b-fsklbz) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/68f549f2d9f2af0717be7613669ed7351c310143/lib/al/src/Library/Base/HashCodeUtil.cpp#L8)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

You did other ones, but apparently not the line we have annotated!
</blockquote></details>

Oops! include/source for al messed me up

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/55)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
