### PR TITLE
Layout: Implement `MenuSelectParts`

### PR DESCRIPTION
**Pull request by GRAnimated**
This PR adds in `MenuSelectParts`, which controls all of the behavior for the buttons on the main menu & pause menu.

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Only partial review in the 5 minutes I had, will continue later

> Reviewed 5 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-:-O0IbtVAC5VLIaH8iD2G:b-2qeq4r)* status: 5 of 12 files reviewed, 2 unresolved discussions (waiting on @GRAnimated)

___
*[`lib/al/Library/Controller/KeyRepeatCtrl.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0IbfmG-G3dc49pD4Eo:-O0IbfmG-G3dc49pD4Ep:b-orcl4q) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a01a1163bbe1ddde97aa3833324dbda942f8c7fb/lib/al/Library/Controller/KeyRepeatCtrl.h#L10)):*
> ```objc
>     KeyRepeatCtrl();
> 
>     void init(s32, s32);
> ```

Parameter names? I guess it would just be two of the member variables?
___
*[`lib/al/Library/Controller/KeyRepeatCtrl.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ibm8f6KjnZWrnFfJl:-O0Ibm8f6KjnZWrnFfJm:b-78ymr8) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a01a1163bbe1ddde97aa3833324dbda942f8c7fb/lib/al/Library/Controller/KeyRepeatCtrl.h#L12)):*
> ```objc
>     void init(s32, s32);
>     void reset();
>     void update(bool, bool);
> ```

Parameter names

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: 4 of 12 files reviewed, 2 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Controller/KeyRepeatCtrl.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0IbfmG-G3dc49pD4Eo:-O0If6pO60uTarzp75A0:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a01a1163bbe1ddde97aa3833324dbda942f8c7fb/lib/al/Library/Controller/KeyRepeatCtrl.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Parameter names? I guess it would just be two of the member variables?
</blockquote></details>

Done.
___
*[`lib/al/Library/Controller/KeyRepeatCtrl.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ibm8f6KjnZWrnFfJl:-O0If71mBRyH8nPyg2gT:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a01a1163bbe1ddde97aa3833324dbda942f8c7fb/lib/al/Library/Controller/KeyRepeatCtrl.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Parameter names
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Another partial bit

> Reviewed 1 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-:-O0JOm-A1DNpc4v0I4Of:b-qn2cxg)* status: 6 of 12 files reviewed, 2 unresolved discussions (waiting on @GRAnimated)

___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 21 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JNHHT0Ghd_UmjVvcc:-O0JNHHU7zo5hNKA3TbZ:b-440r8f) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L21)):*
> ```objc
>         field_1C = _1C;
>         field_1D = _1D;
>     }
> ```

initializer list



_Code quote:_
```objc
    PadRumbleParam(f32 _0, f32 _4, f32 _8, f32 _c, f32 _10, f32 _14, s32 _18, bool _1C, bool _1D) {
        field_0 = _0;
        field_4 = _4;
        field_8 = _8;
        field_c = _c;
        field_10 = _10;
        field_14 = _14;
        field_18 = _18;
        field_1C = _1C;
        field_1D = _1D;
    }
```
___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 71 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JOTKV1_ynOG8VTWGR:-O0JOTKW08SPhyets0Rn:bjui3px) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L71)):*
> ```objc
> void stopPadRumbleLoop(const al::LiveActor*, const char*, const sead::Vector3f*, s32);
> void checkIsAlivePadRumbleLoop(al::PadRumbleDirector*, const char*, const sead::Vector3f*, s32);
> void checkIsAlivePadRumbleLoop(const al::LiveActor*, const char*, const sead::Vector3f*, s32);
> ```

return type: bool



_Code quote:_
```objc
void checkIsAlivePadRumbleLoop(al::PadRumbleDirector*, const char*, const sead::Vector3f*, s32);
void checkIsAlivePadRumbleLoop(const al::LiveActor*, const char*, const sead::Vector3f*, s32);
```

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: all files reviewed, 15 unresolved discussions (waiting on @GRAnimated)

___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jw4wSDeolZszkcA8F:-O0Jw4wSDeolZszkcA8G:b-l0x0tg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L32)):*
> ```objc
>     s32 field_18;
>     bool field_1C;
>     bool field_1D;
> ```

I currently have this:
```cpp
struct al::PadRumbleParam
{
  float mRumbleNear;
  float mRumbleFar;
  float mRumbleVolume;
  float mRumblePitchVol;
  float mRumblePitchLeft;
  float mRumblePitchRight;
  int _18;
  bool isUseController_1C;
  bool _1D;
};
```



_Code quote:_
```objc
    f32 field_0;
    f32 field_4;
    f32 field_8;
    f32 field_c;
    f32 field_10;
    f32 field_14;
    s32 field_18;
    bool field_1C;
    bool field_1D;
```
___
*[`lib/al/Library/Se/SeFunction.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jy8iu6FdNjBrPN2ri:-O0Jy8iu6FdNjBrPN2rj:bdmv2sb) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L35)):*
> ```objc
> void stopSeWithoutFreezed(const IUseAudioKeeper*, const sead::SafeString&, s32, const char*);
> bool tryStopSe(const IUseAudioKeeper*, const sead::SafeString&, s32, const char*);
> bool tryStopAllSeFromUser(const IUseAudioKeeper*, s32, const char*);
> ```

This one is `void`. Yeah, no idea either.
___
*[`lib/al/Library/Se/SeFunction.h` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JyJZW0tKllFg7NylI:-O0JyJZW0tKllFg7NylJ:bbzmnnc) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L38)):*
> ```objc
> void stopAllSeFromUser(const IUseAudioKeeper*, s32, const char*);
> bool isPlayingAnySe(const IUseAudioKeeper*, const char*);
> void checkIsPlayingSe(const IUseAudioKeeper*, const sead::SafeString&, const char*);
> ```

Returns `bool`
___
*[`lib/al/Library/Se/SeFunction.h` line 49 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JyaoO57beWqKwd3Vz:-O0JyaoO57beWqKwd3W-:bsv6lri) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L49)):*
> ```objc
> void setSeEmitterPoseMtxPtr(const IUseAudioKeeper*, const sead::Matrix34f*, const char*);
> void setSeEmitterPosePosPtr(const IUseAudioKeeper*, const sead::Vector3f*, const char*);
> bool tryUpdateSeMaterialCode(IUseAudioKeeper*, const char*);
> ```

returns `void`
___
*[`src/Layout/MenuSelectParts.h` line 3 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jqs7u1ADy1Xo6pLjU:-O0Jqs7u1ADy1Xo6pLjV:b-wq09st) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L3)):*
> ```objc
> #pragma once
> 
> #include <container/seadPtrArray.h>
> ```

Useless include
___
*[`src/Layout/MenuSelectParts.h` line 55 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JrPKzBqQ-exXQgEnq:-O0JrPKzBqQ-exXQgEnr:b-n9bs6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L55)):*
> ```objc
>     s32 mCursorItemIndex = 0;
>     s32 mMax;
>     s32 mCount;
> ```

Never used afterwards?
___
*[`src/Layout/MenuSelectParts.h` line 58 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JragZ3kKg2RAXZ5Jd:-O0JragZ3kKg2RAXZ5Je:b-toq3b7) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L58)):*
> ```objc
>     al::LayoutActor** mLayoutArray = nullptr;
>     al::LayoutActor* mCursorActor = nullptr;
>     s32 field_38 = 0;
> ```

`mDefaultIndex`
___
*[`src/Layout/MenuSelectParts.cpp` line 36 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JtmkqAnvetGUkGrqI:-O0JtmkqAnvetGUkGrqJ:b-43tkg4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L36)):*
> ```cpp
> 
> const s32 mainMenuParts[5] = {0, 1, 2, 3, 5};
> const s32 pauseMenuParts[8] = {0, 1, 3, 4, 5, 0, 0, 0};
> ```

I'd say this is only `[5]`, the remainder is padding. If you look at the calls to `appear`, it always gets `5` as parameter for the number of entries, so anything further than the `5` in here cannot be used.
___
*[`src/Layout/MenuSelectParts.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ju2H6EXUW66G_R6dL:-O0Ju2H6EXUW66G_R6dM:b-r0vaxj) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L38)):*
> ```cpp
> const s32 pauseMenuParts[8] = {0, 1, 3, 4, 5, 0, 0, 0};
> 
> const s32* getPartsArray(bool isPauseMenu, s32 selection) {
> ```

Make this (and everything around it) an `enum class`?
___
*[`src/Layout/MenuSelectParts.cpp` line 181 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JsVboDRjkkXi98QcR:-O0JsVboDRjkkXi98QcS:b83pwmp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L181)):*
> ```cpp
> s32 MenuSelectParts::calcPartsIndex(s32 selection) const {
>     bool isPauseMenu = !mIsMainMenu;
>     return getPartsArray(isPauseMenu, selection)[selection];
> ```

Does this mismatch?



_Suggestion:_
```cpp
    return getPartsArray(!mIsMainMenu, selection)[selection];
```
___
*[`src/Layout/MenuSelectParts.cpp` line 243 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JugEU27k483ew_tEI:-O0JugEU27k483ew_tEJ:bwbrzdk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L243)):*
> ```cpp
> 
>         f32 pitch = ((1.0f - (f32)mCursorItemIndex / (mMenuItemAmount - 1)) * 0.375f) + 1.0f;
>         al::PadRumbleParam param = {0.0f, 3000.0f, 1.0f, 1.0f, 1.0f, 1.0f, 0, 0, 0};
> ```

This seems to be an inline (header) default constructor, because it's inlined like this everywhere.
___
*[`src/Layout/MenuSelectParts.cpp` line 309 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JwpG01iYNN_Ztzoam:-O0JwpG01iYNN_Ztzoan:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L309)):*
> ```cpp
>         if (calcPartsIndex(mCursorItemIndex) == 4 || calcPartsIndex(mCursorItemIndex) == 5)
>             return true;
>     }
> ```





_Suggestion:_
```cpp
    if (rs::isSceneStatusInvalidSave(mLayoutActor) && (calcPartsIndex(mCursorItemIndex) == 4 || calcPartsIndex(mCursorItemIndex) == 5))
            return true;
```
___
*[`src/Util/StageInputFunction.h` line 77 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JxQl77kAv1-ot821M:-O0JxQl77kAv1-ot821N:b-2lqpqm) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Util/StageInputFunction.h#L77)):*
> ```objc
> bool tryReconnectGamePad(al::GamePadSystem*);
> void connectControllerSinglePlay(al::GamePadSystem*);
> void connectControllerSeparatePlay(al::GamePadSystem*);
> ```

return `bool`s



_Code quote:_
```objc
void connectControllerSinglePlay(al::GamePadSystem*);
void connectControllerSeparatePlay(al::GamePadSystem*);
```

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: all files reviewed, 15 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 21 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JNHHT0Ghd_UmjVvcc:-O0KY66A1HX3sfuAz-wA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L21)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

initializer list
</blockquote></details>

Done.
___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jw4wSDeolZszkcA8F:-O0KYJsA0UpA-nTBAMYU:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L32)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I currently have this:
```cpp
struct al::PadRumbleParam
{
  float mRumbleNear;
  float mRumbleFar;
  float mRumbleVolume;
  float mRumblePitchVol;
  float mRumblePitchLeft;
  float mRumblePitchRight;
  int _18;
  bool isUseController_1C;
  bool _1D;
};
```
</blockquote></details>

Done.
___
*[`lib/al/Library/Controller/PadRumbleFunction.h` line 71 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JOTKV1_ynOG8VTWGR:-O0KY_1YBwOjA1l1sQOK:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Controller/PadRumbleFunction.h#L71)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

return type: bool
</blockquote></details>

Done.
___
*[`lib/al/Library/Se/SeFunction.h` line 35 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jy8iu6FdNjBrPN2ri:-O0KZLw-5hSGetec0-ij:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L35)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This one is `void`. Yeah, no idea either.
</blockquote></details>

Done.
___
*[`lib/al/Library/Se/SeFunction.h` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JyJZW0tKllFg7NylI:-O0KZNUbA4F9xuURPGwv:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Returns `bool`
</blockquote></details>

Done.
___
*[`lib/al/Library/Se/SeFunction.h` line 49 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JyaoO57beWqKwd3Vz:-O0KZQ1-BS6SnMVQL5GA:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/lib/al/Library/Se/SeFunction.h#L49)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

returns `void`
</blockquote></details>

Done.
___
*[`src/Layout/MenuSelectParts.h` line 3 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Jqs7u1ADy1Xo6pLjU:-O0KZU0YAiv90_1ik_xZ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L3)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Useless include
</blockquote></details>

Done.
___
*[`src/Layout/MenuSelectParts.h` line 55 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JrPKzBqQ-exXQgEnq:-O0KZfxk4NI59y8foxLi:bwqrvd2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L55)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Never used afterwards?
</blockquote></details>

Got rid of it.
___
*[`src/Layout/MenuSelectParts.h` line 58 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JragZ3kKg2RAXZ5Jd:-O0KZsGG5xZOT7W8N9Wg:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.h#L58)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`mDefaultIndex`
</blockquote></details>

Done.
___
*[`src/Layout/MenuSelectParts.cpp` line 36 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JtmkqAnvetGUkGrqI:-O0KZuy-6mGjqdZ-Riv0:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L36)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'd say this is only `[5]`, the remainder is padding. If you look at the calls to `appear`, it always gets `5` as parameter for the number of entries, so anything further than the `5` in here cannot be used.
</blockquote></details>

Done.
___
*[`src/Layout/MenuSelectParts.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ju2H6EXUW66G_R6dL:-O0KbGL_AThgoV5wmJjA:b-vld33h) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Make this (and everything around it) an `enum class`?
</blockquote></details>

Created an enum in the header named `Selection`.
___
*[`src/Layout/MenuSelectParts.cpp` line 181 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JsVboDRjkkXi98QcR:-O0KbRPR9F8TLyyjW8FT:b-wqg5vy) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L181)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Does this mismatch?
</blockquote></details>

Creates mismatches on every function that uses this inlined.
___
*[`src/Layout/MenuSelectParts.cpp` line 243 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JugEU27k483ew_tEI:-O0KcAZT5IkjNK6RecNH:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L243)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

This seems to be an inline (header) default constructor, because it's inlined like this everywhere.
</blockquote></details>

Done.
___
*[`src/Layout/MenuSelectParts.cpp` line 309 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JwpG01iYNN_Ztzoam:-O0KcSFVBEfQfdFcCYoQ:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L309)):*
> ```cpp
>         if (calcPartsIndex(mCursorItemIndex) == 4 || calcPartsIndex(mCursorItemIndex) == 5)
>             return true;
>     }
> ```

Done.
___
*[`src/Util/StageInputFunction.h` line 77 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0JxQl77kAv1-ot821M:-O0KcWEQ4QuWLNMimVyY:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Util/StageInputFunction.h#L77)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

return `bool`s
</blockquote></details>

Done.

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: all files reviewed, 3 unresolved discussions (waiting on @GRAnimated)

___
*[`src/Layout/MenuSelectParts.h` line 14 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0TA_OkBTeKoRsRwqOY:-O0TA_OkBTeKoRsRwqOZ:b-xztaro) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a5885f7e46ccbfe790ad289c2889dc5a75fb64e1/src/Layout/MenuSelectParts.h#L14)):*
> ```objc
> class MenuSelectParts : public al::NerveExecutor {
> public:
>     enum Selection : s32 {
> ```

Should be `enum class`
___
*[`src/Layout/MenuSelectParts.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ju2H6EXUW66G_R6dL:-O0TAbTb7Sm_NpMN0dWh:b-fhjiwg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L38)):*
<details><summary><i>Previously, GRAnimated wrote…</i></summary><blockquote>

Created an enum in the header named `Selection`.
</blockquote></details>

Make this return the `enum class` value instead of raw `s32`s (and adjust other things accordingly)?

**Review by GRAnimated — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: all files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/Layout/MenuSelectParts.h` line 14 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0TA_OkBTeKoRsRwqOY:-O1wXtld6FF99eUFVhJF:b-f44wv2) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/a5885f7e46ccbfe790ad289c2889dc5a75fb64e1/src/Layout/MenuSelectParts.h#L14)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Should be `enum class`
</blockquote></details>

Resolved in discord, not changing
___
*[`src/Layout/MenuSelectParts.cpp` line 38 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120#-O0Ju2H6EXUW66G_R6dL:-O1wXwVrACaKo4HbjRKZ:b9f127s) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/01cda4f6ebbe706fb4ca5b76674273946b15e40b/src/Layout/MenuSelectParts.cpp#L38)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Make this return the `enum class` value instead of raw `s32`s (and adjust other things accordingly)?
</blockquote></details>

Resolved in discord, adjusted what was wanted

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/120)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @GRAnimated)

**Pull request merged**
