### PR TITLE
ApplicationMessageReceiver functions

### PR DESCRIPTION
**Pull request by Fuzzy2319**
this pr adds `ApplicationMessageReceiver` definition and it's implementation

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33)* status: 1 of 3 files reviewed, 5 unresolved discussions (waiting on @Fuzzy2319)

___
*[`lib/al/include/Library/Application/ApplicationMessageReceiver.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKP2Pk3xN41jeHPZmr:-NwKP2Pk3xN41jeHPZms:b-7zht4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/include/Library/Application/ApplicationMessageReceiver.h#L11)):*
> ```objc
>     NotificationMessage_PerformanceModeChanged = 0x1f
> };  // should go into oe.h
> }  // namespace nn::oe
> ```

This should go into the `nnheaders` project itself, to avoid defining it twice when it gets added there. Feel free to PR it there yourself, or tell me and I'll try getting this into there.

Also, taking a deep dive through Atmosphere and `libnx`, I think the full list of message codes is defined here:
https://switchbrew.org/wiki/Applet_Manager_services#AppletMessage
https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/applet.h#L53-L64



_Code quote:_
```objc
namespace nn::oe {
enum NotificationMessage {
    NotificationMessage_FocusStateChanged = 0xf,  // not sure
    NotificationMessage_OperationModeChanged = 0x1e,
    NotificationMessage_PerformanceModeChanged = 0x1f
};  // should go into oe.h
}  // namespace nn::oe
```
___
*[`lib/al/include/Library/Application/ApplicationMessageReceiver.h` line 19 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKQ3dk-eYoLVMFeav0:-NwKQ3dk-eYoLVMFeav1:b-9jmrxe) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/include/Library/Application/ApplicationMessageReceiver.h#L19)):*
> ```objc
> 
>     nn::oe::OperationMode getOperationMode() const;
>     nn::oe::PerformanceMode getPerformaceMode() const;
> ```

I think they just return `bool`s, or do you have reason to assume otherwise?



_Code quote:_
```objc
    nn::oe::OperationMode getOperationMode() const;
    nn::oe::PerformanceMode getPerformaceMode() const;
```
___
*[`lib/al/include/Library/Application/ApplicationMessageReceiver.h` line 26 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKPSgq9Aa6Q30gPlr8:-NwKPSgq9Aa6Q30gPlr9:b-fs4pou) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/include/Library/Application/ApplicationMessageReceiver.h#L26)):*
> ```objc
> 
> private:
>     bool ukn[4]{};
> ```

Only two, as far as I can tell - which should be declared separately (two variables), and a proper name should be possible as well.
___
*[`lib/al/src/Library/Application/ApplicationMessageReceiver.cpp` line 8 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKPmYh49-gmSzym-Ph:-NwKPmYh49-gmSzym-Pi:b-qxy9at) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/src/Library/Application/ApplicationMessageReceiver.cpp#L8)):*
> ```cpp
>     ukn[1] = false;
>     mOperationMode = nn::oe::OperationMode_Handheld;
>     mPerformanceMode = nn::oe::PerformanceMode_Normal;
> ```

All of these can be defined in the header, then the constructor is just `{}`



_Code quote:_
```cpp
    ukn[0] = false;
    ukn[1] = false;
    mOperationMode = nn::oe::OperationMode_Handheld;
    mPerformanceMode = nn::oe::PerformanceMode_Normal;
```
___
*[`lib/al/src/Library/Application/ApplicationMessageReceiver.cpp` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKQQIM6EBZuYGbavZG:-NwKQQIM6EBZuYGbavZH:bo8aw01) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/src/Library/Application/ApplicationMessageReceiver.cpp#L40)):*
> ```cpp
>     nn::oe::SetOperationModeChangedNotificationEnabled(true);
>     nn::oe::SetPerformanceModeChangedNotificationEnabled(true);
>     nn::oe::SetFocusHandlingMode(3);  // enum?
> ```

Definitely an enum, it is even included in the function signature (`nn::oe::FocusHandlingMode`).

See `libnx`: https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/applet.h#L73-L81

**Comment by Fuzzy2319** [comment]
> _[`lib/al/include/Library/Application/ApplicationMessageReceiver.h` line 19 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKQ3dk-eYoLVMFeav0:-NwKQ3dk-eYoLVMFeav1:b-9jmrxe) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/include/Library/Application/ApplicationMessageReceiver.h#L19)):_
> 
> > ```cpp
> >     nn::oe::OperationMode getOperationMode() const;
> >     nn::oe::PerformanceMode getPerformaceMode() const;
> > ```
> 
> I think they just return `bool`s, or do you have reason to assume otherwise?
> 
> _Code quote:_
> 
> ```cpp
>     nn::oe::OperationMode getOperationMode() const;
>     nn::oe::PerformanceMode getPerformaceMode() const;
> ```
I tried with `bool` as return type but I never manage to get them matching so I tried to change the return type and I discover they get inlined inside the init function.
image
image

**Comment by Fuzzy2319** [comment]
> _[`lib/al/include/Library/Application/ApplicationMessageReceiver.h` line 11 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKP2Pk3xN41jeHPZmr:-NwKP2Pk3xN41jeHPZms:b-7zht4) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/include/Library/Application/ApplicationMessageReceiver.h#L11)):_
> 
> > ```objc
> >     NotificationMessage_PerformanceModeChanged = 0x1f
> > };  // should go into oe.h
> > }  // namespace nn::oe
> > ```
> 
> This should go into the `nnheaders` project itself, to avoid defining it twice when it gets added there. Feel free to PR it there yourself, or tell me and I'll try getting this into there.
> 
> Also, taking a deep dive through Atmosphere and `libnx`, I think the full list of message codes is defined here: https://switchbrew.org/wiki/Applet_Manager_services#AppletMessage https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/applet.h#L53-L64
> 
> _Code quote:_
> 
> ```objc
> namespace nn::oe {
> enum NotificationMessage {
>     NotificationMessage_FocusStateChanged = 0xf,  // not sure
>     NotificationMessage_OperationModeChanged = 0x1e,
>     NotificationMessage_PerformanceModeChanged = 0x1f
> };  // should go into oe.h
> }  // namespace nn::oe
> ```
> 
> _[`lib/al/src/Library/Application/ApplicationMessageReceiver.cpp` line 40 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33#-NwKQQIM6EBZuYGbavZG:-NwKQQIM6EBZuYGbavZH:bo8aw01) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/36fc2501b2089120339e2f679b03e279bd932787/lib/al/src/Library/Application/ApplicationMessageReceiver.cpp#L40)):_
> 
> > ```c++
> >     nn::oe::SetOperationModeChangedNotificationEnabled(true);
> >     nn::oe::SetPerformanceModeChangedNotificationEnabled(true);
> >     nn::oe::SetFocusHandlingMode(3);  // enum?
> > ```
> 
> Definitely an enum, it is even included in the function signature (`nn::oe::FocusHandlingMode`).
> 
> See `libnx`: https://github.com/switchbrew/libnx/blob/master/nx/include/switch/services/applet.h#L73-L81
I will be busy for the rest of the week so I will try to make the PR next week or you can do it if you have time by the end of the week :)

**Comment by MonsterDruide1** [comment]
https://github.com/open-ead/nnheaders/pull/29

This has been merged since, feel free to update `nnheaders` in this PR!

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Fuzzy2319)

**Pull request merged**
