### PR TITLE
decompile GameProgressData

### PR DESCRIPTION
**Pull request by tetraxile**
i wasn't able to get this function matching: https://decomp.me/scratch/2w4Fr

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
Great job! This is a large and important class, probably contains some interesting details.

Your mismatching function has been matched here:
https://decomp.me/scratch/IFXyd

> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-:-O4lidHzA0ZsSs4Mgxk5:b-uiamin)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @tetraxile)

___
*[`src/System/GameProgressData.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liTlV2u1KyLS_AJm1:-O4liTlV2u1KyLS_AJm2:bl9vi2m) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L12)):*
> ```objc
> public:
>     void write(al::ByamlWriter*) override;
>     void read(const al::ByamlIter&) override;
> ```

Throughout entire class: Name parameters



_Code quote:_
```objc
    void write(al::ByamlWriter*) override;
    void read(const al::ByamlIter&) override;
```
___
*[`src/System/GameProgressData.h` line 67 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liIZF4ITH_dcaQ0mk:-O4liIZF4ITH_dcaQ0ml:blx5v8n) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L67)):*
> ```objc
>     s32 mUnlockWorldStatusSecondBranch = 0;
>     s32 mHomeStatus = 0;
>     s32 mHomeLevel = 0;
> ```

All of these should be `enum class`es



_Code quote:_
```objc
    s32 mUnlockWorldStatusFirstBranch = 0;
    s32 mUnlockWorldStatusSecondBranch = 0;
    s32 mHomeStatus = 0;
    s32 mHomeLevel = 0;
```
___
*[`src/System/GameProgressData.h` line 70 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liKd37h-ehD2-g5Wj:-O4liKd37h-ehD2-g5Wk:bko105o) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L70)):*
> ```objc
>     const WorldList* mWorldList = nullptr;
>     bool* mIsFirstTimeWorld = nullptr;
>     s32 mWaterfallWorldProgress = 0;
> ```

`enum class`

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/System/GameProgressData.h` line 12 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liTlV2u1KyLS_AJm1:-O5FQ9fb4zUdiosW5kqS:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L12)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Throughout entire class: Name parameters
</blockquote></details>

done
___
*[`src/System/GameProgressData.h` line 67 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liIZF4ITH_dcaQ0mk:-O5FQBwL0gAGjewB7jp9:b6pv5ei) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L67)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

All of these should be `enum class`es
</blockquote></details>

i don't think it makes as much sense for `HomeLevel` to be an `enum class`, as its values seem to just correspond to particular kingdom indices. did the rest though
___
*[`src/System/GameProgressData.h` line 70 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O4liKd37h-ehD2-g5Wj:-O5FQUsB-ValMBG2zBwf:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/e0f48caf1b0df26e17c5499f7e9ddd10c37698d4/src/System/GameProgressData.h#L70)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

`enum class`
</blockquote></details>

done

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @tetraxile)

___
*[`src/System/GameProgressData.cpp` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiiWdE9AUR_stmyxT:-O5JiiWdE9AUR_stmyxU:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L32)):*
> ```cpp
>         mIsFirstTimeWorld[i] = true;
> 
>     mIsFirstTimeWorld[0] = false;
> ```





_Suggestion:_
```cpp
setAlreadyGoWorld(0);
```
___
*[`src/System/GameProgressData.cpp` line 58 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JjABH1Rs9890w29ka:-O5JjABH1Rs9890w29kb:b-8via24) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L58)):*
> ```cpp
>     s32 idxSky = mWorldList->tryFindWorldIndexByDevelopName("Sky");
> 
>     bool isUnlockPeach = mIsUnlockWorld[idxPeach];
> ```

Throughout a lot of the file



_Suggestion:_
```cpp
isUnlockWorld(idxPeach);
```
___
*[`src/System/GameProgressData.cpp` line 223 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5Jhdsk9SaTJ31xLAOm:-O5Jhdsl8LqNhwN7bLXb:b-45mxzk) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L223)):*
> ```cpp
>         return GameDataFunction::getWorldIndexCity();
>     case 8:
>         return idx != 0 ? GameDataFunction::getWorldIndexSnow() :
> ```

Flip this or the one above to be more consistent
___
*[`src/System/GameProgressData.cpp` line 244 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JhrIA5nmfK1w2QmJG:-O5JhrIA5nmfK1w2QmJH:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L244)):*
> ```cpp
>         return true;
> 
>     return false;
> ```





_Suggestion:_
```cpp
    return mUnlockWorldStatusSecondBranch == SecondBranch::None ||
          mUnlockWorldStatusSecondBranch == SecondBranch::Sea;
```
___
*[`src/System/GameProgressData.cpp` line 257 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiOOh8l_OH0GJo1Bs:-O5JiOOh8l_OH0GJo1Bt:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L257)):*
> ```cpp
> s32 GameProgressData::calcWorldNumForShineList() const {
>     s32 idxSpecial2 = GameDataFunction::getWorldIndexSpecial2();
>     if (mIsUnlockWorld[idxSpecial2] && !mIsFirstTimeWorld[idxSpecial2])
> ```





_Suggestion:_
```cpp
 if (isUnlockWorld(idxSpecial2) && isAlreadyGoWorld(idxSpecial2))
```
___
*[`src/System/GameProgressData.cpp` line 262 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiWwH3UGP0sLRjJfJ:-O5JiWwH3UGP0sLRjJfK:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L262)):*
> ```cpp
>     s32 worldNum = 0;
>     for (s32 i = 0; i < mWorldList->getWorldNum(); i++)
>         worldNum += !mIsFirstTimeWorld[i];
> ```





_Suggestion:_
```cpp
worldNum += isAlreadyGoWorld(i);
```

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @MonsterDruide1)

___
*[`src/System/GameProgressData.cpp` line 32 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiiWdE9AUR_stmyxT:-O5Ok-mwBbwFDvjntD0T:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L32)):*
> ```cpp
>         mIsFirstTimeWorld[i] = true;
> 
>     mIsFirstTimeWorld[0] = false;
> ```

done
___
*[`src/System/GameProgressData.cpp` line 58 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JjABH1Rs9890w29ka:-O5OjnVg9Phti4GVF0WX:b-z2i2zr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L58)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Throughout a lot of the file
</blockquote></details>

oddly, changing this one causes it to no longer match. i changed the others though
___
*[`src/System/GameProgressData.cpp` line 223 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5Jhdsk9SaTJ31xLAOm:-O5Ok9Lz6sIOj8G0ggrG:b1033sq) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L223)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Flip this or the one above to be more consistent
</blockquote></details>

changing either of them causes it to not match
___
*[`src/System/GameProgressData.cpp` line 244 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JhrIA5nmfK1w2QmJG:-O5Ol9XM96qExTVWM4cI:bhd08be) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L244)):*
> ```cpp
>         return true;
> 
>     return false;
> ```

i made the `if` condition easier to read but returning the result immediately causes it to not match anymore
___
*[`src/System/GameProgressData.cpp` line 257 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiOOh8l_OH0GJo1Bs:-O5OlAtB2tE5MgjmYYKi:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L257)):*
> ```cpp
> s32 GameProgressData::calcWorldNumForShineList() const {
>     s32 idxSpecial2 = GameDataFunction::getWorldIndexSpecial2();
>     if (mIsUnlockWorld[idxSpecial2] && !mIsFirstTimeWorld[idxSpecial2])
> ```

done
___
*[`src/System/GameProgressData.cpp` line 262 at r2](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5JiWwH3UGP0sLRjJfJ:-O5OlFEB9knnnxnS9ydo:bb7f2mf) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/3b1826486d022a6da543ec5c5bf284391d512a30/src/System/GameProgressData.cpp#L262)):*
> ```cpp
>     s32 worldNum = 0;
>     for (s32 i = 0; i < mWorldList->getWorldNum(); i++)
>         worldNum += !mIsFirstTimeWorld[i];
> ```

done

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: all files reviewed, 1 unresolved discussion (waiting on @tetraxile)

___
*[`src/System/GameProgressData.cpp` line 236 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5PMMHQ1w7jivuk5UDp:-O5PMMHQ1w7jivuk5UDq:b20jgy3) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f801b76438c20d9201d79a3d4ac117bb13d80187/src/System/GameProgressData.cpp#L236)):*
> ```cpp
> 
> bool GameProgressData::isUnlockFirstForest() const {
>     return mUnlockWorldStatusFirstBranch < FirstBranch::Lake;
> ```

If the one below cannot be adjusted to look like this one, can this one be adjusted to look like the one below? Split up the `<` into `==None` and `==Forest` either way, and if that matches too, put the verbose `if` as well

**Review by tetraxile — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @MonsterDruide1)

___
*[`src/System/GameProgressData.cpp` line 236 at r3](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145#-O5PMMHQ1w7jivuk5UDp:-O5PSz6N3AWQIy1wedLB:b2stpqg) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/f801b76438c20d9201d79a3d4ac117bb13d80187/src/System/GameProgressData.cpp#L236)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

If the one below cannot be adjusted to look like this one, can this one be adjusted to look like the one below? Split up the `<` into `==None` and `==Forest` either way, and if that matches too, put the verbose `if` as well
</blockquote></details>

yep that worked. there must be a better way to represent these but i certainly can't think of it

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/145)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @tetraxile)

**Pull request merged**
