### PR TITLE
Scene: Implement StageSceneStateStartSeparatePlay and StageSceneStateEndSeparatePlay (By GRA)

### PR DESCRIPTION
**Pull request by LynxDev2**
Another PR I'm doing for @GRAnimated. This one implements two `StageScene` states and adds some headers required for them

- - -
This change is [Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)

### CODE REVIEW

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)* status: 5 of 10 files reviewed, 1 unresolved discussion (waiting on @LynxDev2)

___
*[`lib/al/Library/Nerve/NerveStateBase.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Wm4UE7DS7afLDbl1C:-O9Wm4UE7DS7afLDbl1D:b-nhxcwr) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/lib/al/Library/Nerve/NerveStateBase.h#L10)):*
> ```objc
>     NerveStateBase(const char* stateName);
>     // Temporarily removed to avoid mismatch in the StageSceneStateEndSeparatePlay dtor
>     // virtual ~NerveStateBase();
> ```

Completely removed in another PR



_Code quote:_
```objc
    // Temporarily removed to avoid mismatch in the StageSceneStateEndSeparatePlay dtor
    // virtual ~NerveStateBase();
```
___
*[`lib/al/Library/Wipe/WipeSimple.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Wi8q19wMORouNyI51:-O9Wi8q19wMORouNyI52:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/lib/al/Library/Wipe/WipeSimple.h#L23)):*
> ```objc
>     void exeOpen();
> 
>     virtual void appear();
> ```





_Suggestion:_
```objc
void appear() override;
```

**Review by MonsterDruide1 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)* status: all files reviewed, 5 unresolved discussions (waiting on @LynxDev2)

___
*[`src/Scene/StageSceneStateEndSeparatePlay.cpp` line 52 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z02F3DnZoILfLMXLB:-O9Z02F3DnZoILfLMXLC:bdm7o2j) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateEndSeparatePlay.cpp#L52)):*
> ```cpp
>         rs::changeSeparatePlayMode(getScene(), false);
>     else
>         field_30 = true;
> ```

I'm not sure how this can be triggered in-game, as the controller applet view is non-cancelable, but based on how the `connectControllerSeparatePlay` works, this seems to be the intended meaning.



_Suggestion:_
```cpp
mIsCancel = true;
```
___
*[`src/Scene/StageSceneStatePauseMenu.h` line 94 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z1nFX8g4kFqtG7ehm:-O9Z1nFX8g4kFqtG7ehn:b-94k96s) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStatePauseMenu.h#L94)):*
> ```objc
>     StageSceneStateEndSeparatePlay* mStateEndSeparatePlay = nullptr;
>     StageSceneStateOption* mStateOption = nullptr;
>     al::LiveActor* mMarioHigh = nullptr;
> ```

Seems to be used in `getMarioActor()`



_Suggestion:_
```objc
al::LiveActor* mMarioActor = nullptr;
```
___
*[`src/Scene/StageSceneStateStartSeparatePlay.h` line 43 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z2YUB-dWv7cVQnTVJ:-O9Z2YUB-dWv7cVQnTVK:btv622z) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateStartSeparatePlay.h#L43)):*
> ```objc
>     FooterParts* mFooterParts = nullptr;
>     u16 field_40 = 0;
>     bool field_42 = false;
> ```

(either through canceling the controller popup, or pressing back before)



_Suggestion:_
```objc
bool mIsCancel = false;
```
___
*[`src/Scene/StageSceneStateStartSeparatePlay.cpp` line 69 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z2n986ob7K8isgFHz:-O9Z2n986ob7K8isgFI-:undefined) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateStartSeparatePlay.cpp#L69)):*
> ```cpp
>     if (al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.WaitDraw))
>         return true;
>     return al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.FadeIn);
> ```





_Suggestion:_
```cpp
    return al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.WaitDraw) || al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.FadeIn);
```

**Review by LynxDev2 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)* status: 3 of 10 files reviewed, 5 unresolved discussions (waiting on @MonsterDruide1)

___
*[`lib/al/Library/Nerve/NerveStateBase.h` line 10 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Wm4UE7DS7afLDbl1C:-O9ZGw7r5NSzX-kwzRqG:b-f8iiw6) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/lib/al/Library/Nerve/NerveStateBase.h#L10)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Completely removed in another PR
</blockquote></details>

Comment removed
___
*[`lib/al/Library/Wipe/WipeSimple.h` line 23 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Wi8q19wMORouNyI51:-O9ZH-48DqB1TXxQvU7w:bb6un1j) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/lib/al/Library/Wipe/WipeSimple.h#L23)):*
> ```objc
>     void exeOpen();
> 
>     virtual void appear();
> ```

Done
___
*[`src/Scene/StageSceneStateEndSeparatePlay.cpp` line 52 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z02F3DnZoILfLMXLB:-O9ZH69g7v95cb0CRG5U:b5ugqtp) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateEndSeparatePlay.cpp#L52)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

I'm not sure how this can be triggered in-game, as the controller applet view is non-cancelable, but based on how the `connectControllerSeparatePlay` works, this seems to be the intended meaning.
</blockquote></details>

I renamed it to that for now, but based on what I can see, `connectControllerSeparatePlay` return `true` if the applet was successfully opened and `false` if not. It doesn't care if a controller was connected or not
___
*[`src/Scene/StageSceneStatePauseMenu.h` line 94 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z1nFX8g4kFqtG7ehm:-O9ZHXOgCjr2ulMLScRp:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStatePauseMenu.h#L94)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

Seems to be used in `getMarioActor()`
</blockquote></details>

Done.
___
*[`src/Scene/StageSceneStateStartSeparatePlay.h` line 43 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z2YUB-dWv7cVQnTVJ:-O9ZH_DF02akt2Aczcxf:b-ya81ng) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateStartSeparatePlay.h#L43)):*
<details><summary><i>Previously, MonsterDruide1 wrote…</i></summary><blockquote>

(either through canceling the controller popup, or pressing back before)
</blockquote></details>

Same as above
___
*[`src/Scene/StageSceneStateStartSeparatePlay.cpp` line 69 at r1](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179#-O9Z2n986ob7K8isgFHz:-O9ZHcL-4wW8kvxEabk3:b-896fix) ([raw file](https://github.com/MonsterDruide1/OdysseyDecomp/blob/bae967ed881e0ad889f3f007a56e6f7c9e9a6d97/src/Scene/StageSceneStateStartSeparatePlay.cpp#L69)):*
> ```cpp
>     if (al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.WaitDraw))
>         return true;
>     return al::isNerve(this, &NrvStageSceneStateStartSeparatePlay.FadeIn);
> ```

Done.

**Review by MonsterDruide1 — APPROVED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/MonsterDruide1/OdysseyDecomp/179)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @LynxDev2)

**Pull request merged**
